package com.ais.migrate.mnims.hibernate.annotion;

// Generated 29 ¾.Â. 2553, 16:43:32 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MetabCompany generated by hbm2java
 */
@Entity
@Table(name = "METAB_COMPANY")
public class MetabCompany implements java.io.Serializable {

	private String company;
	private String description;
	private String thName;
	private String enName;
	private String address;
	private String subDistrict;
	private String district;
	private String province;
	private String street;

	public MetabCompany() {
	}

	public MetabCompany(String company) {
		this.company = company;
	}

	public MetabCompany(String company, String description, String thName,
			String enName, String address, String subDistrict, String district,
			String province, String street) {
		this.company = company;
		this.description = description;
		this.thName = thName;
		this.enName = enName;
		this.address = address;
		this.subDistrict = subDistrict;
		this.district = district;
		this.province = province;
		this.street = street;
	}

	@Id
	@Column(name = "COMPANY", unique = true, nullable = false, length = 10)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "DESCRIPTION", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TH_NAME", length = 100)
	public String getThName() {
		return this.thName;
	}

	public void setThName(String thName) {
		this.thName = thName;
	}

	@Column(name = "EN_NAME", length = 100)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "ADDRESS", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "SUB_DISTRICT", length = 100)
	public String getSubDistrict() {
		return this.subDistrict;
	}

	public void setSubDistrict(String subDistrict) {
		this.subDistrict = subDistrict;
	}

	@Column(name = "DISTRICT", length = 50)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "PROVINCE", length = 50)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "STREET", length = 100)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

}
