package th.co.ais.domain.sa;

// Generated 27 ¾.Â. 2557, 18:39:17 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SemSaSiteAppDoc generated by hbm2java
 */
@Entity
@Table(name = "SEM_SA_SITE_APP_DOC")
public class SemSaSiteAppDoc implements java.io.Serializable {

	private String siteAppDocId;
	private Long version;
	private String siteAppId;
	private String docCode;
	private String docFlag;
	private String recordStatus;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public SemSaSiteAppDoc() {
	}

	public SemSaSiteAppDoc(String siteAppDocId, String siteAppId, String docCode) {
		this.siteAppDocId = siteAppDocId;
		this.siteAppId = siteAppId;
		this.docCode = docCode;
	}

	public SemSaSiteAppDoc(String siteAppDocId, String siteAppId,
			String docCode, String docFlag, String recordStatus, Date createDt,
			String createBy, Date updateDt, String updateBy) {
		this.siteAppDocId = siteAppDocId;
		this.siteAppId = siteAppId;
		this.docCode = docCode;
		this.docFlag = docFlag;
		this.recordStatus = recordStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "SITE_APP_DOC_ID", unique = true, nullable = false, length = 50)
	public String getSiteAppDocId() {
		return this.siteAppDocId;
	}

	public void setSiteAppDocId(String siteAppDocId) {
		this.siteAppDocId = siteAppDocId;
	}

	@Version
	@Column(name = "VERSION", precision = 22, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "SITE_APP_ID", nullable = false, length = 50)
	public String getSiteAppId() {
		return this.siteAppId;
	}

	public void setSiteAppId(String siteAppId) {
		this.siteAppId = siteAppId;
	}

	@Column(name = "DOC_CODE", nullable = false, length = 2)
	public String getDocCode() {
		return this.docCode;
	}

	public void setDocCode(String docCode) {
		this.docCode = docCode;
	}

	@Column(name = "DOC_FLAG", length = 1)
	public String getDocFlag() {
		return this.docFlag;
	}

	public void setDocFlag(String docFlag) {
		this.docFlag = docFlag;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
