package th.co.ais.domain.sa;

// Generated 27 ¾.Â. 2557, 18:39:17 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SemSaSiteAppSite generated by hbm2java
 */
@Entity
@Table(name = "SEM_SA_SITE_APP_SITE")
public class SemSaSiteAppSite implements java.io.Serializable {

	private String siteAppSiteId;
	private Long version;
	private String siteAppId;
	private String locationId;
	private String siteId;
	private String siteCode;
	private String recordStatus;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public SemSaSiteAppSite() {
	}

	public SemSaSiteAppSite(String siteAppSiteId, String siteAppId) {
		this.siteAppSiteId = siteAppSiteId;
		this.siteAppId = siteAppId;
	}

	public SemSaSiteAppSite(String siteAppSiteId, String siteAppId,
			String locationId, String siteId, String siteCode,
			String recordStatus, Date createDt, String createBy, Date updateDt,
			String updateBy) {
		this.siteAppSiteId = siteAppSiteId;
		this.siteAppId = siteAppId;
		this.locationId = locationId;
		this.siteId = siteId;
		this.siteCode = siteCode;
		this.recordStatus = recordStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "SITE_APP_SITE_ID", unique = true, nullable = false, length = 50)
	public String getSiteAppSiteId() {
		return this.siteAppSiteId;
	}

	public void setSiteAppSiteId(String siteAppSiteId) {
		this.siteAppSiteId = siteAppSiteId;
	}

	@Version
	@Column(name = "VERSION", precision = 22, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "SITE_APP_ID", nullable = false, length = 50)
	public String getSiteAppId() {
		return this.siteAppId;
	}

	public void setSiteAppId(String siteAppId) {
		this.siteAppId = siteAppId;
	}

	@Column(name = "LOCATION_ID", length = 20)
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "SITE_ID", length = 20)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@Column(name = "SITE_CODE", length = 20)
	public String getSiteCode() {
		return this.siteCode;
	}

	public void setSiteCode(String siteCode) {
		this.siteCode = siteCode;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
