package th.co.ais.domain.sa;

// Generated 6 Á.¤. 2558, 13:24:36 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SemSaSiteAppMailAddr generated by hbm2java
 */
@Entity
@Table(name = "SEM_SA_SITE_APP_MAIL_ADDR")
public class SemSaSiteAppMailAddr implements java.io.Serializable {

	private SemSaSiteAppMailAddrId id;
	private Long version;
	private String mailName;
	private String mailHouseNo;
	private String mailBuilding;
	private String mailFloor;
	private String mailRoomNo;
	private String mailStreet;
	private String mailTambon;
	private String mailAmphurId;
	private String mailProvinceId;
	private String mailPostcode;
	private String recordStatus;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public SemSaSiteAppMailAddr() {
	}

	public SemSaSiteAppMailAddr(SemSaSiteAppMailAddrId id) {
		this.id = id;
	}

	public SemSaSiteAppMailAddr(SemSaSiteAppMailAddrId id, String mailName,
			String mailHouseNo, String mailBuilding, String mailFloor,
			String mailRoomNo, String mailStreet, String mailTambon,
			String mailAmphurId, String mailProvinceId, String mailPostcode,
			String recordStatus, Date createDt, String createBy, Date updateDt,
			String updateBy) {
		this.id = id;
		this.mailName = mailName;
		this.mailHouseNo = mailHouseNo;
		this.mailBuilding = mailBuilding;
		this.mailFloor = mailFloor;
		this.mailRoomNo = mailRoomNo;
		this.mailStreet = mailStreet;
		this.mailTambon = mailTambon;
		this.mailAmphurId = mailAmphurId;
		this.mailProvinceId = mailProvinceId;
		this.mailPostcode = mailPostcode;
		this.recordStatus = recordStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "siteAppId", column = @Column(name = "SITE_APP_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "mailAddrId", column = @Column(name = "MAIL_ADDR_ID", nullable = false, length = 50)) })
	public SemSaSiteAppMailAddrId getId() {
		return this.id;
	}

	public void setId(SemSaSiteAppMailAddrId id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", precision = 22, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "MAIL_NAME", length = 100)
	public String getMailName() {
		return this.mailName;
	}

	public void setMailName(String mailName) {
		this.mailName = mailName;
	}

	@Column(name = "MAIL_HOUSE_NO", length = 100)
	public String getMailHouseNo() {
		return this.mailHouseNo;
	}

	public void setMailHouseNo(String mailHouseNo) {
		this.mailHouseNo = mailHouseNo;
	}

	@Column(name = "MAIL_BUILDING", length = 100)
	public String getMailBuilding() {
		return this.mailBuilding;
	}

	public void setMailBuilding(String mailBuilding) {
		this.mailBuilding = mailBuilding;
	}

	@Column(name = "MAIL_FLOOR", length = 10)
	public String getMailFloor() {
		return this.mailFloor;
	}

	public void setMailFloor(String mailFloor) {
		this.mailFloor = mailFloor;
	}

	@Column(name = "MAIL_ROOM_NO", length = 10)
	public String getMailRoomNo() {
		return this.mailRoomNo;
	}

	public void setMailRoomNo(String mailRoomNo) {
		this.mailRoomNo = mailRoomNo;
	}

	@Column(name = "MAIL_STREET", length = 100)
	public String getMailStreet() {
		return this.mailStreet;
	}

	public void setMailStreet(String mailStreet) {
		this.mailStreet = mailStreet;
	}

	@Column(name = "MAIL_TAMBON", length = 100)
	public String getMailTambon() {
		return this.mailTambon;
	}

	public void setMailTambon(String mailTambon) {
		this.mailTambon = mailTambon;
	}

	@Column(name = "MAIL_AMPHUR_ID", length = 20)
	public String getMailAmphurId() {
		return this.mailAmphurId;
	}

	public void setMailAmphurId(String mailAmphurId) {
		this.mailAmphurId = mailAmphurId;
	}

	@Column(name = "MAIL_PROVINCE_ID", length = 20)
	public String getMailProvinceId() {
		return this.mailProvinceId;
	}

	public void setMailProvinceId(String mailProvinceId) {
		this.mailProvinceId = mailProvinceId;
	}

	@Column(name = "MAIL_POSTCODE", length = 10)
	public String getMailPostcode() {
		return this.mailPostcode;
	}

	public void setMailPostcode(String mailPostcode) {
		this.mailPostcode = mailPostcode;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
