package th.co.ais.domain.sa;

// Generated 27 ¾.Â. 2557, 18:39:17 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SemSaSiteAppDispute generated by hbm2java
 */
@Entity
@Table(name = "SEM_SA_SITE_APP_DISPUTE")
public class SemSaSiteAppDispute implements java.io.Serializable {

	private String siteAppDisputeId;
	private Long version;
	private String contractId;
	private Long disputeSeq;
	private String disputeGroup;
	private String title;
	private Date openDt;
	private Long titleSeq;
	private String detail;
	private Date statusDt;
	private String recordStatus;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public SemSaSiteAppDispute() {
	}

	public SemSaSiteAppDispute(String siteAppDisputeId, String contractId) {
		this.siteAppDisputeId = siteAppDisputeId;
		this.contractId = contractId;
	}

	public SemSaSiteAppDispute(String siteAppDisputeId, String contractId,
			Long disputeSeq, String disputeGroup, String title,
			Date openDt, Long titleSeq, String detail, Date statusDt,
			String recordStatus, Date createDt, String createBy, Date updateDt,
			String updateBy) {
		this.siteAppDisputeId = siteAppDisputeId;
		this.contractId = contractId;
		this.disputeSeq = disputeSeq;
		this.disputeGroup = disputeGroup;
		this.title = title;
		this.openDt = openDt;
		this.titleSeq = titleSeq;
		this.detail = detail;
		this.statusDt = statusDt;
		this.recordStatus = recordStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "SITE_APP_DISPUTE_ID", unique = true, nullable = false, length = 50)
	public String getSiteAppDisputeId() {
		return this.siteAppDisputeId;
	}

	public void setSiteAppDisputeId(String siteAppDisputeId) {
		this.siteAppDisputeId = siteAppDisputeId;
	}

	@Version
	@Column(name = "VERSION", precision = 22, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "CONTRACT_ID", nullable = false, length = 50)
	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	@Column(name = "DISPUTE_SEQ", precision = 22, scale = 0)
	public Long getDisputeSeq() {
		return this.disputeSeq;
	}

	public void setDisputeSeq(Long disputeSeq) {
		this.disputeSeq = disputeSeq;
	}

	@Column(name = "DISPUTE_GROUP", length = 20)
	public String getDisputeGroup() {
		return this.disputeGroup;
	}

	public void setDisputeGroup(String disputeGroup) {
		this.disputeGroup = disputeGroup;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OPEN_DT", length = 7)
	public Date getOpenDt() {
		return this.openDt;
	}

	public void setOpenDt(Date openDt) {
		this.openDt = openDt;
	}

	@Column(name = "TITLE_SEQ", precision = 22, scale = 0)
	public Long getTitleSeq() {
		return this.titleSeq;
	}

	public void setTitleSeq(Long titleSeq) {
		this.titleSeq = titleSeq;
	}

	@Column(name = "DETAIL", length = 2000)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STATUS_DT", length = 7)
	public Date getStatusDt() {
		return this.statusDt;
	}

	public void setStatusDt(Date statusDt) {
		this.statusDt = statusDt;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
