package th.co.ais.domain.sa;

// Generated 6 Á.¤. 2558, 13:24:36 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SemSaSiteAppMailAddrId generated by hbm2java
 */
@Embeddable
public class SemSaSiteAppMailAddrId implements java.io.Serializable {

	private String siteAppId;
	private String mailAddrId;

	public SemSaSiteAppMailAddrId() {
	}

	public SemSaSiteAppMailAddrId(String siteAppId, String mailAddrId) {
		this.siteAppId = siteAppId;
		this.mailAddrId = mailAddrId;
	}

	@Column(name = "SITE_APP_ID", nullable = false, length = 50)
	public String getSiteAppId() {
		return this.siteAppId;
	}

	public void setSiteAppId(String siteAppId) {
		this.siteAppId = siteAppId;
	}

	@Column(name = "MAIL_ADDR_ID", nullable = false, length = 50)
	public String getMailAddrId() {
		return this.mailAddrId;
	}

	public void setMailAddrId(String mailAddrId) {
		this.mailAddrId = mailAddrId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SemSaSiteAppMailAddrId))
			return false;
		SemSaSiteAppMailAddrId castOther = (SemSaSiteAppMailAddrId) other;

		return ((this.getSiteAppId() == castOther.getSiteAppId()) || (this
				.getSiteAppId() != null
				&& castOther.getSiteAppId() != null && this.getSiteAppId()
				.equals(castOther.getSiteAppId())))
				&& ((this.getMailAddrId() == castOther.getMailAddrId()) || (this
						.getMailAddrId() != null
						&& castOther.getMailAddrId() != null && this
						.getMailAddrId().equals(castOther.getMailAddrId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSiteAppId() == null ? 0 : this.getSiteAppId().hashCode());
		result = 37
				* result
				+ (getMailAddrId() == null ? 0 : this.getMailAddrId()
						.hashCode());
		return result;
	}

}
