package th.co.ais.domain.sa;

// Generated 20 ¸.¤. 2557, 17:59:55 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SemSaSiteContractStatus generated by hbm2java
 */
@Entity
@Table(name = "SEM_SA_SITE_CONTRACT_STATUS")
public class SemSaSiteContractStatus implements java.io.Serializable {

	private String siteContractStatusId;
	private String siteAppId;
	private BigDecimal seq;
	private String contractStatus;
	private String remark;
	private String recordStatus;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public SemSaSiteContractStatus() {
	}

	public SemSaSiteContractStatus(String siteContractStatusId) {
		this.siteContractStatusId = siteContractStatusId;
	}

	public SemSaSiteContractStatus(String siteContractStatusId,
			String siteAppId, BigDecimal seq, String contractStatus,
			String remark, String recordStatus, Date createDt, String createBy,
			Date updateDt, String updateBy) {
		this.siteContractStatusId = siteContractStatusId;
		this.siteAppId = siteAppId;
		this.seq = seq;
		this.contractStatus = contractStatus;
		this.remark = remark;
		this.recordStatus = recordStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "SITE_CONTRACT_STATUS_ID", unique = true, nullable = false, length = 50)
	public String getSiteContractStatusId() {
		return this.siteContractStatusId;
	}

	public void setSiteContractStatusId(String siteContractStatusId) {
		this.siteContractStatusId = siteContractStatusId;
	}

	@Column(name = "SITE_APP_ID", length = 50)
	public String getSiteAppId() {
		return this.siteAppId;
	}

	public void setSiteAppId(String siteAppId) {
		this.siteAppId = siteAppId;
	}

	@Column(name = "SEQ", precision = 22, scale = 0)
	public BigDecimal getSeq() {
		return this.seq;
	}

	public void setSeq(BigDecimal seq) {
		this.seq = seq;
	}

	@Column(name = "CONTRACT_STATUS", length = 2)
	public String getContractStatus() {
		return this.contractStatus;
	}

	public void setContractStatus(String contractStatus) {
		this.contractStatus = contractStatus;
	}

	@Column(name = "REMARK", length = 2000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
