package th.co.ais.util;

public enum ELovType {
					  T_MODULE("MODULE"),
					  
					  //module gm
					  T_COMPANY("CT_COMPANY"),
					  T_CT_VENDOR_TYPE("CT_VENDOR_TYPE"),
					  T_CT_BLOCK_STATUS("CT_BLOCK_STATUS"),
					  T_CT_DUPLICATE_STATUS("CT_DUPLICATE_STATUS"),
					  T_CT_VENDOR_STATUS("CT_VENDOR_STATUS"),
					  T_CT_BOOKBANK_STATUS("CT_BOOKBANK_STATUS"),
					  T_CT_FINANCE_STATUS("CT_FN_STATUS"),
					  T_CT_PAYEE_BOOKBANK_STATUS("CT_PB_STATUS"),
					  T_CT_BANK_ACC_TYPE("CT_BANK_ACC_TYPE"),
					  T_CT_EXPENSE_TYPE("CT_EXPENSE_TYPE"),
					  T_SAP_CT_EXPENSE_TYPE("SAP_CT_EXPENSE_TYPE"),
					  T_CT_PAYMENT_METHOD("CT_PAYMENT_METHOD"),
					  T_CT_PAYMENT_STATUS("CT_PAYMENT_STATUS"),
					  T_CT_PAYMENT_REJECT_STATUS("CT_PAYMENT_REJECT_STATUS"),
					  T_CT_PAYMENT_TYPE("CT_PAYMENT_TYPE"),
					  T_CT_NETWORK_STATUS("CT_NETWORK_STATUS"),
					  T_CT_BG_STATUS("CT_BG_STATUS"), 
					  T_CT_BG_BANK("CT_BG_BANK"), 
					  T_CT_DAY_PER_YEAR("CT_DAY_PER_YEAR"),
					  T_CT_DAY_PER_MONTH("CT_DAY_PER_MONTH"),
					  T_CT_VAT_TYPE("CT_VAT_TYPE"),
					  T_CT_PERIOD_TYPE("CT_PERIOD_TYPE"),
					  T_CT_FIX_RENTAL_ADD_PERCENT("CT_FIX_RENTAL_ADD_PERCENT"),
					  T_CT_PAY_PERIOD_TYPE("CT_PAY_PERIOD_TYPE"), 
					  T_CT_DEPOSIT_TYPE("CT_DEPOSIT_TYPE"), 
					  T_CP_TOT_STATUS("CP_TOT_STATUS"), 
					  T_CP_CONSTRUCT_STATUS("CP_CONSTRUCT_STATUS"), 
					  T_CP_CONSTRUCT_TYPE("CP_CONSTRUCT_TYPE"),
					  T_CP_CON_BILL_PAY_STATUS("CP_CON_BILL_PAY_STATUS"),
					  T_CT_PAYMENT_DOC_TYPE("CT_PAYMENT_DOC_TYPE"),
					  T_CT_MODULE("CT_MODULE"),
					  T_CT_PAYEE_STATUS("CT_PAYEE_STATUS"),
					  T_CT_ACCOUNT_STATUS("CT_ACC_STATUS"),
					  T_CT_PAYEE_TYPE("CT_PAYEE_TYPE"),
					  T_CT_BANK_STATUS("CT_BANK_STATUS"),
					  T_CT_WHT_RATE("CT_WHT_RATE"),
					  T_CT_WHT_TYPE("CT_WHT_TYPE"),
					  T_CT_BG_TYPE("CT_BG_TYPE"),
					  T_CT_LOV_TYPE_LIST("LOV_TYPE_LIST"),
					  T_CT_SAP_ERROR_STATUS("CT_SAP_ERROR_STATUS"),
					  T_CT_MASTER_PARAMETER_TYPE("CT_MASTER_PARAMETER_TYPE"),
					  T_CT_SITE_GROUP("CT_SITE_GROUP"),
					  T_CT_PAYMENT_SPECIAL("CT_PAYMENT_SPECIAL"),
					  T_CT_VENDOR_BRANCH("CT_VENDOR_BRANCH"),
					  T_CT_GL_TYPE("CT_GL_TYPE"),
					  //module ir
					  T_IR_TYPE("IR_TYPE"),
					  T_IR_NETWORK_TYPES("IR_NETWORK_TYPE"),
					  T_IR_TRANSFER_TYPES("IR_TRANSFER_TYPE"),
					  T_IR_LOSS_TYPE("IR_LOSS_TYPE"),
					  T_IR_LOSS_SUB_TYPE("IR_LOSS_SUB_TYPE"),
					  T_IR_POLICY_TYPE("IR_POLICY_TYPE"),
					  T_IR_DRAFT_STATUS("IR_DRAFT_STATUS"),
					  T_IR_DOC_TYPE("IR_DOC_TYPE"),
					  T_IR_PAY_TYPE("IR_PAY_TYPE"),
					  T_IR_DATE_TYPE("IR_DATE_TYPE"),
					  T_IR_CLAIM_STATUS("IR_CLAIM_STATUS"),
					  T_IR_CLAIM_CONTACT("IR_CLAIM_CONTACT"),
					  T_IR_LOSS_ASSET_TYPE("IR_LOSS_ASSET_TYPE"),
					  T_IR_ACQ_TYPE("IR_ACQ_TYPE"),
					  T_CT_VAT_RATE("CT_VAT_RATE"),
					  T_CT_SERVICE("CT_SERVICE"),
					  
					  //module si
					  T_SI_APPROVE_TYPE("SI_REQ_TYPE"),
					  T_SI_SITE_APPROVE_TYPE("RPT_SITE_APPROVE_TYPE"),
					  T_SI_APPROVE_STATUS("SI_SITE_APPROVE_STATUS"), 
					  T_SI_REQ_DOC_TYPE("SI_REQ_DOC_TYPE"),
					  T_SI_LEGAL_APPROVE_STATUS("SI_LEGAL_APPROVE_STATUS"),
					  T_SI_SITE_TYPE("SI_SITE_TYPE"),
					  T_SI_SITE_INFO_STATUS("SI_SITE_INFO_STATUS"),
					  T_SI_SITE_STATUS("SI_SITE_STATUS"),
					  T_SI_SEND_RENEW_A_STATUS("SI_SEND_RENEW_A_STATUS"),
					  T_SI_SEND_RENEW_TYPE("SI_SEND_RENEW_TYPE"),
					  T_SI_SEND_RENEW_STATUS("SI_SEND_RENEW_STATUS"), 
					  T_SI_PLACE_TYPE("SI_PLACE_TYPE"),
					  T_SI_DECK_AREA_TYPE("SI_DECK_AREA_TYPE"), 
					  T_SI_BUILDING_AREA_TYPE("SI_BUILDING_AREA_TYPE"), 
					  T_SI_AREA_UNIT_TYPE("CT_AREA_UNIT_TYPE"),
					  T_SI_PROPERTY_TAX_TYPE("SI_PROPERTY_TAX_TYPE"),
					  T_SI_PROPERTY_TAX_PAY_TYPE("SI_PROPERTY_TAX_PAY_TYPE"),
					  T_SI_RENEW_AGE_CODE("SI_RENEW_AGE_CODE"),
					  T_SI_PMS_STATUS("CT_PMS_STATUS"),
					  T_SI_CONTRACT_DOC_TYPE("SI_CONTRACT_DOC_TYPE"),
					  T_SI_SITE_OWNER_GROUP("SI_SITE_OWNER_GROUP"),
					  T_SI_ROOM_AREA_TYPE("SI_ROOM_AREA_TYPE"),
					  T_SI_LAND_AREA_TYPE("SI_LAND_AREA_TYPE"), 
					  T_SI_SITE_APPROVE_FROM("SI_SITE_APPROVE_FROM"), 
					  T_SI_LEGAL_CHECK_DOC_STATUS("SI_LEGAL_CHECK_DOC_STATUS"),
					  T_SI_SEARCH_PICO("SI_SEARCH_PICO"),
					  T_SI_TODO_MENU_REQ_TYPE("TODO_MENU_REQ_TYPE"),
					  
					  T_SI_LEGAL_PLACE_TYPE("SI_LEGAL_PLACE_TYPE"),
					  T_SI_LEGAL_PARTIES_TYPE("SI_LEGAL_PARTIES_TYPE"),
					  
					  // module rt
					  T_RT_VERIFY_STATUS("RT_VERIFY_STATUS"),
					  T_RT_RENTAL_JOB_STATUS("RT_RENTAL_JOB_STATUS"), 
					  T_RT_JOB_TYPE_N("RT_JOB_TYPE_N"), 
					  T_RT_JOB_TYPE_E("RT_JOB_TYPE_E"),
					  T_RT_JOB_TYPE("RT_JOB_TYPE"),
					  T_RT_CL_RECEIPT_STATUS("RT_CLR_RECEIPT_STATUS"),
					  T_RT_PETTY_CASH_PAY_STATUS("RT_PETTY_CASH_PAY_STATUS"), 
					  T_RT_RETURN_DPS_BG("RT_RETURN_DPS_BG"), 
					  T_RT_RETURN_DPS_CASH("RT_RETURN_DPS_CASH"),
					  T_RT_PETTY_CASH_SUBJECT("RT_PETTY_CASH_SUBJECT"),
					  T_RT_PETTY_CASH_CATEGORY("RT_PETTY_CASH_CATEGORY"),
					  T_RT_CAL("RT_CAL"),
					  
					  //module cp
					  T_CP_SITE_CONSTRUCT_STATUS("CP_SITE_CONSTRUCT_STATUS"),
					  T_CP_POST_TYPE("CP_POST_TYPE"),
					  T_CP_CON_RESULT_STATUS("CP_CON_RESULT_STATUS"),		
					   
					 
					  
					  
					  //module bg
					  T_BG_BANK("CT_BG_BANK"),
					 
					 
					//module pt
					  T_PT_PROPERTY_TAX_PAY_TYPE("SI_PROPERTY_TAX_PAY_TYPE"),
					  T_PT_PTAX_ESTM_STATUS("PT_PTAX_ESTM_STATUS"),
					  T_PT_PENALTY_TYPE("PT_PENALTY_TYPE"),
					  
					//module co
					  T_CO_CONTRACT_STATUS("CO_CONTRACT_STATUS"),
					  T_CO_CHECK_DOC_STATUS("CO_CHECK_DOC_STATUS"),
					  T_CO_DUTY_PAY_STATUS("CO_DUTY_PAY_STATUS"),
					  T_CO_TOT_SEND_STATUS("CO_TOT_SEND_STATUS"),
					  T_CO_BORROW_OFFICER("CO_BORROW_OFFICER"),
					  T_CO_CONTRACT_STATUS_REQ_TYPE("CO_CONTRACT_STATUS_REQ_TYPE"),
					  T_CO_SUB_RENT_TYPE("CO_SUB_RENT_TYPE"),
					  T_CO_SUB_RENT_STATUS("CO_SUB_RENT_STATUS"),
					  T_CO_SUB_RENT_SEARCH_SUMMARY("CO_SUB_RENT_SEARCH_SUMMARY"),
					  T_CO_BORROW_FOR_TYPE("CO_BORROW_FOR_TYPE"),
					  INTERNAL_CONTRACT_STATUS("INTERNAL_CONTRACT_STATUS"),
					  
					   //module el
					  EL_ELECTRIC_TYPE("EL_ELECTRIC_TYPE"),
					  EL_ELECTRIC_TYPE2("EL_ELECTRIC_TYPE2"),
					  EL_EXPENSE_TYPE("EL_EXPENSE_TYPE"),
					  EL_DOC_TYPE("EL_DOC_TYPE"),
					  CT_DEPOSIT_TYPE("CT_DEPOSIT_TYPE"),
					  EL_PROCESS_STATUS("EL_PROCESS_STATUS"),
					  EL_WARRANT_TYPE("EL_WARRANT_TYPE"),
					  EL_MEA_STATUS("EL_MEA_STATUS"),
					  EL_PEA_STATUS("EL_PEA_STATUS"),
					  EL_PRIVATE_STATUS("EL_PRIVATE_STATUS"),
					  EL_OTHERSITE_STATUS("EL_OTHERSITE_STATUS"),
					  EL_ADDRESS("EL_ADDRESS"),
					  EL_DEPOSIT_TYPE("EL_DEPOSIT_TYPE"),
					  EL_PAYMENT_STATUS("EL_PAYMENT_STATUS"), 
					  T_EL_ELECTRIC_TYPE ("EL_ELECTRIC_TYPE"),
					  T_EL_ONEBILL_STATUS("EL_ONEBILL_STATUS"),
					  T_EL_WARRANT_TYPE("EL_WARRANT_TYPE"),
					  EL_WARRANT_STATUS("EL_WARRANT_STATUS"),
					  EL_OUTSTANDING_FLAG("EL_OUTSTANDING_FLAG"),
					  EL_VENDOR_TYPE("EL_VENDOR_TYPE"),
					  EL_METER_TYPE("EL_METER_TYPE"),
					  EL_METER_STATUS("EL_METER_STATUS"),
					  T_EL_TXTFILE_FORMAT("EL_TXTFILE_FORMAT"),
					  EL_TXTFILE_STATUS("EL_TXTFILE_STATUS"),
					  T_EL_TXTFILE_PAID_FLAG("EL_TXTFILE_PAID_FLAG"),
					  T_EL_TXTFILE_ERROR_CODE("EL_TXTFILE_ERROR_CODE"),
					  EL_BANK_NAME("EL_BANK_NAME"),
					  CT_PAYMENT_TYPE("CT_PAYMENT_TYPE"),
					  CT_WHT_TYPE("CT_WHT_TYPE"),
					  EL_UPDATE_STATUS("EL_UPDATE_STATUS"),
					  CT_CR_BANK("CT_CR_BANK"),
					  EL_ACTION_PROCESS("EL_ACTION_PROCESS"),
					  EL_ORDER_BY("EL_ORDER_BY"),
					  EL_METER_DATA("EL_METER_DATA"),
					  EL_ON_SERVICE("EL_ON_SERVICE"),
					  EL_BY_TYPE("EL_BY_TYPE"),
					  EL_OWNER_GROUP("EL_OWNER_GROUP"),
					  EL_MONTH_PERCENT_GROWTH("EL_MONTH_PERCENT_GROWTH"),
					  EL_TYPE_PERCENT_GROWTH("EL_TYPE_PERCENT_GROWTH"),
					  
					  
					//module ac
					  T_SAP_TRX_LOG("SAP_TRX_LOG"),
					  
					//module Report
					  RT_RPT_SEMRRT022_EXPENSE_TYPE("RPT_SEMRRT022_EXPENSE_TYPE"),
					  
					//Attachment
					  T_CT_ATTACH_MODULE("CT_ATTACH_MODULE"),
					  T_CT_ATTACH_SUB_MODULE("CT_ATTACH_SUB_MODULE"),
					  
					  
					  // module SA
					  T_SA_TEAM_LIST("SA_TEAM_LIST"),
					  T_SA_MEMBER_LIST("SA_MEMBER_LIST"),
					  T_SA_APPROVE_TYPE("SA_REQ_TYPE"),
					  T_SA_APP_RESULT("SA_APP_RESULT"),
					  T_SA_APP_RESULT_A("SA_APP_RESULT_A"),
					  T_SA_SITE_STATUS("SA_SITE_APPROVE_STATUS"),
					  T_SA_FLOW_STATUS("SA_FLOW_STATUS"),
					  T_SA_CONTRACT_STATUS("SA_CONTRACT_STATUS"),
					  T_CT_CO_COMPANY("CT_CO_COMPANY"),
					  T_SA_CO_OPERATOR("SA_CO_OPERATOR"),
					  T_SA_EL_COND_TYPE("SA_ELECTRIC_COND_TYPE"),
					  T_SA_EL_COND_SUB_TYPE("SA_ELECTRIC_COND_SUBTYPE"),
					  T_SA_IR_TYPE("SA_INSURANCE_TYPE"),
					  T_SA_REQ_TITLE("SA_REQ_TITLE"),
					  T_SA_RENT_ADJ("SA_RENT_ADJ"),
					  T_SA_OWNER_CATEGORY("CT_CATEGORY"),
					  T_SA_OWNER_SUB_CATEGORY("CT_SUB_CATEGORY"),
					  T_SA_ELECTRIC_TYPE("SA_ELECTRIC_TYPE"),
					  
					  
					// module MM
					  T_MM_SAP_VENDOR_STATUS("SAP_VENDOR_STATUS"),
					  T_MM_SAP_BOOKBANK_STATUS("SAP_BOOKBANK_STATUS"),
					  T_MM_SAP_BLOCK_STATUS("SAP_BLOCK_STATUS"),
					  T_MM_SAP_BLACKLIST_STATUS("SAP_BLACKLIST_STATUS"),
					  T_MM_SAP_PAYEE_STATUS("SAP_PAYEE_STATUS"),
					  T_MM_SAP_BP_STATUS("SAP_BP_STATUS"),
					  
					  T_MM_SAP_VENDOR_FLOW_STATUS("SAP_VENDOR_FLOW_STATUS"),
					  T_MM_SAP_BOOKBANK_FLOW_STATUS("SAP_BOOKBANK_FLOW_STATUS"),
					  T_MM_SAP_PAYEE_FLOW_STATUS("SAP_PAYEE_FLOW_STATUS"),
					  T_MM_SAP_BP_FLOW_STATUS("SAP_BP_FLOW_STATUS"),
					  T_MM_SAP_BOOKBANK_PAYEE_FLOW_STATUS("SAP_BOOKBANK_PAYEE_FLOW_STATUS"),
					  
					  T_MM_SAP_WHT_TYPE("SAP_CT_WHT_TYPE"),
					  T_CT_GET_URL("T_CT_GET_URL"),
					  T_MM_SAP_NO_EXPORT_BATCH_CRI("SAP_EXPORT_BATCH_CRITERIA"),
					  T_SI_LEGAL_DOC_TYPE("SI_LEGAL_DOC_TYPE"),
					  T_SA_SITE_APP_TITLE("SAP_TITLE"),
					 
					// module BP
					  T_BP_TITLE("BP_TITLE");

	public String name = "";
	
	ELovType(String name) {
		this.name = name;
	}
}