package th.co.ais.util;

public enum EQueryName {Q_ACQUISITION_COST("queryAcquisitionCost"), 
	Q_ACQUISITION_COST_DETAIL("queryAcquisitionCostDetailSP"),
	Q_REPLACEMENT_VALUE("queryReplacementValue"), 
	Q_REPLACEMENT_VALUE_EDT("queryReplacementValueEdt"),
	Q_INSURED("queryInsured"), 
	Q_INSURED_EDT("queryInsuredEdt"), 
	Q_DEDUCTIBLE("queryDeductible"), 
	Q_DEDUCTIBLE_EDT("queryDeductibleEdt"), 
	Q_PREMIUM_SRCH("queryPremium"), 
	Q_PREMIUM_EDT("queryPremiumEdt"), 
	Q_POLICY("queryPolicySP"),
	Q_VENDOR_MASTER("queryVendorMaster"),
	Q_CT001_M_SRCH("queryCT001SrchMSP"), 
	Q_CT001_EXPORT("queryCT001Export"),
	Q_CT001_L_SRCH("queryLessorInfo"),
	Q_CT006_SRCH("queryMCT006Srch"),
	Q_CT007_SRCH("queryCT007Search"),
	Q_MIR008_EX1("queryMIR008Export1"),
	Q_MIR008_EX2("queryMIR008Export2"),
	Q_MIR008_EX3("queryMIR008Export3"),
	SP_UPDATE_CT001("mct001Update"),
	SP_APPROVE_CT001("mct001ActApprove"),
	SP_CT001_EX_BANK("queryCT001ExportBank"),
	//added by NEW 20151015
	SP_CT001_EX_VENDOR_TO_LEADER("queryCT001ExportVendorToLeader"),
	SP_CT001_EX_VENDOR_BOOKBANK_TO_LEADER("queryCT001ExportVendorBookbankToLeader"),
	SP_CT001_EX_PAYEE_TO_LEADER("queryCT001ExportPayeeToLeader"),
	SP_CT001_EX_PAYEE_BOOKBANK_TO_LEADER("queryCT001ExportPayeeBookbankToLeader"),
	SP_CT001_Q_POPUP_REJECT("queryCT001PopupReject"),
	SP_UPDATE_CT002_RENT("mct002UpdateRent"),
	SP_CHK_VENDOR_MULTI("spCheckVendorMulti"),
	Q_SEARCH_ELECTRICAL_METER_MANAGEMENT("querySearchElMeterManagement"),
	Q_EL_SEARCH_REC_DTL("queryElSearchRecDtl"),
	Q_EL_SEARCH_BG("querySearchBg"),
	Q_CHECK_VENDOR_MASTER("queryCheckVendorMasterExisted"),
	Q_CHECK_VENDOR_MASTER_S("queryCheckVendorMasterBeforSave"),
	Q_CHECK_PAYEE_MASTER("queryCheckPayeeMasterExisted"),
	Q_SEARCH_SITE_APPROVE_DISPLAY("querySearchSiteApproveDisplay"), 
	Q_SEARCH_SITE_APPROVE("querySearchSiteApproveById"), 
	Q_SERACH_MAP_LOC_BY_SITE_APPROVE_ID("querySearchSiteApproveMapLocBySiteApproveId"), 
	Q_SEQ_MAP_LOC_BY_SITE_APPROVE_ID("querySeqSiteApproveMapLocBySiteApproveId"), 
	Q_SEARCH_SITE_TERMINATE("querySearchSiteTerminate"),
	Q_SEARCH_POPUP_SITE_CONTRACT("queryPopupContractSearch"),
	Q_SEARCH_POPUP_SITE_CONTRACT_ANTCRI("queryPopupContractAntCriSearch"),
	Q_SEARCH_MAP_LOC_BY_SITE_INFO_ID("querySearchSiteInfoMapLoc"),
	Q_SEARCH_SITE_TERMINATE_BY_ID("querySearchSiteTerminatePK"), 
	Q_SITE_LOCATION("querySiteLocationSearch"),
	Q_SITE_LOCATION_FOR_IR("querySiteLocationSearchForIR"), 
	Q_SITE_LOCATION_BY_SITE_INFO_ID("querySiteLocationBySiteInfoId"),
	Q_SEARCH_LEGAL_APPROVE_DISPLAY("querySearchLegalApproveDisplay"),
	Q_SEARCH_LEGAL_APPROVE_SRCH_BY_APPV("querySearchLegalApproveByAppv"),
	Q_SEARCH_SITE_INFO("querySearchSiteInfo"),
	Q_SEARCH_SITE_ACQ("querySearchSiteAcq"),
	Q_SEARCH_SITE_ACQ_PAYMENT_REPORT("queryMsaPaymentReportParam"),
	Q_SEARCH_SITE_APP("querySearchSiteApp"),
	Q_MSA003_REPORT_PARAM("queryMsa003ReportParam"),
	Q_SEARCH_SEND_RENEW("querySearchSendRenew"),
	SP_SEND_RENEW_ACT("sendRenewAct"),
	Q_SEARCH_SEND_RENEW_EXP("querySearchSendRenewExp"),
	Q_SEARCH_BG_MASTER("querySearchBGMaster"),
	Q_SEARCH_APPROVE_RENEW("querySearchApproveRenew"),
	Q_SEARCH_SUM_RENT("querySearchSumRent"),
	Q_SEARCH_SUM_DEPOSIT_RENT("querySearchSumDepositRent"), 
	Q_SEARCH_VERIFY_RENTAL_BY_SITE_INFO("querySearchVerifyRentalSiteInfo"),
	Q_SEARCH_SITE_INFO_SEQ_NO("querySearchSiteInfoSeq"),
	Q_SEARCH_SITE_INFO_MAP_LOC_SEQ_NO("querySearchSiteInfoMapLocSeq"),
	Q_SEARCH_QUERY_RENEW_SAM("querySearchQueryRenewSAM"),
	Q_SEARCH_QUERY_NETWORK_STATUS("querySearchQueryNetworkStatus"),
	Q_SEARCH_QUERY_SITE_MANAGEMENT ("querySearchQuerySiteManagement"),
	Q_SEARCH_RENTALPAY("querySearchRentalPay"),
	Q_SEARCH_RENTALPAY_S("querySearchRentalPayS"),
	Q_SEARCH_RENTALPAY_S2("querySearchRentalPayS2"),
	Q_SEARCH_RENTALPAY_NORMAL("querySearchRentalPayNormal"),
	Q_SEARCH_RENTALPAY_NORMAL_LP("querySearchRentalPayNormalLP"),
	Q_SEARCH_RENTALPAY_NORMAL_D("querySearchRentalPayNormalD"),
	Q_SEARCH_CONSTRUCTIONPERMISSION("querySearchConstructionPermission"),
	Q_SEARCH_CONSTRUCTION_LOCATION("querySearchConstructionLocation"),
	Q_SEARCH_LESSOR_ADDRESS("queryLessorAddress"),
	Q_SEARCH_SITE_ADDRESS("querySiteAddress"),
	SP_MSI002_SEQ_LEGAL("spMsi002SeqLegal"), 
	SP_MSI002_SAVE("spMsi002Save"),
	SP_MRT001_CHECK_DATE("spMrt001CheckDate"), 
	SP_MRT001_SRCH_RENT_COND("spMrt001SrchRentCond"), 
	SP_MRT001_SRCH_RENT_DETAIL("spMrt001SrchRentDetail"), 
	SP_MRT001_SRCH_RENT_HIST("spMrt001SrchRentHist"), 
	SP_MRT001_SRCH_VENDOR("spMrt001SrchVendor"), 
	SP_MRT001_SRCH_PAYEE("spMrt001SrchPayee"), 
	SP_MRT001_UPD_RENT_PAY("spMrt001UpdRentPay"), 
	SP_MRT001_UPD_RENT_MAP("spMrt001UpdRentMap"), 
	SP_MRT001_UPD_DPST_PAY("spMrt001UpdDpstPay"), 
	SP_MRT001_UPD_DPST_MAP("spMrt001UpdDpstMap"), 
	SP_MRT001_UPD_RENT_JOB("spMrt001UpdRentJob"), 
	SP_MRT001_SRCH_DPST_COND("spMrt001SrchDpstCond"), 
	SP_MRT001_SRCH_DPST_DETAIL("spMrt001SrchDpstDetail"), 
	SP_MRT001_BOOKBANK("spMrt001BookBank"), 
	SP_MRT001_VERIFY_STATUS("spMrt001VerifyStatus"), 
	SP_MRT001_RENT_CAL("spMrt001RentCal"), 
	SP_MRT003_PAY("spMrt003Pay"),
	SP_MRT003_EDT("spMrt003Edt"),
    SP_MRT003_ACT("spMrt003Act"), 
    SP_MRT006_SRCH("spMrt006Srch"), 
    SP_MRT006_SAVE("spMrt006Save"), 
    SP_MRT006_GET_DEPOSIT_STATUS_DDL("spMrt006getDepositDDL"),
    SP_MRT007_SRCH("spMrt007Srch"),
    SP_MRT007_UPDATE_DOC_SRCH("spMrt007UpdateDocSrch"),
    SP_MRT007_UPDATE_DOC_SAVE("spMrt007UpdateDocSave"),
    SP_MRT007_UPDATE_CLR_STATUS("spMrt007UpdateClrStatus"),
    SP_MRT007_UPDATE_CLR_BATCH("spMrt007UpdateCrlBatch"),
    SP_MRT007_UPD_STATUS("spMrt007UpdStatus"), 
    SP_MRT007_UPD_BATCH_NO("spMrt007UpdBatchNo"), 
    SP_MRT007_SMS("mrt007SMS"),
	SP_MRT007_MAIL("mrt007MAIL"),
    SP_MRT008_SRCH("spMrt008SrchPettyCash"),
    SP_MRT008_CHECK("spMrt008Check"),
    SP_MRT008PAY_SRCH("spMrt008SrchPettyCashPay"),
    SP_MRT008PAY_UPD_EXPORT("updateRT008PayExport"),
    SP_MRT008_BL_AMT("spMrt008BLAmt"),
    SP_MRT008_SRCH_MAP_PAY("spMrt008SrchMapPay"),
    SP_MRT009_ACT("spMrt009Act"),
    SP_MRT010_IFRS_INTERFACE("spMrt010IfrsInterface"),
    SP_MRT010_IFRS_INTERFACE_ONLINE("spMrt010IfrsInterfaceOnline"),
    SP_MRT010_IFRS_INTERFACE_ONLINE_CH("spMrt010IfrsInterfaceOnlineCH"),
    SP_MRT010_IFRS_INTERFACE_UPDATE("spMrt010IfrsInterfaceUpdate"),
    SP_MRT010_IFRS_INTERFACE_TODOLIST("spMrt010IfrsInterfaceTodolist"),
    SP_MRT010_IFRS_TODOLIST_DETAIL("spMrt010IfrsTodolistDetail"),
    SP_MSI004_SRCH_LESSOR("msi004SearchLessor"),
    SP_MSI004_SEQ_LESSOR("msi004SeqLessor"),
    SP_PCT001_SRCH("querySearchVendorSupplier"),
    SP_MSI004_SRCH_RENT_COND("msi004SrchRentCond"),
    SP_MSI004_SRCH_RENT_COND_EXT("msi004SrchRentCondExt"),
    SP_MSI004_SRCH_DPST_R("msi004SrchDepositRent"),
    SP_MPT001_SRCH ("spMpt001Srch"),
    SP_MPT001_EDT ("spMpt001Edt"),
    SP_MPT001_SRCH_HIST("spMpt001SrchHist"),
    SP_MSI004_SEQ_DEPOSIT("msi004SeqDeposit"),
    SP_MSI004_SEQ_RENT_COND("msi004SeqRentCond"),
    SP_MSI004_CALC_AGE("msi004CalcAge"),
    SP_MSI004_CHK_PT_UNDEF("msi004CheckPtUndef"),
    SP_MSI004_GEN_DPST_E_ADD("updateEAdd"),
    SP_MSI004_GEN_DPST_E_DEL("updateEDel"),
    SP_MSI004_GEN_DPST_R_ADD("updateRAdd"),
    SP_MSI004_GEN_DPST_R_DEL("updateRDel"),
    SP_MPT002_SRCH("spMpt002Srch"),
    SP_MPT002_EDT("spMpt002Edt"),
    SP_MPT002_SRCH_HIST("spMpt002SrchHist"),
    SP_MPT003_SRCH("spMpt003Srch"),
    SP_MPT006_SRCH("spMpt006Srch"),
    Q_SEARCH_POPUP_VIEW_SITE_INFO("querypopupViewSiteInFoSearch"),
    SP_MSI004_SRCH_PT_HIST("msi004SearchPropertyTaxHistory"),
    SP_MSI004_SRCH_DPST_E("msi004SrchDepositElectric"),
    SP_MSI004_SRCH_SUM_DPST_E("msi004SrchSumDepositElectric"),
    SP_MSI004_CALC_EXPIRE_DT("msi004CalcExpireDate"),
    SP_MPT004_Pay("spMpt004Pay"),
    SP_MPT004_SRCH("spMpt004Srch"),
    SP_MPT004_ACT("spMpt004Act"),
    SP_MPT004_SRCH_D("spMpt004SrchD"), 
    SP_MSI001_UPD_OUT_DT("msi001UpdOutDt"), 
    SP_MSI001_EXP("msi001UpdateExport"),
    SP_MSI001_DEL("msi001Del"), 
    SP_MSI001_UPD_REGION("msi001UpdRegion"), 
    SP_MSI001_SEQ("msi001Seq"), 
    SP_MSI001_CHK_DOC_NO("msi001ChkDocNo"), 
    SP_MSI001_SAVE("msi001Save"),
    SP_MSI004_SRCH_SUB_RENT("msi004SrchSubRent"),
    SP_MSI004_SRCH_SITE_STATUS("msi004SrchSiteStatus"),
    SP_MSI004_SEQ_SUB_RENT("msi004SeqSubRent"),
    SP_MSI004_GEN_CONTRACT_NO("msi004GenContractNo"),
    SP_MSI004_GEN_DUMMY_NO("msi004GenDummytNo"),
    SP_MSI004_SRCH_LOC_ADDR("msi004SrchLocAddress"),
    SP_MSI004_CLR_MAIN_LOC("msi004ClearMainLocFlag"),
    SP_MSI004_SRCH_EXPORT("msi004SearchExport"),
    SP_MSI004_SRCH_ROLLBACK_DUMMY("msi004SearchRollBackDummy"),
    SP_MSI004_UPD_CO_SKIP("msi004UpdateContractSkip"),
    SP_MSI004_UPD_NO_RENT("msi004UpdateNoRent"),
    SP_MSI004_UPD_NO_DEPOSIT_R("msi004UpdateNoDepositRent"),
    SP_MSI004_UPD_NO_DEPOSIT_E("msi004UpdateNoDepositElectric"),
    SP_MSI004_UPD_LATEST_FLAG("msi004UpdateLatestFlag"),
    SP_MSI004_SITEINFO_PT_SRCH("msi004SiteInfoPTSrch"),
    SP_MSI004_CHK_CANCELABLE("msi004CheckCancelable"),
    SP_MSI004_CHKEDIT_SITE("msi004CheckEditSite"),
    SP_MSI004_CHKEDIT_PT("msi004CheckEditPropertyTax"),
    SP_MSI004_CHKEDIT_E("msi004CheckEditElectric"),
    SP_MSI004_CHKEDIT_CONTRACT("msi004CheckEditContract"),
    SP_MSI004_CHKEDIT_LESSOR("msi004CheckEditLessor"),
    SP_MSI004_CHKEDIT_RENT("msi004CheckEditRent"),
    SP_MSI004_CHKEDIT_DPST_R("msi004CheckEditDepositRent"),
    SP_MSI004_CHKEDIT_DPST_E("msi004CheckEditDepositElectric"),
    SP_MSI004_CHKEDIT_IN("msi004CheckEditInsurance"),
    SP_MSI004_CHK_CONTRACT_NO("msi004CheckContractNo"),
    SP_MSI004_CHK_APPROVE("msi004CheckApprove"),
    SP_MSI004_CHK_ENA_APPROVE("msi004CheckEnableApprove"),
    SP_MSI004_CHK_ENA_STATUS("msi004CheckEnableStatus"),
    SP_MSI004_SRCH_SUM_RENT_A("msi004SrchSumRentAge"),
    SP_MSI004_CHK_EFFECTIVE_DT("msi004CheckEffectiveDate"), 
    SP_MSI004_CHK_COPY("msi004ChkCopy"), 
    SP_MSI004_DEFAULT_TOT("msi004DefaultTot"),
    SP_MSI004_SITE_INFO_SERVICE_SRCH("msi004SiteInfoServiceSrch"),
    
    SP_MSI004_SITE_INFO_INSURENCE_SRCH("msi004SiteInfoIRSrch"),

    SP_MSI004_SITE_INFO_EL_COND_SRCH("msi004SiteInfoELCondSrch"),
    SP_MSI004_SITE_INFO_EL_COND_DEL("msi004SiteInfoElCondDel"),
    SP_MSI004_SITE_INFO_EL_COND_UPD("msi004SiteInfoELCondUpd"),
    SP_MSI004_SITE_INFO_EL_COND_INS("msi004SiteInfoELCondIns"),
    SP_MSI004_SITE_INFO_RENT_SERV_SRCH("msi004SiteInfoRentServSrch"), 
    
    SP_MSI004_SITE_INFO_RENTAL_UNDO("msi004SiteInfoRentalUndo"),
    SP_MSI004_SITE_INFO_RENTAL_DEPOSIT_UNDO("msi004SiteInfoRentalDepositUndo"),
    SP_MSI004_SITE_INFO_PT_UNDO("msi004SiteInfoPTUndo"),
    SP_MSI004_SITE_INFO_IR_UNDO("msi004SiteInfoIRUndo"),
    SP_MSI004_SITE_INFO_CONTRACT_UNDO("msi004SiteInfoContractUndo"),
    
    SP_MSI002_UPD_LATEST_FLAG("msi002UpdLatestFlag"),
    SP_MCO002_SRCH("mco002SearchContractStatus"),
    SP_MCO006_SRCH("mco006SearchContractStatus"),
    SP_MCO002_UPD_STATUS_LIST("mco002UpdateContractStatus"),
    SP_MCO005_UPD_STATUS_LIST("mco005UpdateContractStatus"),
    SP_MCO002_DEFAULT_DUTY("mco002DefaultDuty"),
    SP_MCO004_DEFAULT_DUTY("mco004DefaultDuty"), 
    SP_MCO002_SRCH_NO_FOUND("mco002SearchNoFoundStatus"),
    SP_MCO002_CHK_NO_FILE("mco002CheckNoFile"),
    SP_MCO001_SRCH("mco001Srch"),
    SP_MCO005_SRCH("mco005Srch"),
    SP_MCO001_SRCH_LOV_STATUS("mco001SrchLovStatus"),
    SP_MCO004_SRCH_LOV_STATUS("mco004SrchLovStatus"),
    SP_MCO001_CHK_ADDABLE("mco001CheckAddAble"),
    SP_MCO001_SEQ_STATUS("mco001SeqStatus"),
    SP_MCO001_SRCH_STATUS("mco001SrchStatus"),
    SP_MCO004_SRCH_STATUS("mco004SrchStatus"),
    SP_MAC001_SRCH("spMac001Srch"),
    SP_MAC001_SRCH_D("spMac001SrchD"),
    SP_MCO001_SRCH_DDL_STATUS("mco001ContractStatus"),
    SP_MCO005_SRCH_DDL_STATUS("mco005ContractStatus"),
	SEM_SP_MCO003_SRCH("spMco003Search"),
    SP_MCO001_UPD_STATUS("mco001UpdateStatus"),
    SP_MCO001_SRCH_FILE("mco001SrchFile"),
    SP_MCO001_SRCH_DDL_DOC("mco001SrchDDLDoc"),
    SP_MCO001_SRCH_DDL_DOC_NEW("mco001SrchDDLDocNew"),
    SP_MCO001_SEQ_FILE("mco001SeqFile"),
    SP_MCO001_UPD_CHECK_DOC("mco001UpdateCheckDoc"),
    SP_MCO001_UPD_CHECK_DOC_L("mco001UpdateCheckDocL"),
    SP_MCO001_UPD_DOC_LEGAL("mco001UpdateDocLegal"),
    SP_MRT_GET_RUNNING_NO("mrtGetRunningNo"),
    SP_MRT003_CAL("mrt003Cal"),
    SP_MCP001_GEN_DOC_NO("spMcp001GenDocNo"),
    SP_MCO003_SECH_BORROW("spMco003SearchBorrow"),
    SP_MCO003_SECH_PSI002("spMco003SearchPSI002"),
    SP_MCO003_SECH_CONTRACT("spMco003SearchContract"),
    SP_MCO003_GEN_DOC_NO("spMco003GenDocNo"), 
    SP_MCO003_DEL("spMco003Del"), 
    SP_MCO003_DEL_BORROW("spMco003DelBorrow"),
    SP_MCO003_CHK_BORROW("spMco003ChkBorrow"), 
    SP_MCO003_CHK_RETURN("spMco003ChkReturn"),
    SP_MCO003_SAVE_RETURN("spMco003SaveReturn"),
    SP_MCO003_SAVE_BORROW("spMco003SaveBorrow"),
    SP_MCO003_APPROVE_BORROW("spMco003ApproveBorrow"),
    SP_MCO003_SEND_APPROVE_BORROW("spMco003SendApproveBorrow"),
    
    //added by NEW 2018/11/08
    SP_MCO007_MC_SRCH("mco007MasterContractSrch"),
    SP_MCO007_MC_DETAIL_SRCH("mco007MasterContractDetailSrch"),
    SP_MCO007_MC_DETAIL_INS("mco007MasterContractIns"),
    SP_MCO007_MC_DETAIL_UPD("mco007MasterContractUpd"),
    SP_MCO007_MC_DETAIL_DEL("mco007MasterContractDel"),
    SP_MCO007_MC_PARAM_NAME("mco007ContractParamName"),
    Q_MCO007_REPORT_TITLE_PARAM("mco007ReportTitleSrch"),
    Q_MCO007_REPORT_DETAIL_PARAM("mco007ReportDetailSrch"),
    Q_MCO007_REPORT_RENTAL_PARAM("mco007ReportRentalSrch"),
    Q_MCO007_REPORT_EL_PARAM("mco007ReportELSrch"),
    
	SP_MPT004_CHK("spMpt004Chk"),
	SP_MPT004_EDT("spMpt004Edt"),
	SP_MSI002_UPD_OUT_DT("msi002UpdOutDt"),
	SP_MAC001_ACT("spMac001Act"),
	SP_MAC001_PAY("spMac001Pay"),
	SP_SEARCH_APPROVE_BOOK_BANK("querySearchApproveBookBank"),
	SP_APPROVE_BOOK_BANK_ACT("queryApproveBookBankAct"),
	SP_CHECK_APPROVE_BOOK_BANK("mct003CheckApproveBookBank"),
	SP_APPROVE_SITE_INFO("approveSiteInfo"),
	SP_MPT004_CAL("spMpt004Cal"),
	SP_MPT004_SRCH_C("spMpt004SrchC"),
	SP_MCP001_SAVE_PAY("querySaveConstructionPermission"),
	SP_MAC001_SAP("spMac001Sap"),
	SP_MAC001_SRCH_R("spMac001SrchR"),
	SP_MAC003_SRCH("spMac003Srch"),
	SP_MAC004_SRCH("spMac004Srch"),
	SP_MAC004_ACT("spMac004Act"),
	SP_MAC003_FILE("spMac003File"),
	SP_MCT008_SRCH("queryCT008SrchSP"),
	SP_MSI002_Check_ADDED("msi002CheckAdded"),
	SP_PSI003_SRCH_SITE_INFO("spPsi003SrchSiteInfo"),
    SP_MCP001_Check_Payable("spMcp001Chkable"),
    SP_MCP001_CHECK_SAVE_PAY("spMcp001ChkSavePay"),
    SP_MCP001_SAVE_PAY_SP("spMcp001SavePay"),
    SP_MCP001_CANCLE_PAY("spMcp001CanclePay"),
    
    SP_MCP001_TRANSFER_DUMMY("mcp001TransferDummy"),
	SP_MCP001_ROLLBACK_DUMMY("mcp001RollBackDummy"),
	SP_MCP001_SRCH_ROLLBACK_DUMMY("mcp001SearchRollBackDummy"),
	
    SP_CHECK_VENDOR("spCheckVendor"),
    SP_MAC001_RE_FILE("spMac001ReFile"), 
    SP_PSI005_SRCH("queryPopupContractSearchPSI005"), 
    SP_PCT002_SRCH_BG("queryPopupContractSearchPCT002"),
	SP_MIR007_ACT("mir007Act"),
	SP_MIR007_SCH_D("mir007SchD"),
	SP_MIR007_SCH_R("mir007SchR"),
	SP_MIR008_SCH("mir008Sch"),
	SP_MIR008_SCH_DRAFT("mir008SchDraft"),
	SP_MIR008_UPD("mir008SchDraftUPD"),
	SP_MIR009_SCH("mir009Sch"),
	SP_MIR009_POLICY("mir009Policy"),
	SP_MIR010_SCH("mir010Sch"),
	SP_MIR010_ACT("mir010Act"),
	SP_MIR_GET_RUNNING_NO("mirGetRunningNo"),
	SP_MIR010_SCH_D("mir010SchD"),
	SP_MIR010_PAY("mir010Pay"),
	SP_MIR013_SCH("mir013Sch"),
	SP_MIR013_SCH_D("mir013SchD"),
	SP_MIR013_EDT("mir013Edt"),
	SP_MIR014_SCH("mir014Sch"),
	SP_MIR002_ACT("mir002Act"),
	SP_MIR008_SAVE("mir008Save"),
	SP_MIR007_ADD("mir007Add"),
	SP_SEARCH_VENDOR_MASTER("searchVendorMaster"),
	SP_MIR007_MAP_P("mir007MapP"),
	SP_MIR013_LOAD("mir013Load"),
	SEM_SP_QSI004_SRCH("querySiteInfoSearch"),
	SEM_SP_MSI001_DELETE_SITE_INFO("msi001DeleteSiteInfo"),
	SP_MCT001_SRCH_CON("mct001SrchCon"),
	SP_MCT001_DEL("mct001Del"),
	SP_MCO004_SRCH("mco004Srch"),
	SP_MCO004_SRCH_SUMMARY("mco004SrchSummary"),
	SP_MCO004_INSERT("mco004Insert"),
	SP_MCO004_UPDATE("mco004Update"),
	SP_MRT001_SRCH_RENT_PAY("mrt001SrchRentPay"),
	SP_MRT001_BALANCE_CAL("spMrt001BalanceCal"),
	SP_MRT003_POP("mrt003Pop"),
	SP_MRT003_POP_D("mrt003PopD"),
	SP_MRT003_EXP("mrt003Exp"),
	SP_MAC001_CLEAR_CHQ("mac001ClearChq"),
	SP_MCO004_ACT("mco004Act"),
	SP_APPROVE_EL("approveEL"),
	SP_MSI004_CHK_ALERT("msi004ChkAlert"),
	SP_GET_DETAIL_VENDOR_PAYEE("detailVendorPayee"),
	SP_SHOW_PERCENT_GROWTH("showPercentGrowth"),
	SP_EL_UPLOAD_TEXT_SUCCESS("uploadSuccessText"),
	SP_EL_OWNER_GROUP("getOwnerGroup"),
	SP_MSI004_SITE("queryCloselySite"),
	SP_MSI004_HIST_RENT("queryRentHistory"),
	SP_EL_METER_INFO_FEE("getMeterId"),
	SP_MEL005_SUCCESS_VALIDATE("successValidate"),
	SEM_SP_MEL005_FAIL_VALIDATE("failValidate"),
	SP_MEL006_PRIVATE_VALIDATE("elPrivateValidate"),
	SP_MEL009_ACCURE_PROCESS("clearAccureProcess"),
	PG_EL_METER_TYPE_INFO("getMeterRate"),
	PG_METER_TYPE_VALIDATE("validateAddMeterInfo"),
	SP_MCO003_CHK_CONTRACT("spMco003ChkContract"),
	SP_MCO003_INSERT("spMco003InsertBorrow"),
	SP_MCO003_INSERT_NEW("spMco003InsertBorrowNew"),
	SP_MPT003_ACT("spMpt003Act"),
	SP_MPT003_EXP("spMpt003Exp"),
	SP_MRT003_EXPLET("spMrt003Exp"),
	SP_MEL008_EXPLET("spMel008Exp"),
	SP_MEL008_EXP("spMel008ExpExcel"),
	SP_MEL008_EXP_REMARK("spMel008ExpRemarkExcel"),
	SP_MEL008_EXP_CHQ("spMel008ExpChq"),
	SP_MCT001_CONF("spMct001CONF"),
	SP_MSI001_GEN_DOC_NO("spMsi001GenDocNo"),
	SP_MCO004_UPD_DUTY("mco004UpdDuty"),
	SP_MRT003_SMS("mrt003SMS"),
	SP_MRT003_MAIL("mrt003MAIL"),
	SP_MRT003_EXP_BATCH("mrt003ExpBatch"),
	SP_EL_GET_VENDOR_ID_FEE("elGetVendorId"),
	SP_MSI004_GEN_DUMMY("msi004GenDummy"),
	SP_MEL011_GEN_DUMMY("mel011GenDummy"),
	SP_MEL011_SRCH_DUMMY("mel011SrchDummy"),
	SP_MEL011_SRCH_DUMMY_DTL("mel011SrchDummyDtl"),
	SP_MEL011_SAVE_DUMMY("mel011SaveDummy"),
	SP_MEL011_TRANSFER_DUMMY("mel011TransferDummy"),
	SP_MEL011_ROLLBACK_DUMMY("mel011RollBackDummy"),
	SP_MEL011_DEL_DUMMY("mel011DeleteDummy"),
	SP_MEL011_CHK_LOC("mel011ChkLoc"),
	SP_EL_GET_CONTRACT("elGetContract"),
	SP_MEL005_FAIL_SRCH("searchFail"),
	SP_MEL005_FAIL_NEW_SRCH("searchFailNew"),
	SP_MEL005_GET_DATA_DETAIL("GetDataDetailEL"),
	SP_MEL005_FAIL_SRCH_LIST("searchFailList"),
	SP_MEL005_EXPORT_METER("exportMeter"),
	SP_MEL005_EXPORT_TEXT("exportText"),
	SP_MEL005_REPORT_USAGE("exportReportUsage"),
	SP_MEL005_SRCH_PAYMENT_HIST("srchPaymentHist"),
	SP_MEL008_CHK_PAY("mel008ChkPay"),
	SP_MRT003_POP_PAY("mrt003PopPay"),
	SP_UPD_MRT003_POP_PAY("updateMrt003PopPay"),
	SP_UPD_MRT001_UPD_PERIOD("mrt001UpdPeriod"),
	SP_MRT003_UPD_REMARK("mrt003UpdRemark"),
	SP_MSI004_CHANGE("historyDetail"),
	SP_EL001_SEARCH_DTL("getElUseDetail"),
	SP_EL001_INSERT_DETAIL("insertElUseDetail"),
	SP_MRT003_GEN_SPC("saveRentalCreate"),
	SP_MRT003_CAL_AMOUNT("rentalCalAmt"),
	SP_MCT001_CHK_HQ("mct001ChkHq"),
	SP_MEL008_ACT("mel008Act"),
	SP_MEL008_SEARCH("queryPaymentSP"),
	SP_MEL008_SEARCH_DEATIL("queryPaymentDetailSP"),
	SP_MEL009_ACCURE_SRCH("getMeterInstallment"),
	SP_MEL009_MAIL("mel009MAIL"),
	SP_MEL009_SMS("mel009SMS"),
	SP_UPD_MEL014_UPD_PERIOD("mel014UpdPeriod"),
	
	//fixed by.. YUT 2014/09/18
	SP_MRT003_UPD_STATUS("mrt003UpdateStatus"),

	//fixed by.. YUT 2014/09/18
	SP_MCT009_BANKMASTER_SEARCH("mct009BankMasterSearch"),
	SP_MCT009_BANKMASTER_SAVE("mct009BankMasterSave"),
	SP_MCT009_BANKMASTER_SEARCH_DDL_BANK("mct009BankMasterSearchDdlBank"),


	//added by.. YUT 2014/11/10
	SP_MSA001_GET_TODO_MENU("msa01GetTodoMenu"),	
	SP_MSA001_SRCH_NEW_SITE("msa001SearchNewSite"),
	SP_MSA001_SRCH_TEAM("msa001SearchTeam"),
	SP_MSA001_ASSIGN_SUMMARY("msa001AssignSummary"),
	SP_MSA001_SRCH_WAITING("msa001SearchWaiting"),
	SP_MSA001_SRCH_LEADER("msa001SearchLeader"),
	
	SP_MSA001_SERCH_RENEW_SITE("msa001SearchReNewSite"),
	
	SP_MSA001_SRCH_MANAGER_HD("msa001SearchManagerHD"),
	SP_MSA001_SRCH_MANAGER_DT("msa001SearchManagerDT"),
	
	SP_MSA001_SRCH_LEGAL("msa001SearchLegal"),
	
	SP_MSA001_SRCH_EXCEPT("msa001SearchExcept"),
	
	SP_MSA001_SRCH("msa001Srch"),
	
	SP_MSA001_ASSIGN_UPD("msa001AssignUpd"),
	SP_MSA001_MOVE2SITE_PAUSE("msa001Move2SitePause"),
	
	SP_MSA001_CLR_BATCH_NO("msa001ClearBatchNo"),
	SP_MSA001_OFFICER_APPROVE("msa001OfficerApprove"), 
	SP_MSA001_LEADER_APPROVE("msa001LeaderApprove"),
	SP_MSA001_MANAGER_APPROVE("msa001ManagerApprove"),
	SP_MSA001_AVP_APPROVE("msa001AvpApprove"),
	
	SP_MSA001_UPD_CO_STATUS("msa001UpdCoStatus"),
	
	SP_MSA001_GET_LEGAL_DOC("msa001getLegalDoc"),
	SP_MSA001_SRCH_CO_STATUS("msa001SrchCoStatus"),
	
	SP_MSA002_SRCH_SITEAPP_ALL_DETAIL("msa002SiteAppAllDetail"), 
	SP_MSA002_SITE_APP_SITE_SRCH("msa002SiteAppSiteSrch"),
	SP_MSA002_POPUP_ADD_SITE_SRCH("msa002PopupAddSiteSrch"),
	
	SP_MSA002_SITE_APP_UPD("msa002SiteAppUpdate"),
	SP_MSA002_UPD_TS_TERMINATE("msa002UpdTsTerminate"),
	
	SP_MSA002_SITE_APP_SITE_UPD("msa002SiteAppSiteUpd"),
	
	SP_MSA002_SITE_APP_DOC_SAVE("msa002SiteAppDocSave"),
	
	SP_MSA002_GEN_DOC_NO("msa002GenDocNo"),
	SP_MSA002_MAIL_ADDRESS_SEARCH_ALL("msa002MailAddrSrchAll"),
	SP_MSA002_MAIL_ADDRESS_IUD("msa002MailAddrIUD"),
	SP_MSA002_MAIL_EXPORT("msa002MailAddrExport"),
	SP_MSA002_DOC_SRCH("msa002DocSrch"),

	SP_MSA002_SITE_HISTORY_TAB("msa002SiteHistoryTab"),
	SP_MSA002_MAIN_SITE_HISTORY_TAB("msa002MainSiteHistoryTab"),
	SP_MSA002_SUB_SITE_HISTORY_TAB("msa002SubSiteHistoryTab"),
	SP_MSA002_POPUP_CONTRACT_HISTORY_TAB("msa002PopupContractHistoryTab"),
	SP_MSA002_POPUP_RENTAL_HISTORY_TAB("msa002PopupRentalHistoryTab"),
	SP_MSA002_POPUP_ELECTRICAL_HISTORY_TAB("msa002PopupElectricalHistoryTab"),
	SP_MSA002_POPUP_ELECTRICAL_DEPOSIT_HISTORY_TAB("msa002PopupElectricalDepositHistoryTab"),
	SP_MSA002_POPUP_PROPERTY_TAX_HISTORY_TAB("msa002PopupPropertyTaxHistoryTab"),
	SP_MSA002_POPUP_INSURANCE_HISTORY_TAB("msa002PopupInsuranceHistoryTab"),
	SP_MSA002_RENTAL_HISTORY_TAB("msa002RentalHistoryTab"),
	SP_MSA002_SITE_APP_HIST_SRACH("msa002SiteAppRegHistSrch"),
	SP_MSA002_SITE_APP_SERVICE("msa002SiteAppService"),
	
	SP_MSA002_SITE_APP_LOC_UPDATE("msa002SiteAppLocUpdate"),
	SP_MSA002_SITE_APP_MASTER_SRCH("msa002SiteAppMasterSrch"),
	SP_MSA002_SITE_APP_RENT_CONT_SRCH("msa002SiteAppRentContSrch"),
	SP_MSA002_SITE_APP_RENT_COND_INS("msa002SiteAppRentCondIns"),
	SP_MSA002_SITE_APP_RENT_COND_UPD("msa002SiteAppRentCondUpd"),
	SP_MSA002_SITE_APP_RENT_COND_DEL("msa002SiteAppRentCondDel"),
	SP_MSA002_SITE_APP_RENT_SRCH("msa002SiteAppRentSrch"),
	SP_MSA002_SITE_APP_DEPOSIT_SRCH("msa002SiteAppDepositSrch"),
	SP_MSA002_SITE_APP_DEPOSIT_DEL("msa002SiteAppDepositDel"),
	SP_MSA002_SITE_APP_DEPOSIT_UPD("msa002SiteAppDepositUpd"),
	SP_MSA002_SITE_APP_DEPOSIT_INS("msa002SiteAppDepositIns"),
	SP_MSA002_SITE_APP_EL_COND_SRCH("msa002SiteAppELCondSrch"),
	SP_MSA002_SITE_APP_EL_COND_DEL("msa002SiteAppElCondDel"),
	SP_MSA002_SITE_APP_EL_COND_UPD("msa002SiteAppELCondUpd"),
	SP_MSA002_SITE_APP_EL_COND_INS("msa002SiteAppELCondIns"),
	SP_MSA002_SITE_APP_RENT_UNDO("msa002SiteAppRentUndo"),
	SP_MSA002_SITE_APP_RENT_DEPOSIT_UNDO("msa002SiteAppRentalDepositUndo"),
	SP_MSA002_SITE_APP_CONTRACT_UNDO("msa002SiteAppContractUndo"),
	SP_MSA002_SITE_APP_PT_UNDO("msa002SiteAppPTUndo"),
	SP_MSA002_SITE_APP_IR_UNDO("msa002SiteAppIRUndo"),
	SP_MSA002_SITE_APP_EL_UNDO("msa002SiteAppElUndo"),
	SP_MSA002_SITE_APP_EL_DEPOSIT_UNDO("msa002SiteAppElDepositUndo"),
	P_MSA002_SITE_APP_DOC_UNDO("msa002SiteAppDocUndo"),
	
	SP_MSA003_ASSIGN_UPD("msa003AssignUpd"),
	SP_MSA003_EXP_BATCH("msa003ExpBatch"),
	SP_MSA003_EXP("msa003Exp"),
	SP_MSA002_EXP("msa002Exp"),
	SP_MSA003_CLEAR_BATCH("msa003ClearBatch"),
	SP_MSA003_OFFICER_APPROVE("msa003OfficerApprove"),
	SP_MSA003_DELETE_SITEACQ("msa003DeleteSiteAcq"),
	SP_MSA003_POPUP_NEAREST_SITE("msa00PopupNearestSite"),
	SP_MSA003_DO_POPUPNEW("msa003DoPopupNEW"),
	SP_MSA002_CAL_AMT("msa002CalAmt"),
	SP_MSA002_CAL_RENT_AMT("msa002CalRentAmt"),
	SP_MSA002_CAL_SERVICE_AMT("msa002CalServiceAmt"),
	SP_MSA002_SITE_APP_RENT_SERV_SRCH("msa002SiteAppRentServSrch"),
	SP_MSA002_SITE_APP_PT_SRCH("msa002SiteAppPTSrch"),
	SP_MSA002_SITE_APP_PT_UPD("msa002SiteAppPtUpd"),
	SP_MSA002_SITE_APP_PT_HIST_SRCH("msa002SiteAppPTHistSrch"),
	SP_MSA002_SITE_APP_IR_INS("msa001SiteAppIRIns"),
	SP_MSA002_SITE_APP_IR_UPD("msa001SiteAppIRUpd"),
	SP_MSA002_SITE_APP_IR_DEL("msa001SiteAppIRDel"),
	SP_MSA002_SITE_APP_IR_SRCH("msa002SiteAppIRSrch"),
	
	
	//added by.. YUT 2015/01/22
	SP_MSI001_GET_TODO_MENU("msi001GetTodoMenu"),
	SP_MSI001_GET_TODO_MENU_BY_CRI("getMenuTodoByCriterria"),
	SP_GET_TODO_MENU("getMenuTodoMenu"),
	SP_MLG001_SEARCH("mlg001Search"),
	
	SP_MSA002_POPUP_CONTRACT_EL_USE("msa002PopupContractElUse"),
	SP_MSA002_CHECK_CONTRACT_EL_USE("msa002checkContractElUse"),
	//
	
	SP_MSA002_CHECK_DUPLICATE_DOC_NO("msa002ChkDupDocNo"),
	SP_MSA002_CHECK_CONTRACT_NO("msa002ChkContractNo"),
	
	SP_MSA002_REQ_HIST_SRCH("msa002ReqHistSrch"),
	SP_MSA002_DOC_REMAIN_SRCH("msa002docRemainSrch"),
	SP_MSA002_SITE_REQ_HIST_INS("msa002SiteReqHistIns"),
	
	//added by.. YUT 2015/03/19
	SP_MSA004_EXECUTIVE_TO_DO_LIST("msa004ExcutiveTodoList"),
	SP_MSA004_EXECUTIVE_APPROVE("msa004ExcutiveApprove"),
	SP_MSA004_EXECUTIVE_REJECT("msa004ExcutiveReject"),
	
	//added by NEW 2018/12/25
	SP_MSA005_SEARCH_CONTRACT("msa005SrchContract"),
	
	//added by NEW 19/04/2015
	SP_ECO001_EXP_CONTRACT_DOC("eco001ExpContractDoc"),
	
	//added by NEW 06/10/2015
	SP_MCT010_SRCH("queryMct010Srch"),
	SP_MCT010_APPROVE_PAYEE_BOOKBANK("mct010ApprovePayeeBookbank"),
	
	//added by NEW 06/10/2015
	SP_MCT011_SRCH("queryMct011Srch"),
	
	//added by NEW 12/10/2015
	SP_MCT001_VM_ACT("mct001SendVendorToSAP"),
	SP_MCT001_VB_ACT("mct001SendVendorBookbank"),
	SP_MCT001_PM_ACT("mct001SendPayee"),
	SP_MCT001_PB_ACT("mct001SendPayeeBookbank"),
	SP_MCT001_CLEAR_BATCH("mct001ClearBatch"),
	SP_GET_CITY("queryCity"),
	SP_GET_AMPHUR("queryAmphur"),
	SP_GET_DISTRICT("queryDistrict"),
	
	SP_GET_MAP_VENDOR("queryGetMapVendor"),
	SP_GET_MCT001_HIST("queryGetMct001History"),
	SP_GET_VENDOR_HIST("queryGetVendorHistory"),
	SP_GET_BOOKBANK_HIST("queryGetBookbankHistory"),
	
	//added by NEW 20160407 sent email when reject
	SP_MSA001_MAIL("msa001MAIL"),
	SP_MSA001_GET_MANAGER("msa001GetManagerName"),
	
	
	//added by OUM 04/04/2016
	SP_MEL002_SEARCH_FILE("mel002SearchUploadFile"),
	SEM_SP_MEL002_EL_PERM_IMP("mel002AddElPermissionFile"),
	SEM_SP_MEL002_EL_PERM_IMP_LOG("mel002AddFileName"),
	SEM_SP_MEL002_EL_PERM_LIST("mel002SearchElPermissionWarrantCaseSuccess"),
	SEM_SP_MEL002_EL_PERM_LIST_DTL("mel002SearchForEdit"),
	SEM_SP_MEL002_EL_PERM_DTL_UPD("mel002UpdateElPermissionWarrant"),
	SEM_SP_MEL002_EL_PERM_LOG_LIST("mel002SearchDetailUploadFile"),
	SEM_SP_MEL002_EL_PERM_DEL("mel002DeleteUploadFile"),
	SEM_SP_MEL002_EL_PERM_DTL_DEL("mel002DeleteByRowUploadFile"),
	
	
	SEM_SP_MEL013_PROXY_SRCH("mel013SearchUploadFile"),
	SEM_SP_MEL013_PROXY_IMP("mel013AddElPermissionFile"),
	SEM_SP_MEL013_PROXY_IMP_LOG("mel013AddFileName"),
	SEM_SP_MEL013_PROXY_LIST("mel013SearchProxyElPermissionWarrantCaseSuccess"),
	SEM_SP_MEL013_PROXY_LOG_LIST("mel013SearchDetailUploadFile"),
	SEM_SP_MEL013_PROXY_LIST_DTL("mel013SearchForEdit"),
	SEM_SP_MEL013_PROXY_DTL_UPD("mel013UpdateElPermissionWarrant"),
	SEM_SP_MEL013_PROXY_DEL("mel013DeleteUploadFile"),
	SEM_SP_MEL013_PROXY_SRCH_F("mel013SearchUploadFileFirstPage"),
	SEM_SP_MEL013_PROXY_DTL_DEL("mel013DeleteByRowUploadFile"),
	
	
	SEM_SP_MCP002_PROXY_SRCH("mcp002SearchUploadFile"),
	SEM_SP_MCP002_PROXY_IMP("mcp002AddElPermissionFile"),
	SEM_SP_MCP002_PROXY_IMP_LOG("mcp002AddFileName"),
	SEM_SP_MCP002_PROXY_LIST("mcp002SearchProxyPermissionWarrantCaseSuccess"),
	SEM_SP_MCP002_PROXY_LOG_LIST("mcp002SearchDetailUploadFile"),
	SEM_SP_MCP002_PROXY_LIST_DTL("mcp002SearchForEdit"),
	SEM_SP_MCP002_PROXY_DTL_UPD("mcp002UpdateElPermissionWarrant"),
	SEM_SP_MCP002_PROXY_DEL("mcp002DeleteUploadFile"),
	SEM_SP_MCP002_PROXY_SRCH_F("mcp002SearchUploadFileFirstPage"),
	SEM_SP_MEL013_PROXY_PRINT("mel013PrintDoc"),
	SEM_SP_MCP002_PROXY_DTL_DEL("mcp002DeleteByRowUploadFile"),
	
	SEM_SP_MEL003_METER_SRCH("mel003SearchUploadFile"),
	SEM_SP_MEL003_METER_IMP("mel003AddUploadMeterPermissionFile"),
	SEM_SP_MEL003_METER_IMP_LOG("mel003AddFileName"),
	SEM_SP_MEL003_METER_LIST("mel003SearchUploadMeterWarrantCaseSuccess"),
	SEM_SP_MEL003_METER_LOG_LIST("mel003SearchDetailUploadFile"),
	
	SEM_SP_MEL003_METER_LIST_DTL("mel003SearchForEdit"),
	SEM_SP_MEL003_METER_DTL_UPD("mel003UpdateElPermissionWarrant"),
	SEM_SP_MEL003_METER_DEL("mel003DeleteUploadFile"),
	SEM_SP_MEL003_EL_METER_DEL("mel003DeleteUploadFile"),
	SEM_SP_MEL003_METER_SRCH_F("mel003SearchUploadFileFirstPage"),
	SEM_SP_MEL003_METER_DTL_DEL("mel003DeleteByRowUploadFile"),
	SEM_SP_MEL013_GEN_DUMMY("mel013GenDummy"),
	SP_MSA001_SRCH_RENT_COND("msa001SrchRentCond"),
	
	// -- added 2017/04/05
	SEM_SAP_SP_ADD_BOOKBANK_IN("semsapAddBookBank"),
	SEM_SAP_SP_VENDOR_SEARCH("semsapVendorSearch"),
	SEM_SAP_REGION_CHECK_LIST("semsapRegionCheckList"),
	
	SEM_SAP_CONTRACT_DETAIL("semsapContractDetail"),
	SEM_SAP_VENDOR_DETAIL("semsapVendorDetail"),
	SEM_SAP_VENDOR_DETAIL_SAP("semsapVendorDetailSAP"),
	SEM_SAP_SUMMARY_VENDOR_HIST("semsapSummaryVendorHist"),
	SEM_SAP_VENDOR_CONTRACT_LIST("semsapVendorContractList"),
	SEM_SAP_VENDOR_BOOKBANK_LIST("semsapVendorBookbankList"),
	SEM_SAP_VENDOR_PAYEE_LIST("semsapVendorPayeeList"),
	SEM_SAP_CONTRACT_LIST("semsapContractList"),
	
	SEM_SAP_BOOKBANK_DETAIL("semsapBookbankDetail"),
	SEM_SAP_BOOKBANK_DETAIL_SAP("semsapBookbankDetailSAP"),
	SEM_SAP_PAYEE_DETAIL("semsapPayeeDetail"),
	SEM_SAP_BOOKBANK_PAYEE_DETAIL("semsapBookbankPayeeDetail"),
	
	SEM_SAP_ADDRESS("semsapAddress"),
	
	SEM_SAP_EXPORT_BATCH("semsapExportBatch"),
	SEM_SAP_CHANGE_STATUS("semsapChangeStatus"),
	SEM_SAP_GET_VENDOR("semsapGetVendor"),
	SEM_SAP_DELETE_MASTER("semsapDeleteMaster"),
	SEM_SAP_VENDOR_DELETE("semsapVendorDelete"),
	SEM_SAP_DELETE_VENDOR_CONTRACT("semsapDeleteVendorContract"),
	SEM_SAP_CLEAR_BATCH("semSapClearBatch"),
	SEM_SAP_CANCEL("semSapCancel"),
	
	SEM_SAP_VENDOR_SAVE_DRAFT("semsapVendorSaveDraft"),
	SEM_SAP_BOOKBANK_SAVE_DRAFT("semsapBookbankSaveDraft"),
	SEM_SAP_PAYEE_SAVE_DRAFT("semsapPayeeSaveDraft"),
	SEM_SAP_BB_PAYEE_SAVE_DRAFT("semsapBBPayeeSaveDraft"),
	
	SEM_SAP_VENDOR_SAVE_ADDRESS("semsapVendorSaveAddress"),// -- added 2017/04/05
	
	SEM_SAP_CHECK_VENDOR_POPUP("semsapCheckVendorPopup"),
	SEM_SAP_LIST_VENDOR_POPUP("semsapListVendorPopup"),
	
	SEM_SAP_CHECK_BOOKBANK_POPUP("semSapCheckBookbankPopup"),
	SEM_SAP_LIST_BOOKBANK_POPUP("semSapListBookbankPopup"),
	
	SEM_SAP_VENDOR_ADDRESS("semsapVendorAddress"),
	

	SEM_SAP_MANAGER_REJECT("semsapReject"),
	SEM_SAP_SP_VENDOR_SEARCH_FLOW("semsapVendorSearchFlow"),
	SEM_SAP_GET_TODO_MENU("mmm002SapGetTodoMenu"),
	SEM_SAP_SP_TODO_VENDOR_SEARCH("semsapTodoVendorSearch"),
	SEM_SAP_SP_TODO_STAFF_SEARCH("semsapTodoStaffSearch"),
	SP_SEARCH_SAP_APPROVE_BOOK_BANK("querySearchSapApproveBookBank"),
	SP_SAP_APPROVE_BOOK_BANK_ACT("querySapApproveBookBankAct"),
	SP_CHECK_SAP_APPROVE_BOOK_BANK("mct003CheckSapApproveBookBank"),
	SP_SEM_SAP_VENDOR_APPROVE("semsapVendorApprove"),
	
	SEM_SAP_SEARCH_WHT("semsapSearchWht"),
	
	SEM_SAP_GET_MAP_VENDOR("semsapGetMapVendor"),
	SEM_SAP_POPUP_CONTRACT_SEARCH("semsapPopupContractSearch"),
	
	SEM_SAP_MAP_VENDOR_INFO("semsapMapVendorInfo"),
	SEM_SAP_GET_CONTRACT_HIST("semsapGetContractHistory"),
	SEM_SAP_GET_CONTRACT_PAY_HIST("semsapGetContractPayHistory"),
	SEM_SAP_GET_MASTER_HIST("semsapGetMasterHistory"),
	
	SEM_SAP_ASSGN_CNTRCT_TO_VNDR("semsapAssignCntrctToVndr"),
	SEM_SAP_EXP_WTH_CNTRT_OF_VNDR("semsapSaveExpenseInfo"),
	
	SEM_SAP_SEARCH_BANK_MASTER("semsapSearchBankMaster"),
	SEM_SAP_CHECK_PAYEE_POPUP("semsapCheckPayeePopup"),
	SEM_SAP_BOOKBANK_PAYEE_LIST("semsapBookbankPayeeList"),
	
	SEM_SAP_VALIDATE_VENDOR("semsapValidateVendor"),
	SEM_SAP_VALIDATE_APPROVE("semsapValidateApprove"),
	SEM_SAP_VALIDATE_BOOKBANK("semsapValidateBookbank"),
	SEM_SAP_VALIDATE_PAYEE("semsapValidatePayee"),
	SEM_SAP_VALIDATE_BB_PAYEE("semsapValidateBBPayee"),
	SEM_SAP_VENDOR_RENTAL_PAYMENT_HISTORY("semsapVendorRentalPayHist"),
	SEM_SAP_VENDOR_EL_PAYMENT_HISTORY("semsapVendorELPayHist"),
	SEM_SAP_VENDOR_CT_PAYMENT_HISTORY("semsapVendorCTPayHist"),
	SEM_SAP_VENDOR_PT_PAYMENT_HISTORY("semsapVendorPTPayHist"),
	SEM_SAP_VENDOR_IR_PAYMENT_HISTORY("semsapVendorIRPayHist"),
	SEM_SAP_CT_CONFIRM("semSapConfirm"),
	SEM_SAP_VALIDATE_PAGE("semsapVendorValidatePage"),
	SEM_SAP_VENDOR_GET_PAYMENT("semsapVendorGetPayment"),
	SEM_SAP_CONFIRM_INFO("semsapConfirmInfo"),
	SEM_SAP_VALIDATE_BACK_VD("semsapVendorValidateBack"),
	SEM_SAP_VALIDATE_BACK_AD("semsapAddressValidateBack"),
	SEM_SAP_VALIDATE_BACK_EP("semsapExpenseValidateBack"),
	SEM_SAP_VALIDATE_BACK_VB("semsapBookbankValidateBack"),
	SEM_SAP_VALIDATE_BACK_PY("semsapPayeeValidateBack"),
	SEM_SAP_VALIDATE_BACK_PB("semsapBBPayeeValidateBack"),
	SEM_SAP_BOOKBANK_CHECK_GSB("semsapVendorBookbankCheckBBGsb"),
	SEM_MEL001_SCH_VER_MASTER("mel001SchVerMasterSP"),
	SEM_MEL001_SCH_VER_COND("srchVerCond"),
	SEM_MEL001_SCH_VER_DTL("srchVerDtl"),
	SEM_MEL001_SCH_VER_HIST("srchVerHist"),
	SEM_MEL001_EL_CAL("mel001Cal"),
	SEM_MEL001_SEARCH_VENDOR("mel001SrchVendor"),
	SEM_MEL001_SEARCH_PAYEE("mel001SrchPayee"),
	SEM_MEL001_BOOKBANK("mel001BookBank"),
	SEM_MEL001_INSERT_DETAIL("mel001InsertDetail"),
	SEM_MEL001_SRCH_DPST_COND("el001SrchDpstCond"),
	SEM_MEL001_SEARCH_DPST_DTL("el001SrchDpstDtl"),
	SEM_MEL001_INSERT_DPST("el001InsertDpst"),
	SEM_MEL001_LIST_METER("mel001ListMeter"),
	SEM_MEL014_PRIVATE_VERIFY("mel014PrivateVerify"),
	SEM_SP_MEL001_LIST_WARRANT("spMel001ListWarrant"),
	SEM_SI_SITE_INFO_SERVICES("mrt001ListService"),
	
	SEM_SP_MEL001_SRCH_CAL_CONFIG("mel001SrchCalConfig"),
	SEM_SP_MEL001_CHK_METHOD("mel001ChkMethod"),
	SEM_SP_MEL001_EL_CAL_DETAIL("mel001ElCalDetail"),
	SEM_SP_MEL001_SRCH_CAL_DETAIL("mel001SrchCalDetail"),
	
	
	SEM_MEL001_LIST_EL_PAYMENT_PRERIOD("el001ListPaymentPeriod"),	
	SEM_SP_MRT001_RENT_CAL_DETAIL("mrt001RentCalDetail"),
	SEM_SP_MRT001_SRCH_CAL_CONFIG("mrt001SrchCalConfig"),
	SEM_SP_MRT001_CHK_METHOD("mrt001ChkMethod"),
	SEM_SP_MRT001_SRCH_CAL_DETAIL("mrt001SrchCalDetail"),
	

	SP_MSI004_SRCH_EL_COND("msi004SiteAppELCondSrch"),
	SP_MSI004_POPUP_CONTRACT_EL_USE("msi004PopupContractElUse"),
	SP_MSI004_SITE_INFO_EL_UNDO("msi004SiteInfoElUndo"),
	SP_MSI004_SITE_INFO_EL_DEPOSIT_UNDO("msi004SiteInfoElDepositUndo"),
	
	SP_MEL006_SP_ADJUST_PRIVATE("mel006SpAdjustPrivate"),
	SEM_IFRS_ONLINE_NEW("semIfrsFOnlineNew"),
	SP_EL_PAYMENT_DEL("mel006DelPayment");

	public String name = "";
	
	EQueryName(String name) {
	this.name = name;
	}
}
