package th.co.ais.domain.si;

// Generated 27 ¾.Â. 2557, 18:39:17 by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * SemSaSiteApp generated by hbm2java
 */
@Entity
@Table(name = "SEM_SA_SITE_APP")
public class SiteApp implements java.io.Serializable {

	private String siteAppId;
	private Long version;
	private String contractId;
	private Long contractTime;
	private Long contractTimeSeq;
	private String contractNo;
	private String reqType;
	private String reqDocType;
	private String title;
	private String reqOfficer;
	private String reqOfficerManual;
	private String company;
	private String region;
	private String docNo;
	private Date docDt;
	private String docStatus;
	private String needLegalApprove;
	private String needAvpApprove;
	private String locationId;
	private String locationZone;
	private String isCoLocate;
	private String coContractNo;
	private String terminateReason;
	private String terminateRemoveFlag;
	private Date terminateRemoveDt;
	private String terminateCancelRelateData;
	private String terminateNote;
	private String locationType;
	private String locationAddressNo;
	private String locationBuilding;
	private String locationFloor;
	private String locationRoomNo;
	private String locationStreet;
	private String locationTambon;
	private String locationAmphurId;
	private String locationProvinceId;
	private String locationPostcode;
	private Long landArea;
	private String landAreaType;
	private Long deckArea;
	private Long buildingArea;
	private Long roomArea;
	private String areaRemark;
	private Date effectiveDt;
	private Date expireDt;
	private Long ageYear;
	private Long ageMonth;
	private Long ageDay;
	private String contractWanted;
	private Long promiseRenewTime;
	private Long promiseRenewPeriod;
	private String promiseRenewPeriodType;
	private String lessorName;
	private String lessorHouseNo;
	private String lessorBuilding;
	private String lessorFloor;
	private String lessorRoomNo;
	private String lessorStreet;
	private String lessorTambon;
	private String lessorAmphurId;
	private String lessorProvinceId;
	private String lessorPostcode;
	private String contactName;
	private String contactTel;
	private String contactMobile;
	private String contactFax;
	private String contactEmail;
	private Long rentAmt;
	private String rentPeriodType;
	private String rentDetail;
	private String rentWhtType;
	private Long rentWhtRate;
	private String rentWhtRateMod;
	private Long rentServiceAmt;
	private String rentServicePeriodType;
	private String rentServiceDetail;
	private String rentServiceVatType;
	private String rentServiceWhtType;
	private Long rentServiceWhtRate;
	private String rentServiceWhtRateMod;
	private String rentAreaAmtMemo;
	private String rentServiceAmtMemo;
	private String rentSetupAmtMemo;
	private String rentOtherAmtMemo;
	private String rentSpecialAmtMemo;
	private Long totalRentService;
	private String rentPaymentPeriod;
	private String rentPaymentPeriodOth;
	private String rentDepositFlag;
	private Long rentDepositBgAmt;
	private String rentDepositBgVat;
	private Long rentDepositCashAmt;
	private String rentDepositCashVat;
	private String rentRemark;
	private String elUseMultiResourse;
	private String elUseNewMeter;
	private String elUseOldMeter;
	private String elUseOwner;
	private String elOwnerType;
	private String elPayOnPackage;
	private String elPackagePeriodType;
	private String elPayOnUsed;
	private Long elUnitPrice;
	private String elVatType;
	private String elRemark;
	private String elDepositFlag;
	private Long elBgDeposit;
	private String elBgDepositVatType;
	private Long elCashDeposit;
	private String elCashDepositVatType;
	private String elDepositRemark;
	private String remarkSpecial;
	private String remarkDocuments;
	private String remarkContract;
	private String remarkAqm;
	private String remarkRisk;
	private String remarkLegal;
	private String remarkOther;
	private String ptTaxPayType;
	private String ptRemark;
	private String insFlag;
	private Long insSumInsured;
	private Date insEffectiveDt;
	private Date insExpireDt;
	private String insBeneficiary;
	private String mailName;
	private String mailHouseNo;
	private String mailBuilding;
	private String mailFloor;
	private String mailRoomNo;
	private String mailStreet;
	private String mailTambon;
	private String mailAmphurId;
	private String mailProvinceId;
	private String mailPostcode;
	private Date assignDt;
	private String assignBy;
	private String assignToUser;
	private Date leaderApproveDt;
	private String leaderApproveBy;
	private String leaderApproveRemark;
	private Date managerApproveDt;
	private String managerApproveBy;
	private String managerApproveRemark;
	private Date legalApproveDt;
	private String legalApproveBy;
	private String legalApproveRemark;
	private Date avpApproveDt;
	private String avpApproveBy;
	private String avpApproveRemark;
	private String flowStatus;
	private String recordStatus;
	private String batchNo;
	private Date batchDt;
	private String locationEditFlag;
	private String contractEditFlag;
	private String rentEditFlag;
	private String rentDepositEditFlag;
	private String elEditFlag;
	private String elDepositEditFlag;
	private String propertyTaxEditFlag;
	private String insuranceEditFlag;
	private String mailEditFlag;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private String coLocateCompany;
	private String flowBy;
	private String flowRemark;
	private Date flowDt;
	private String updateLog;
	private String assignToTeam;

	public SiteApp() {
	}

	public SiteApp(String siteAppId) {
		this.siteAppId = siteAppId;
	}

	public SiteApp(String siteAppId, String contractId,
			Long contractTime, Long contractTimeSeq,
			String contractNo, String reqType, String reqDocType, String title,
			String reqOfficer, String reqOfficerManual, String company,
			String region, String docNo, Date docDt, String docStatus,
			String needLegalApprove, String needAvpApprove, String locationId,
			String locationZone, String isCoLocate, String coContractNo,
			String terminateReason, String terminateRemoveFlag,
			Date terminateRemoveDt, String terminateCancelRelateData,
			String terminateNote, String locationType,
			String locationAddressNo, String locationBuilding,
			String locationFloor, String locationRoomNo, String locationStreet,
			String locationTambon, String locationAmphurId,
			String locationProvinceId, String locationPostcode,
			Long landArea, String landAreaType, Long deckArea,
			Long buildingArea, Long roomArea, String areaRemark,
			Date effectiveDt, Date expireDt, Long ageYear,
			Long ageMonth, Long ageDay, String contractWanted,
			Long promiseRenewTime, Long promiseRenewPeriod,
			String promiseRenewPeriodType, String lessorName,
			String lessorHouseNo, String lessorBuilding, String lessorFloor,
			String lessorRoomNo, String lessorStreet, String lessorTambon,
			String lessorAmphurId, String lessorProvinceId,
			String lessorPostcode, String contactName, String contactTel,
			String contactMobile, String contactFax, String contactEmail,
			Long rentAmt, String rentPeriodType, String rentDetail,
			String rentWhtType, Long rentWhtRate, String rentWhtRateMod,
			Long rentServiceAmt, String rentServicePeriodType,
			String rentServiceDetail, String rentServiceVatType,
			String rentServiceWhtType, Long rentServiceWhtRate,
			String rentServiceWhtRateMod, String rentAreaAmtMemo,
			String rentServiceAmtMemo, String rentSetupAmtMemo,
			String rentOtherAmtMemo, String rentSpecialAmtMemo,
			Long totalRentService, String rentPaymentPeriod,
			String rentPaymentPeriodOth, String rentDepositFlag,
			Long rentDepositBgAmt, String rentDepositBgVat,
			Long rentDepositCashAmt, String rentDepositCashVat,
			String rentRemark, String elUseMultiResourse, String elUseNewMeter,
			String elUseOldMeter, String elUseOwner, String elOwnerType,
			String elPayOnPackage, String elPackagePeriodType,
			String elPayOnUsed, Long elUnitPrice, String elVatType,
			String elRemark, String elDepositFlag, Long elBgDeposit,
			String elBgDepositVatType, Long elCashDeposit,
			String elCashDepositVatType, String elDepositRemark,
			String remarkSpecial, String remarkDocuments,
			String remarkContract, String remarkAqm, String remarkRisk,
			String remarkLegal, String remarkOther, String ptTaxPayType,
			String ptRemark, String insFlag, Long insSumInsured,
			Date insEffectiveDt, Date insExpireDt, String insBeneficiary,
			String mailName, String mailHouseNo, String mailBuilding,
			String mailFloor, String mailRoomNo, String mailStreet,
			String mailTambon, String mailAmphurId, String mailProvinceId,
			String mailPostcode, Date assignDt, String assignBy,
			String assignToUser, Date leaderApproveDt, String leaderApproveBy,
			String leaderApproveRemark, Date managerApproveDt,
			String managerApproveBy, String managerApproveRemark,
			Date legalApproveDt, String legalApproveBy,
			String legalApproveRemark, Date avpApproveDt, String avpApproveBy,
			String avpApproveRemark, String flowStatus, String recordStatus,
			String batchNo, Date batchDt, String locationEditFlag,
			String contractEditFlag, String rentEditFlag,
			String rentDepositEditFlag, String elEditFlag,
			String elDepositEditFlag, String propertyTaxEditFlag,
			String insuranceEditFlag, String mailEditFlag, Date createDt,
			String createBy, Date updateDt, String updateBy,
			String coLocateCompany, String flowBy, String flowRemark,
			Date flowDt, String updateLog, String assignToTeam) {
		this.siteAppId = siteAppId;
		this.contractId = contractId;
		this.contractTime = contractTime;
		this.contractTimeSeq = contractTimeSeq;
		this.contractNo = contractNo;
		this.reqType = reqType;
		this.reqDocType = reqDocType;
		this.title = title;
		this.reqOfficer = reqOfficer;
		this.reqOfficerManual = reqOfficerManual;
		this.company = company;
		this.region = region;
		this.docNo = docNo;
		this.docDt = docDt;
		this.docStatus = docStatus;
		this.needLegalApprove = needLegalApprove;
		this.needAvpApprove = needAvpApprove;
		this.locationId = locationId;
		this.locationZone = locationZone;
		this.isCoLocate = isCoLocate;
		this.coContractNo = coContractNo;
		this.terminateReason = terminateReason;
		this.terminateRemoveFlag = terminateRemoveFlag;
		this.terminateRemoveDt = terminateRemoveDt;
		this.terminateCancelRelateData = terminateCancelRelateData;
		this.terminateNote = terminateNote;
		this.locationType = locationType;
		this.locationAddressNo = locationAddressNo;
		this.locationBuilding = locationBuilding;
		this.locationFloor = locationFloor;
		this.locationRoomNo = locationRoomNo;
		this.locationStreet = locationStreet;
		this.locationTambon = locationTambon;
		this.locationAmphurId = locationAmphurId;
		this.locationProvinceId = locationProvinceId;
		this.locationPostcode = locationPostcode;
		this.landArea = landArea;
		this.landAreaType = landAreaType;
		this.deckArea = deckArea;
		this.buildingArea = buildingArea;
		this.roomArea = roomArea;
		this.areaRemark = areaRemark;
		this.effectiveDt = effectiveDt;
		this.expireDt = expireDt;
		this.ageYear = ageYear;
		this.ageMonth = ageMonth;
		this.ageDay = ageDay;
		this.contractWanted = contractWanted;
		this.promiseRenewTime = promiseRenewTime;
		this.promiseRenewPeriod = promiseRenewPeriod;
		this.promiseRenewPeriodType = promiseRenewPeriodType;
		this.lessorName = lessorName;
		this.lessorHouseNo = lessorHouseNo;
		this.lessorBuilding = lessorBuilding;
		this.lessorFloor = lessorFloor;
		this.lessorRoomNo = lessorRoomNo;
		this.lessorStreet = lessorStreet;
		this.lessorTambon = lessorTambon;
		this.lessorAmphurId = lessorAmphurId;
		this.lessorProvinceId = lessorProvinceId;
		this.lessorPostcode = lessorPostcode;
		this.contactName = contactName;
		this.contactTel = contactTel;
		this.contactMobile = contactMobile;
		this.contactFax = contactFax;
		this.contactEmail = contactEmail;
		this.rentAmt = rentAmt;
		this.rentPeriodType = rentPeriodType;
		this.rentDetail = rentDetail;
		this.rentWhtType = rentWhtType;
		this.rentWhtRate = rentWhtRate;
		this.rentWhtRateMod = rentWhtRateMod;
		this.rentServiceAmt = rentServiceAmt;
		this.rentServicePeriodType = rentServicePeriodType;
		this.rentServiceDetail = rentServiceDetail;
		this.rentServiceVatType = rentServiceVatType;
		this.rentServiceWhtType = rentServiceWhtType;
		this.rentServiceWhtRate = rentServiceWhtRate;
		this.rentServiceWhtRateMod = rentServiceWhtRateMod;
		this.rentAreaAmtMemo = rentAreaAmtMemo;
		this.rentServiceAmtMemo = rentServiceAmtMemo;
		this.rentSetupAmtMemo = rentSetupAmtMemo;
		this.rentOtherAmtMemo = rentOtherAmtMemo;
		this.rentSpecialAmtMemo = rentSpecialAmtMemo;
		this.totalRentService = totalRentService;
		this.rentPaymentPeriod = rentPaymentPeriod;
		this.rentPaymentPeriodOth = rentPaymentPeriodOth;
		this.rentDepositFlag = rentDepositFlag;
		this.rentDepositBgAmt = rentDepositBgAmt;
		this.rentDepositBgVat = rentDepositBgVat;
		this.rentDepositCashAmt = rentDepositCashAmt;
		this.rentDepositCashVat = rentDepositCashVat;
		this.rentRemark = rentRemark;
		this.elUseMultiResourse = elUseMultiResourse;
		this.elUseNewMeter = elUseNewMeter;
		this.elUseOldMeter = elUseOldMeter;
		this.elUseOwner = elUseOwner;
		this.elOwnerType = elOwnerType;
		this.elPayOnPackage = elPayOnPackage;
		this.elPackagePeriodType = elPackagePeriodType;
		this.elPayOnUsed = elPayOnUsed;
		this.elUnitPrice = elUnitPrice;
		this.elVatType = elVatType;
		this.elRemark = elRemark;
		this.elDepositFlag = elDepositFlag;
		this.elBgDeposit = elBgDeposit;
		this.elBgDepositVatType = elBgDepositVatType;
		this.elCashDeposit = elCashDeposit;
		this.elCashDepositVatType = elCashDepositVatType;
		this.elDepositRemark = elDepositRemark;
		this.remarkSpecial = remarkSpecial;
		this.remarkDocuments = remarkDocuments;
		this.remarkContract = remarkContract;
		this.remarkAqm = remarkAqm;
		this.remarkRisk = remarkRisk;
		this.remarkLegal = remarkLegal;
		this.remarkOther = remarkOther;
		this.ptTaxPayType = ptTaxPayType;
		this.ptRemark = ptRemark;
		this.insFlag = insFlag;
		this.insSumInsured = insSumInsured;
		this.insEffectiveDt = insEffectiveDt;
		this.insExpireDt = insExpireDt;
		this.insBeneficiary = insBeneficiary;
		this.mailName = mailName;
		this.mailHouseNo = mailHouseNo;
		this.mailBuilding = mailBuilding;
		this.mailFloor = mailFloor;
		this.mailRoomNo = mailRoomNo;
		this.mailStreet = mailStreet;
		this.mailTambon = mailTambon;
		this.mailAmphurId = mailAmphurId;
		this.mailProvinceId = mailProvinceId;
		this.mailPostcode = mailPostcode;
		this.assignDt = assignDt;
		this.assignBy = assignBy;
		this.assignToUser = assignToUser;
		this.leaderApproveDt = leaderApproveDt;
		this.leaderApproveBy = leaderApproveBy;
		this.leaderApproveRemark = leaderApproveRemark;
		this.managerApproveDt = managerApproveDt;
		this.managerApproveBy = managerApproveBy;
		this.managerApproveRemark = managerApproveRemark;
		this.legalApproveDt = legalApproveDt;
		this.legalApproveBy = legalApproveBy;
		this.legalApproveRemark = legalApproveRemark;
		this.avpApproveDt = avpApproveDt;
		this.avpApproveBy = avpApproveBy;
		this.avpApproveRemark = avpApproveRemark;
		this.flowStatus = flowStatus;
		this.recordStatus = recordStatus;
		this.batchNo = batchNo;
		this.batchDt = batchDt;
		this.locationEditFlag = locationEditFlag;
		this.contractEditFlag = contractEditFlag;
		this.rentEditFlag = rentEditFlag;
		this.rentDepositEditFlag = rentDepositEditFlag;
		this.elEditFlag = elEditFlag;
		this.elDepositEditFlag = elDepositEditFlag;
		this.propertyTaxEditFlag = propertyTaxEditFlag;
		this.insuranceEditFlag = insuranceEditFlag;
		this.mailEditFlag = mailEditFlag;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
		this.coLocateCompany = coLocateCompany;
		this.flowBy = flowBy;
		this.flowRemark = flowRemark;
		this.flowDt = flowDt;
		this.updateLog = updateLog;
		this.assignToTeam = assignToTeam;
	}

	@Id
	@Column(name = "SITE_APP_ID", unique = true, nullable = false, length = 50)
	public String getSiteAppId() {
		return this.siteAppId;
	}

	public void setSiteAppId(String siteAppId) {
		this.siteAppId = siteAppId;
	}

	@Version
	@Column(name = "VERSION", precision = 22, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "CONTRACT_ID", length = 50)
	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	@Column(name = "CONTRACT_TIME", precision = 22, scale = 0)
	public Long getContractTime() {
		return this.contractTime;
	}

	public void setContractTime(Long contractTime) {
		this.contractTime = contractTime;
	}

	@Column(name = "CONTRACT_TIME_SEQ", precision = 22, scale = 0)
	public Long getContractTimeSeq() {
		return this.contractTimeSeq;
	}

	public void setContractTimeSeq(Long contractTimeSeq) {
		this.contractTimeSeq = contractTimeSeq;
	}

	@Column(name = "CONTRACT_NO", length = 20)
	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Column(name = "REQ_TYPE", length = 2)
	public String getReqType() {
		return this.reqType;
	}

	public void setReqType(String reqType) {
		this.reqType = reqType;
	}

	@Column(name = "REQ_DOC_TYPE", length = 2)
	public String getReqDocType() {
		return this.reqDocType;
	}

	public void setReqDocType(String reqDocType) {
		this.reqDocType = reqDocType;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "REQ_OFFICER", length = 100)
	public String getReqOfficer() {
		return this.reqOfficer;
	}

	public void setReqOfficer(String reqOfficer) {
		this.reqOfficer = reqOfficer;
	}

	@Column(name = "REQ_OFFICER_MANUAL", length = 1)
	public String getReqOfficerManual() {
		return this.reqOfficerManual;
	}

	public void setReqOfficerManual(String reqOfficerManual) {
		this.reqOfficerManual = reqOfficerManual;
	}

	@Column(name = "COMPANY", length = 10)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "REGION", length = 10)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "DOC_NO", length = 20)
	public String getDocNo() {
		return this.docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOC_DT", length = 7)
	public Date getDocDt() {
		return this.docDt;
	}

	public void setDocDt(Date docDt) {
		this.docDt = docDt;
	}

	@Column(name = "DOC_STATUS", length = 2)
	public String getDocStatus() {
		return this.docStatus;
	}

	public void setDocStatus(String docStatus) {
		this.docStatus = docStatus;
	}

	@Column(name = "NEED_LEGAL_APPROVE", length = 1)
	public String getNeedLegalApprove() {
		return this.needLegalApprove;
	}

	public void setNeedLegalApprove(String needLegalApprove) {
		this.needLegalApprove = needLegalApprove;
	}

	@Column(name = "NEED_AVP_APPROVE", length = 1)
	public String getNeedAvpApprove() {
		return this.needAvpApprove;
	}

	public void setNeedAvpApprove(String needAvpApprove) {
		this.needAvpApprove = needAvpApprove;
	}

	@Column(name = "LOCATION_ID", length = 20)
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "LOCATION_ZONE", length = 20)
	public String getLocationZone() {
		return this.locationZone;
	}

	public void setLocationZone(String locationZone) {
		this.locationZone = locationZone;
	}

	@Column(name = "IS_CO_LOCATE", length = 1)
	public String getIsCoLocate() {
		return this.isCoLocate;
	}

	public void setIsCoLocate(String isCoLocate) {
		this.isCoLocate = isCoLocate;
	}

	@Column(name = "CO_CONTRACT_NO", length = 20)
	public String getCoContractNo() {
		return this.coContractNo;
	}

	public void setCoContractNo(String coContractNo) {
		this.coContractNo = coContractNo;
	}

	@Column(name = "TERMINATE_REASON", length = 2000)
	public String getTerminateReason() {
		return this.terminateReason;
	}

	public void setTerminateReason(String terminateReason) {
		this.terminateReason = terminateReason;
	}

	@Column(name = "TERMINATE_REMOVE_FLAG", length = 1)
	public String getTerminateRemoveFlag() {
		return this.terminateRemoveFlag;
	}

	public void setTerminateRemoveFlag(String terminateRemoveFlag) {
		this.terminateRemoveFlag = terminateRemoveFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TERMINATE_REMOVE_DT", length = 7)
	public Date getTerminateRemoveDt() {
		return this.terminateRemoveDt;
	}

	public void setTerminateRemoveDt(Date terminateRemoveDt) {
		this.terminateRemoveDt = terminateRemoveDt;
	}

	@Column(name = "TERMINATE_CANCEL_RELATE_DATA", length = 1)
	public String getTerminateCancelRelateData() {
		return this.terminateCancelRelateData;
	}

	public void setTerminateCancelRelateData(String terminateCancelRelateData) {
		this.terminateCancelRelateData = terminateCancelRelateData;
	}

	@Column(name = "TERMINATE_NOTE", length = 2000)
	public String getTerminateNote() {
		return this.terminateNote;
	}

	public void setTerminateNote(String terminateNote) {
		this.terminateNote = terminateNote;
	}

	@Column(name = "LOCATION_TYPE", length = 2)
	public String getLocationType() {
		return this.locationType;
	}

	public void setLocationType(String locationType) {
		this.locationType = locationType;
	}

	@Column(name = "LOCATION_ADDRESS_NO", length = 500)
	public String getLocationAddressNo() {
		return this.locationAddressNo;
	}

	public void setLocationAddressNo(String locationAddressNo) {
		this.locationAddressNo = locationAddressNo;
	}

	@Column(name = "LOCATION_BUILDING", length = 100)
	public String getLocationBuilding() {
		return this.locationBuilding;
	}

	public void setLocationBuilding(String locationBuilding) {
		this.locationBuilding = locationBuilding;
	}

	@Column(name = "LOCATION_FLOOR", length = 10)
	public String getLocationFloor() {
		return this.locationFloor;
	}

	public void setLocationFloor(String locationFloor) {
		this.locationFloor = locationFloor;
	}

	@Column(name = "LOCATION_ROOM_NO", length = 10)
	public String getLocationRoomNo() {
		return this.locationRoomNo;
	}

	public void setLocationRoomNo(String locationRoomNo) {
		this.locationRoomNo = locationRoomNo;
	}

	@Column(name = "LOCATION_STREET", length = 100)
	public String getLocationStreet() {
		return this.locationStreet;
	}

	public void setLocationStreet(String locationStreet) {
		this.locationStreet = locationStreet;
	}

	@Column(name = "LOCATION_TAMBON", length = 100)
	public String getLocationTambon() {
		return this.locationTambon;
	}

	public void setLocationTambon(String locationTambon) {
		this.locationTambon = locationTambon;
	}

	@Column(name = "LOCATION_AMPHUR_ID", length = 50)
	public String getLocationAmphurId() {
		return this.locationAmphurId;
	}

	public void setLocationAmphurId(String locationAmphurId) {
		this.locationAmphurId = locationAmphurId;
	}

	@Column(name = "LOCATION_PROVINCE_ID", length = 50)
	public String getLocationProvinceId() {
		return this.locationProvinceId;
	}

	public void setLocationProvinceId(String locationProvinceId) {
		this.locationProvinceId = locationProvinceId;
	}

	@Column(name = "LOCATION_POSTCODE", length = 10)
	public String getLocationPostcode() {
		return this.locationPostcode;
	}

	public void setLocationPostcode(String locationPostcode) {
		this.locationPostcode = locationPostcode;
	}

	@Column(name = "LAND_AREA", precision = 15)
	public Long getLandArea() {
		return this.landArea;
	}

	public void setLandArea(Long landArea) {
		this.landArea = landArea;
	}

	@Column(name = "LAND_AREA_TYPE", length = 2)
	public String getLandAreaType() {
		return this.landAreaType;
	}

	public void setLandAreaType(String landAreaType) {
		this.landAreaType = landAreaType;
	}

	@Column(name = "DECK_AREA", precision = 15)
	public Long getDeckArea() {
		return this.deckArea;
	}

	public void setDeckArea(Long deckArea) {
		this.deckArea = deckArea;
	}

	@Column(name = "BUILDING_AREA", precision = 15)
	public Long getBuildingArea() {
		return this.buildingArea;
	}

	public void setBuildingArea(Long buildingArea) {
		this.buildingArea = buildingArea;
	}

	@Column(name = "ROOM_AREA", precision = 15)
	public Long getRoomArea() {
		return this.roomArea;
	}

	public void setRoomArea(Long roomArea) {
		this.roomArea = roomArea;
	}

	@Column(name = "AREA_REMARK", length = 500)
	public String getAreaRemark() {
		return this.areaRemark;
	}

	public void setAreaRemark(String areaRemark) {
		this.areaRemark = areaRemark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EFFECTIVE_DT", length = 7)
	public Date getEffectiveDt() {
		return this.effectiveDt;
	}

	public void setEffectiveDt(Date effectiveDt) {
		this.effectiveDt = effectiveDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPIRE_DT", length = 7)
	public Date getExpireDt() {
		return this.expireDt;
	}

	public void setExpireDt(Date expireDt) {
		this.expireDt = expireDt;
	}

	@Column(name = "AGE_YEAR", precision = 22, scale = 0)
	public Long getAgeYear() {
		return this.ageYear;
	}

	public void setAgeYear(Long ageYear) {
		this.ageYear = ageYear;
	}

	@Column(name = "AGE_MONTH", precision = 22, scale = 0)
	public Long getAgeMonth() {
		return this.ageMonth;
	}

	public void setAgeMonth(Long ageMonth) {
		this.ageMonth = ageMonth;
	}

	@Column(name = "AGE_DAY", precision = 22, scale = 0)
	public Long getAgeDay() {
		return this.ageDay;
	}

	public void setAgeDay(Long ageDay) {
		this.ageDay = ageDay;
	}

	@Column(name = "CONTRACT_WANTED", length = 1)
	public String getContractWanted() {
		return this.contractWanted;
	}

	public void setContractWanted(String contractWanted) {
		this.contractWanted = contractWanted;
	}

	@Column(name = "PROMISE_RENEW_TIME", precision = 22, scale = 0)
	public Long getPromiseRenewTime() {
		return this.promiseRenewTime;
	}

	public void setPromiseRenewTime(Long promiseRenewTime) {
		this.promiseRenewTime = promiseRenewTime;
	}

	@Column(name = "PROMISE_RENEW_PERIOD", precision = 22, scale = 0)
	public Long getPromiseRenewPeriod() {
		return this.promiseRenewPeriod;
	}

	public void setPromiseRenewPeriod(Long promiseRenewPeriod) {
		this.promiseRenewPeriod = promiseRenewPeriod;
	}

	@Column(name = "PROMISE_RENEW_PERIOD_TYPE", length = 2)
	public String getPromiseRenewPeriodType() {
		return this.promiseRenewPeriodType;
	}

	public void setPromiseRenewPeriodType(String promiseRenewPeriodType) {
		this.promiseRenewPeriodType = promiseRenewPeriodType;
	}

	@Column(name = "LESSOR_NAME", length = 1000)
	public String getLessorName() {
		return this.lessorName;
	}

	public void setLessorName(String lessorName) {
		this.lessorName = lessorName;
	}

	@Column(name = "LESSOR_HOUSE_NO", length = 500)
	public String getLessorHouseNo() {
		return this.lessorHouseNo;
	}

	public void setLessorHouseNo(String lessorHouseNo) {
		this.lessorHouseNo = lessorHouseNo;
	}

	@Column(name = "LESSOR_BUILDING", length = 100)
	public String getLessorBuilding() {
		return this.lessorBuilding;
	}

	public void setLessorBuilding(String lessorBuilding) {
		this.lessorBuilding = lessorBuilding;
	}

	@Column(name = "LESSOR_FLOOR", length = 10)
	public String getLessorFloor() {
		return this.lessorFloor;
	}

	public void setLessorFloor(String lessorFloor) {
		this.lessorFloor = lessorFloor;
	}

	@Column(name = "LESSOR_ROOM_NO", length = 10)
	public String getLessorRoomNo() {
		return this.lessorRoomNo;
	}

	public void setLessorRoomNo(String lessorRoomNo) {
		this.lessorRoomNo = lessorRoomNo;
	}

	@Column(name = "LESSOR_STREET", length = 100)
	public String getLessorStreet() {
		return this.lessorStreet;
	}

	public void setLessorStreet(String lessorStreet) {
		this.lessorStreet = lessorStreet;
	}

	@Column(name = "LESSOR_TAMBON", length = 100)
	public String getLessorTambon() {
		return this.lessorTambon;
	}

	public void setLessorTambon(String lessorTambon) {
		this.lessorTambon = lessorTambon;
	}

	@Column(name = "LESSOR_AMPHUR_ID", length = 20)
	public String getLessorAmphurId() {
		return this.lessorAmphurId;
	}

	public void setLessorAmphurId(String lessorAmphurId) {
		this.lessorAmphurId = lessorAmphurId;
	}

	@Column(name = "LESSOR_PROVINCE_ID", length = 20)
	public String getLessorProvinceId() {
		return this.lessorProvinceId;
	}

	public void setLessorProvinceId(String lessorProvinceId) {
		this.lessorProvinceId = lessorProvinceId;
	}

	@Column(name = "LESSOR_POSTCODE", length = 10)
	public String getLessorPostcode() {
		return this.lessorPostcode;
	}

	public void setLessorPostcode(String lessorPostcode) {
		this.lessorPostcode = lessorPostcode;
	}

	@Column(name = "CONTACT_NAME", length = 100)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "CONTACT_TEL", length = 100)
	public String getContactTel() {
		return this.contactTel;
	}

	public void setContactTel(String contactTel) {
		this.contactTel = contactTel;
	}

	@Column(name = "CONTACT_MOBILE", length = 200)
	public String getContactMobile() {
		return this.contactMobile;
	}

	public void setContactMobile(String contactMobile) {
		this.contactMobile = contactMobile;
	}

	@Column(name = "CONTACT_FAX", length = 100)
	public String getContactFax() {
		return this.contactFax;
	}

	public void setContactFax(String contactFax) {
		this.contactFax = contactFax;
	}

	@Column(name = "CONTACT_EMAIL", length = 200)
	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	@Column(name = "RENT_AMT", precision = 15)
	public Long getRentAmt() {
		return this.rentAmt;
	}

	public void setRentAmt(Long rentAmt) {
		this.rentAmt = rentAmt;
	}

	@Column(name = "RENT_PERIOD_TYPE", length = 2)
	public String getRentPeriodType() {
		return this.rentPeriodType;
	}

	public void setRentPeriodType(String rentPeriodType) {
		this.rentPeriodType = rentPeriodType;
	}

	@Column(name = "RENT_DETAIL", length = 500)
	public String getRentDetail() {
		return this.rentDetail;
	}

	public void setRentDetail(String rentDetail) {
		this.rentDetail = rentDetail;
	}

	@Column(name = "RENT_WHT_TYPE", length = 2)
	public String getRentWhtType() {
		return this.rentWhtType;
	}

	public void setRentWhtType(String rentWhtType) {
		this.rentWhtType = rentWhtType;
	}

	@Column(name = "RENT_WHT_RATE", precision = 5)
	public Long getRentWhtRate() {
		return this.rentWhtRate;
	}

	public void setRentWhtRate(Long rentWhtRate) {
		this.rentWhtRate = rentWhtRate;
	}

	@Column(name = "RENT_WHT_RATE_MOD", length = 1)
	public String getRentWhtRateMod() {
		return this.rentWhtRateMod;
	}

	public void setRentWhtRateMod(String rentWhtRateMod) {
		this.rentWhtRateMod = rentWhtRateMod;
	}

	@Column(name = "RENT_SERVICE_AMT", precision = 15)
	public Long getRentServiceAmt() {
		return this.rentServiceAmt;
	}

	public void setRentServiceAmt(Long rentServiceAmt) {
		this.rentServiceAmt = rentServiceAmt;
	}

	@Column(name = "RENT_SERVICE_PERIOD_TYPE", length = 2)
	public String getRentServicePeriodType() {
		return this.rentServicePeriodType;
	}

	public void setRentServicePeriodType(String rentServicePeriodType) {
		this.rentServicePeriodType = rentServicePeriodType;
	}

	@Column(name = "RENT_SERVICE_DETAIL", length = 500)
	public String getRentServiceDetail() {
		return this.rentServiceDetail;
	}

	public void setRentServiceDetail(String rentServiceDetail) {
		this.rentServiceDetail = rentServiceDetail;
	}

	@Column(name = "RENT_SERVICE_VAT_TYPE", length = 2)
	public String getRentServiceVatType() {
		return this.rentServiceVatType;
	}

	public void setRentServiceVatType(String rentServiceVatType) {
		this.rentServiceVatType = rentServiceVatType;
	}

	@Column(name = "RENT_SERVICE_WHT_TYPE", length = 2)
	public String getRentServiceWhtType() {
		return this.rentServiceWhtType;
	}

	public void setRentServiceWhtType(String rentServiceWhtType) {
		this.rentServiceWhtType = rentServiceWhtType;
	}

	@Column(name = "RENT_SERVICE_WHT_RATE", precision = 5)
	public Long getRentServiceWhtRate() {
		return this.rentServiceWhtRate;
	}

	public void setRentServiceWhtRate(Long rentServiceWhtRate) {
		this.rentServiceWhtRate = rentServiceWhtRate;
	}

	@Column(name = "RENT_SERVICE_WHT_RATE_MOD", length = 1)
	public String getRentServiceWhtRateMod() {
		return this.rentServiceWhtRateMod;
	}

	public void setRentServiceWhtRateMod(String rentServiceWhtRateMod) {
		this.rentServiceWhtRateMod = rentServiceWhtRateMod;
	}

	@Column(name = "RENT_AREA_AMT_MEMO", length = 2000)
	public String getRentAreaAmtMemo() {
		return this.rentAreaAmtMemo;
	}

	public void setRentAreaAmtMemo(String rentAreaAmtMemo) {
		this.rentAreaAmtMemo = rentAreaAmtMemo;
	}

	@Column(name = "RENT_SERVICE_AMT_MEMO", length = 2000)
	public String getRentServiceAmtMemo() {
		return this.rentServiceAmtMemo;
	}

	public void setRentServiceAmtMemo(String rentServiceAmtMemo) {
		this.rentServiceAmtMemo = rentServiceAmtMemo;
	}

	@Column(name = "RENT_SETUP_AMT_MEMO", length = 2000)
	public String getRentSetupAmtMemo() {
		return this.rentSetupAmtMemo;
	}

	public void setRentSetupAmtMemo(String rentSetupAmtMemo) {
		this.rentSetupAmtMemo = rentSetupAmtMemo;
	}

	@Column(name = "RENT_OTHER_AMT_MEMO", length = 2000)
	public String getRentOtherAmtMemo() {
		return this.rentOtherAmtMemo;
	}

	public void setRentOtherAmtMemo(String rentOtherAmtMemo) {
		this.rentOtherAmtMemo = rentOtherAmtMemo;
	}

	@Column(name = "RENT_SPECIAL_AMT_MEMO", length = 4000)
	public String getRentSpecialAmtMemo() {
		return this.rentSpecialAmtMemo;
	}

	public void setRentSpecialAmtMemo(String rentSpecialAmtMemo) {
		this.rentSpecialAmtMemo = rentSpecialAmtMemo;
	}

	@Column(name = "TOTAL_RENT_SERVICE", precision = 15)
	public Long getTotalRentService() {
		return this.totalRentService;
	}

	public void setTotalRentService(Long totalRentService) {
		this.totalRentService = totalRentService;
	}

	@Column(name = "RENT_PAYMENT_PERIOD", length = 2)
	public String getRentPaymentPeriod() {
		return this.rentPaymentPeriod;
	}

	public void setRentPaymentPeriod(String rentPaymentPeriod) {
		this.rentPaymentPeriod = rentPaymentPeriod;
	}

	@Column(name = "RENT_PAYMENT_PERIOD_OTH", length = 500)
	public String getRentPaymentPeriodOth() {
		return this.rentPaymentPeriodOth;
	}

	public void setRentPaymentPeriodOth(String rentPaymentPeriodOth) {
		this.rentPaymentPeriodOth = rentPaymentPeriodOth;
	}

	@Column(name = "RENT_DEPOSIT_FLAG", length = 1)
	public String getRentDepositFlag() {
		return this.rentDepositFlag;
	}

	public void setRentDepositFlag(String rentDepositFlag) {
		this.rentDepositFlag = rentDepositFlag;
	}

	@Column(name = "RENT_DEPOSIT_BG_AMT", precision = 22, scale = 0)
	public Long getRentDepositBgAmt() {
		return this.rentDepositBgAmt;
	}

	public void setRentDepositBgAmt(Long rentDepositBgAmt) {
		this.rentDepositBgAmt = rentDepositBgAmt;
	}

	@Column(name = "RENT_DEPOSIT_BG_VAT", length = 2)
	public String getRentDepositBgVat() {
		return this.rentDepositBgVat;
	}

	public void setRentDepositBgVat(String rentDepositBgVat) {
		this.rentDepositBgVat = rentDepositBgVat;
	}

	@Column(name = "RENT_DEPOSIT_CASH_AMT", precision = 22, scale = 0)
	public Long getRentDepositCashAmt() {
		return this.rentDepositCashAmt;
	}

	public void setRentDepositCashAmt(Long rentDepositCashAmt) {
		this.rentDepositCashAmt = rentDepositCashAmt;
	}

	@Column(name = "RENT_DEPOSIT_CASH_VAT", length = 2)
	public String getRentDepositCashVat() {
		return this.rentDepositCashVat;
	}

	public void setRentDepositCashVat(String rentDepositCashVat) {
		this.rentDepositCashVat = rentDepositCashVat;
	}

	@Column(name = "RENT_REMARK", length = 2000)
	public String getRentRemark() {
		return this.rentRemark;
	}

	public void setRentRemark(String rentRemark) {
		this.rentRemark = rentRemark;
	}

	@Column(name = "EL_USE_MULTI_RESOURSE", length = 1)
	public String getElUseMultiResourse() {
		return this.elUseMultiResourse;
	}

	public void setElUseMultiResourse(String elUseMultiResourse) {
		this.elUseMultiResourse = elUseMultiResourse;
	}

	@Column(name = "EL_USE_NEW_METER", length = 1)
	public String getElUseNewMeter() {
		return this.elUseNewMeter;
	}

	public void setElUseNewMeter(String elUseNewMeter) {
		this.elUseNewMeter = elUseNewMeter;
	}

	@Column(name = "EL_USE_OLD_METER", length = 1)
	public String getElUseOldMeter() {
		return this.elUseOldMeter;
	}

	public void setElUseOldMeter(String elUseOldMeter) {
		this.elUseOldMeter = elUseOldMeter;
	}

	@Column(name = "EL_USE_OWNER", length = 1)
	public String getElUseOwner() {
		return this.elUseOwner;
	}

	public void setElUseOwner(String elUseOwner) {
		this.elUseOwner = elUseOwner;
	}

	@Column(name = "EL_OWNER_TYPE", length = 2)
	public String getElOwnerType() {
		return this.elOwnerType;
	}

	public void setElOwnerType(String elOwnerType) {
		this.elOwnerType = elOwnerType;
	}

	@Column(name = "EL_PAY_ON_PACKAGE", length = 1)
	public String getElPayOnPackage() {
		return this.elPayOnPackage;
	}

	public void setElPayOnPackage(String elPayOnPackage) {
		this.elPayOnPackage = elPayOnPackage;
	}

	@Column(name = "EL_PACKAGE_PERIOD_TYPE", length = 2)
	public String getElPackagePeriodType() {
		return this.elPackagePeriodType;
	}

	public void setElPackagePeriodType(String elPackagePeriodType) {
		this.elPackagePeriodType = elPackagePeriodType;
	}

	@Column(name = "EL_PAY_ON_USED", length = 1)
	public String getElPayOnUsed() {
		return this.elPayOnUsed;
	}

	public void setElPayOnUsed(String elPayOnUsed) {
		this.elPayOnUsed = elPayOnUsed;
	}

	@Column(name = "EL_UNIT_PRICE", precision = 15)
	public Long getElUnitPrice() {
		return this.elUnitPrice;
	}

	public void setElUnitPrice(Long elUnitPrice) {
		this.elUnitPrice = elUnitPrice;
	}

	@Column(name = "EL_VAT_TYPE", length = 2)
	public String getElVatType() {
		return this.elVatType;
	}

	public void setElVatType(String elVatType) {
		this.elVatType = elVatType;
	}

	@Column(name = "EL_REMARK", length = 1000)
	public String getElRemark() {
		return this.elRemark;
	}

	public void setElRemark(String elRemark) {
		this.elRemark = elRemark;
	}

	@Column(name = "EL_DEPOSIT_FLAG", length = 1)
	public String getElDepositFlag() {
		return this.elDepositFlag;
	}

	public void setElDepositFlag(String elDepositFlag) {
		this.elDepositFlag = elDepositFlag;
	}

	@Column(name = "EL_BG_DEPOSIT", precision = 22, scale = 0)
	public Long getElBgDeposit() {
		return this.elBgDeposit;
	}

	public void setElBgDeposit(Long elBgDeposit) {
		this.elBgDeposit = elBgDeposit;
	}

	@Column(name = "EL_BG_DEPOSIT_VAT_TYPE", length = 2)
	public String getElBgDepositVatType() {
		return this.elBgDepositVatType;
	}

	public void setElBgDepositVatType(String elBgDepositVatType) {
		this.elBgDepositVatType = elBgDepositVatType;
	}

	@Column(name = "EL_CASH_DEPOSIT", precision = 22, scale = 0)
	public Long getElCashDeposit() {
		return this.elCashDeposit;
	}

	public void setElCashDeposit(Long elCashDeposit) {
		this.elCashDeposit = elCashDeposit;
	}

	@Column(name = "EL_CASH_DEPOSIT_VAT_TYPE", length = 2)
	public String getElCashDepositVatType() {
		return this.elCashDepositVatType;
	}

	public void setElCashDepositVatType(String elCashDepositVatType) {
		this.elCashDepositVatType = elCashDepositVatType;
	}

	@Column(name = "EL_DEPOSIT_REMARK", length = 2000)
	public String getElDepositRemark() {
		return this.elDepositRemark;
	}

	public void setElDepositRemark(String elDepositRemark) {
		this.elDepositRemark = elDepositRemark;
	}

	@Column(name = "REMARK_SPECIAL", length = 500)
	public String getRemarkSpecial() {
		return this.remarkSpecial;
	}

	public void setRemarkSpecial(String remarkSpecial) {
		this.remarkSpecial = remarkSpecial;
	}

	@Column(name = "REMARK_DOCUMENTS", length = 2000)
	public String getRemarkDocuments() {
		return this.remarkDocuments;
	}

	public void setRemarkDocuments(String remarkDocuments) {
		this.remarkDocuments = remarkDocuments;
	}

	@Column(name = "REMARK_CONTRACT", length = 2000)
	public String getRemarkContract() {
		return this.remarkContract;
	}

	public void setRemarkContract(String remarkContract) {
		this.remarkContract = remarkContract;
	}

	@Column(name = "REMARK_AQM", length = 2000)
	public String getRemarkAqm() {
		return this.remarkAqm;
	}

	public void setRemarkAqm(String remarkAqm) {
		this.remarkAqm = remarkAqm;
	}

	@Column(name = "REMARK_RISK", length = 2000)
	public String getRemarkRisk() {
		return this.remarkRisk;
	}

	public void setRemarkRisk(String remarkRisk) {
		this.remarkRisk = remarkRisk;
	}

	@Column(name = "REMARK_LEGAL", length = 2000)
	public String getRemarkLegal() {
		return this.remarkLegal;
	}

	public void setRemarkLegal(String remarkLegal) {
		this.remarkLegal = remarkLegal;
	}

	@Column(name = "REMARK_OTHER", length = 2000)
	public String getRemarkOther() {
		return this.remarkOther;
	}

	public void setRemarkOther(String remarkOther) {
		this.remarkOther = remarkOther;
	}

	@Column(name = "PT_TAX_PAY_TYPE", length = 2)
	public String getPtTaxPayType() {
		return this.ptTaxPayType;
	}

	public void setPtTaxPayType(String ptTaxPayType) {
		this.ptTaxPayType = ptTaxPayType;
	}

	@Column(name = "PT_REMARK", length = 1000)
	public String getPtRemark() {
		return this.ptRemark;
	}

	public void setPtRemark(String ptRemark) {
		this.ptRemark = ptRemark;
	}

	@Column(name = "INS_FLAG", length = 1)
	public String getInsFlag() {
		return this.insFlag;
	}

	public void setInsFlag(String insFlag) {
		this.insFlag = insFlag;
	}

	@Column(name = "INS_SUM_INSURED", precision = 15)
	public Long getInsSumInsured() {
		return this.insSumInsured;
	}

	public void setInsSumInsured(Long insSumInsured) {
		this.insSumInsured = insSumInsured;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INS_EFFECTIVE_DT", length = 7)
	public Date getInsEffectiveDt() {
		return this.insEffectiveDt;
	}

	public void setInsEffectiveDt(Date insEffectiveDt) {
		this.insEffectiveDt = insEffectiveDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INS_EXPIRE_DT", length = 7)
	public Date getInsExpireDt() {
		return this.insExpireDt;
	}

	public void setInsExpireDt(Date insExpireDt) {
		this.insExpireDt = insExpireDt;
	}

	@Column(name = "INS_BENEFICIARY", length = 500)
	public String getInsBeneficiary() {
		return this.insBeneficiary;
	}

	public void setInsBeneficiary(String insBeneficiary) {
		this.insBeneficiary = insBeneficiary;
	}

	@Column(name = "MAIL_NAME", length = 100)
	public String getMailName() {
		return this.mailName;
	}

	public void setMailName(String mailName) {
		this.mailName = mailName;
	}

	@Column(name = "MAIL_HOUSE_NO", length = 100)
	public String getMailHouseNo() {
		return this.mailHouseNo;
	}

	public void setMailHouseNo(String mailHouseNo) {
		this.mailHouseNo = mailHouseNo;
	}

	@Column(name = "MAIL_BUILDING", length = 100)
	public String getMailBuilding() {
		return this.mailBuilding;
	}

	public void setMailBuilding(String mailBuilding) {
		this.mailBuilding = mailBuilding;
	}

	@Column(name = "MAIL_FLOOR", length = 10)
	public String getMailFloor() {
		return this.mailFloor;
	}

	public void setMailFloor(String mailFloor) {
		this.mailFloor = mailFloor;
	}

	@Column(name = "MAIL_ROOM_NO", length = 10)
	public String getMailRoomNo() {
		return this.mailRoomNo;
	}

	public void setMailRoomNo(String mailRoomNo) {
		this.mailRoomNo = mailRoomNo;
	}

	@Column(name = "MAIL_STREET", length = 100)
	public String getMailStreet() {
		return this.mailStreet;
	}

	public void setMailStreet(String mailStreet) {
		this.mailStreet = mailStreet;
	}

	@Column(name = "MAIL_TAMBON", length = 100)
	public String getMailTambon() {
		return this.mailTambon;
	}

	public void setMailTambon(String mailTambon) {
		this.mailTambon = mailTambon;
	}

	@Column(name = "MAIL_AMPHUR_ID", length = 20)
	public String getMailAmphurId() {
		return this.mailAmphurId;
	}

	public void setMailAmphurId(String mailAmphurId) {
		this.mailAmphurId = mailAmphurId;
	}

	@Column(name = "MAIL_PROVINCE_ID", length = 20)
	public String getMailProvinceId() {
		return this.mailProvinceId;
	}

	public void setMailProvinceId(String mailProvinceId) {
		this.mailProvinceId = mailProvinceId;
	}

	@Column(name = "MAIL_POSTCODE", length = 10)
	public String getMailPostcode() {
		return this.mailPostcode;
	}

	public void setMailPostcode(String mailPostcode) {
		this.mailPostcode = mailPostcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ASSIGN_DT", length = 7)
	public Date getAssignDt() {
		return this.assignDt;
	}

	public void setAssignDt(Date assignDt) {
		this.assignDt = assignDt;
	}

	@Column(name = "ASSIGN_BY", length = 50)
	public String getAssignBy() {
		return this.assignBy;
	}

	public void setAssignBy(String assignBy) {
		this.assignBy = assignBy;
	}

	@Column(name = "ASSIGN_TO_USER", length = 50)
	public String getAssignToUser() {
		return this.assignToUser;
	}

	public void setAssignToUser(String assignToUser) {
		this.assignToUser = assignToUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LEADER_APPROVE_DT", length = 7)
	public Date getLeaderApproveDt() {
		return this.leaderApproveDt;
	}

	public void setLeaderApproveDt(Date leaderApproveDt) {
		this.leaderApproveDt = leaderApproveDt;
	}

	@Column(name = "LEADER_APPROVE_BY", length = 50)
	public String getLeaderApproveBy() {
		return this.leaderApproveBy;
	}

	public void setLeaderApproveBy(String leaderApproveBy) {
		this.leaderApproveBy = leaderApproveBy;
	}

	@Column(name = "LEADER_APPROVE_REMARK", length = 1000)
	public String getLeaderApproveRemark() {
		return this.leaderApproveRemark;
	}

	public void setLeaderApproveRemark(String leaderApproveRemark) {
		this.leaderApproveRemark = leaderApproveRemark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MANAGER_APPROVE_DT", length = 7)
	public Date getManagerApproveDt() {
		return this.managerApproveDt;
	}

	public void setManagerApproveDt(Date managerApproveDt) {
		this.managerApproveDt = managerApproveDt;
	}

	@Column(name = "MANAGER_APPROVE_BY", length = 50)
	public String getManagerApproveBy() {
		return this.managerApproveBy;
	}

	public void setManagerApproveBy(String managerApproveBy) {
		this.managerApproveBy = managerApproveBy;
	}

	@Column(name = "MANAGER_APPROVE_REMARK", length = 1000)
	public String getManagerApproveRemark() {
		return this.managerApproveRemark;
	}

	public void setManagerApproveRemark(String managerApproveRemark) {
		this.managerApproveRemark = managerApproveRemark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LEGAL_APPROVE_DT", length = 7)
	public Date getLegalApproveDt() {
		return this.legalApproveDt;
	}

	public void setLegalApproveDt(Date legalApproveDt) {
		this.legalApproveDt = legalApproveDt;
	}

	@Column(name = "LEGAL_APPROVE_BY", length = 50)
	public String getLegalApproveBy() {
		return this.legalApproveBy;
	}

	public void setLegalApproveBy(String legalApproveBy) {
		this.legalApproveBy = legalApproveBy;
	}

	@Column(name = "LEGAL_APPROVE_REMARK", length = 1000)
	public String getLegalApproveRemark() {
		return this.legalApproveRemark;
	}

	public void setLegalApproveRemark(String legalApproveRemark) {
		this.legalApproveRemark = legalApproveRemark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AVP_APPROVE_DT", length = 7)
	public Date getAvpApproveDt() {
		return this.avpApproveDt;
	}

	public void setAvpApproveDt(Date avpApproveDt) {
		this.avpApproveDt = avpApproveDt;
	}

	@Column(name = "AVP_APPROVE_BY", length = 50)
	public String getAvpApproveBy() {
		return this.avpApproveBy;
	}

	public void setAvpApproveBy(String avpApproveBy) {
		this.avpApproveBy = avpApproveBy;
	}

	@Column(name = "AVP_APPROVE_REMARK", length = 1000)
	public String getAvpApproveRemark() {
		return this.avpApproveRemark;
	}

	public void setAvpApproveRemark(String avpApproveRemark) {
		this.avpApproveRemark = avpApproveRemark;
	}

	@Column(name = "FLOW_STATUS", length = 2)
	public String getFlowStatus() {
		return this.flowStatus;
	}

	public void setFlowStatus(String flowStatus) {
		this.flowStatus = flowStatus;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "BATCH_NO", length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BATCH_DT", length = 7)
	public Date getBatchDt() {
		return this.batchDt;
	}

	public void setBatchDt(Date batchDt) {
		this.batchDt = batchDt;
	}

	@Column(name = "LOCATION_EDIT_FLAG", length = 1)
	public String getLocationEditFlag() {
		return this.locationEditFlag;
	}

	public void setLocationEditFlag(String locationEditFlag) {
		this.locationEditFlag = locationEditFlag;
	}

	@Column(name = "CONTRACT_EDIT_FLAG", length = 1)
	public String getContractEditFlag() {
		return this.contractEditFlag;
	}

	public void setContractEditFlag(String contractEditFlag) {
		this.contractEditFlag = contractEditFlag;
	}

	@Column(name = "RENT_EDIT_FLAG", length = 1)
	public String getRentEditFlag() {
		return this.rentEditFlag;
	}

	public void setRentEditFlag(String rentEditFlag) {
		this.rentEditFlag = rentEditFlag;
	}

	@Column(name = "RENT_DEPOSIT_EDIT_FLAG", length = 1)
	public String getRentDepositEditFlag() {
		return this.rentDepositEditFlag;
	}

	public void setRentDepositEditFlag(String rentDepositEditFlag) {
		this.rentDepositEditFlag = rentDepositEditFlag;
	}

	@Column(name = "EL_EDIT_FLAG", length = 1)
	public String getElEditFlag() {
		return this.elEditFlag;
	}

	public void setElEditFlag(String elEditFlag) {
		this.elEditFlag = elEditFlag;
	}

	@Column(name = "EL_DEPOSIT_EDIT_FLAG", length = 1)
	public String getElDepositEditFlag() {
		return this.elDepositEditFlag;
	}

	public void setElDepositEditFlag(String elDepositEditFlag) {
		this.elDepositEditFlag = elDepositEditFlag;
	}

	@Column(name = "PROPERTY_TAX_EDIT_FLAG", length = 1)
	public String getPropertyTaxEditFlag() {
		return this.propertyTaxEditFlag;
	}

	public void setPropertyTaxEditFlag(String propertyTaxEditFlag) {
		this.propertyTaxEditFlag = propertyTaxEditFlag;
	}

	@Column(name = "INSURANCE_EDIT_FLAG", length = 1)
	public String getInsuranceEditFlag() {
		return this.insuranceEditFlag;
	}

	public void setInsuranceEditFlag(String insuranceEditFlag) {
		this.insuranceEditFlag = insuranceEditFlag;
	}

	@Column(name = "MAIL_EDIT_FLAG", length = 1)
	public String getMailEditFlag() {
		return this.mailEditFlag;
	}

	public void setMailEditFlag(String mailEditFlag) {
		this.mailEditFlag = mailEditFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "CO_LOCATE_COMPANY", length = 10)
	public String getCoLocateCompany() {
		return this.coLocateCompany;
	}

	public void setCoLocateCompany(String coLocateCompany) {
		this.coLocateCompany = coLocateCompany;
	}

	@Column(name = "FLOW_BY", length = 50)
	public String getFlowBy() {
		return this.flowBy;
	}

	public void setFlowBy(String flowBy) {
		this.flowBy = flowBy;
	}

	@Column(name = "FLOW_REMARK", length = 1000)
	public String getFlowRemark() {
		return this.flowRemark;
	}

	public void setFlowRemark(String flowRemark) {
		this.flowRemark = flowRemark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FLOW_DT", length = 7)
	public Date getFlowDt() {
		return this.flowDt;
	}

	public void setFlowDt(Date flowDt) {
		this.flowDt = flowDt;
	}

	@Column(name = "UPDATE_LOG", length = 4000)
	public String getUpdateLog() {
		return this.updateLog;
	}

	public void setUpdateLog(String updateLog) {
		this.updateLog = updateLog;
	}

	@Column(name = "ASSIGN_TO_TEAM", length = 50)
	public String getAssignToTeam() {
		return this.assignToTeam;
	}

	public void setAssignToTeam(String assignToTeam) {
		this.assignToTeam = assignToTeam;
	}

}
