package th.co.ais.domain.gm;

// Generated Nov 16, 2010 10:59:16 AM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SsoCompanyUserId generated by hbm2java
 */
@Embeddable
public class SsoCompanyUserId implements java.io.Serializable {

	private String companyCode;
	private String userGroup;

	public SsoCompanyUserId() {
	}

	public SsoCompanyUserId(String companyCode, String userGroup) {
		this.companyCode = companyCode;
		this.userGroup = userGroup;
	}

	@Column(name = "COMPANY_CODE", nullable = false, length = 10)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "USER_GROUP", nullable = false, length = 100)
	public String getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(String userGroup) {
		this.userGroup = userGroup;
	}
}
