package th.co.ais.domain.gm;

// Generated Nov 19, 2010 8:55:20 AM by Hibernate Tools 3.3.0.GA
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.domain.AbstractDomain;
/**
 * SemCtTransPaymentHist generated by hbm2java
 */
@Entity
@Table(name = "SEM_CT_TRANS_PAYMENT_HIST", schema="SEM")
public class TransPaymentHist extends AbstractDomain {

	private static final long serialVersionUID = 3101482477059974457L;
	
	private String rowId;
	private String transPaymentId;
	private String company;
	private String expenseType;
	private Date paymentDt;
	private String paymentBatchNo;
	private String paymentGroupNo;
	private String paymentDocNo;
	private String vendorCode;
	private String payeeName;
	private String payeeAddress;
	private String payeeBankAccNo;
	private String docType;
	private String docNo;
	private Date docDt;
	private String referenceDocType;
	private String referenceDocNo;
	private Integer periodNoStart;
	private Integer periodNoEnd;
	private String periodType;
	private Integer periodInterval;
	private Date periodStartDt;
	private Date periodEndDt;
	private Double periodAmt;
	private String payVatType;
	private Double payVatRate;
	private String payWhtType;
	private Double payWhtRate;
	private Double payExcAmt;
	private Double payVatAmt;
	private Double payIncAmt;
	private Double payWhtAmt;
	private Double payDutyAmt;
	private String paymentType;
	private String paymentMethod;
	private String glAccount;
	private String costCenter;
	private String wbsNo;
	private Date chqDt;
	private String chqNo;
	private Date chqReceiveDt;
	private Date transferDt;
	private String chqClearingStatus;
	private Date chqClearingDt;
	private String approveBy;
	private Date approveDt;
	private String paymentStatus;
	//private String rejectStatus;
	private String reason;
	private String reasonDesc;
	private String remark;
	private String doc68;
	private Date doc68Dt;
	private String doc92;
	private Date doc92Dt;
	private String recordStatus;
	private String sapGroupNo;
	private String sapUpdateFile;
	private Date sapUpdateDt;
	private String doc68Year;
	private String doc92Year;
	private String doc68Linitm;
	private Long version;
		
	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "TRANS_PAYMENT_HIST_ID", unique = true, nullable = false, length = 50)
	public String getRowId() {
		return this.rowId;
	}

	public void setRowId(String rowId) {
		this.rowId = rowId;
	}

	@Version
	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "TRANS_PAYMENT_ID", length = 50)
	public String getTransPaymentId() {
		return this.transPaymentId;
	}

	public void setTransPaymentId(String transPaymentId) {
		this.transPaymentId = transPaymentId;
	}

	@Column(name = "COMPANY", length = 5)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "EXPENSE_TYPE", length = 20)
	public String getExpenseType() {
		return this.expenseType;
	}

	public void setExpenseType(String expenseType) {
		this.expenseType = expenseType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAYMENT_DT", length = 7)
	public Date getPaymentDt() {
		return this.paymentDt;
	}

	public void setPaymentDt(Date paymentDt) {
		this.paymentDt = paymentDt;
	}

	@Column(name = "PAYMENT_BATCH_NO", length = 20)
	public String getPaymentBatchNo() {
		return this.paymentBatchNo;
	}

	public void setPaymentBatchNo(String paymentBatchNo) {
		this.paymentBatchNo = paymentBatchNo;
	}

	@Column(name = "PAYMENT_GROUP_NO", length = 20)
	public String getPaymentGroupNo() {
		return this.paymentGroupNo;
	}

	public void setPaymentGroupNo(String paymentGroupNo) {
		this.paymentGroupNo = paymentGroupNo;
	}

	@Column(name = "PAYMENT_DOC_NO", length = 20)
	public String getPaymentDocNo() {
		return this.paymentDocNo;
	}

	public void setPaymentDocNo(String paymentDocNo) {
		this.paymentDocNo = paymentDocNo;
	}

	@Column(name = "VENDOR_CODE", length = 20)
	public String getVendorCode() {
		return this.vendorCode;
	}

	public void setVendorCode(String vendorCode) {
		this.vendorCode = vendorCode;
	}

	@Column(name = "PAYEE_NAME")
	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	@Column(name = "PAYEE_ADDRESS")
	public String getPayeeAddress() {
		return this.payeeAddress;
	}

	public void setPayeeAddress(String payeeAddress) {
		this.payeeAddress = payeeAddress;
	}

	@Column(name = "PAYEE_BANK_ACC_NO", length = 20)
	public String getPayeeBankAccNo() {
		return this.payeeBankAccNo;
	}

	public void setPayeeBankAccNo(String payeeBankAccNo) {
		this.payeeBankAccNo = payeeBankAccNo;
	}

	@Column(name = "DOC_TYPE", length = 20)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "DOC_NO", length = 20)
	public String getDocNo() {
		return this.docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOC_DT", length = 7)
	public Date getDocDt() {
		return this.docDt;
	}

	public void setDocDt(Date docDt) {
		this.docDt = docDt;
	}

	@Column(name = "REFERENCE_DOC_TYPE", length = 20)
	public String getReferenceDocType() {
		return this.referenceDocType;
	}

	public void setReferenceDocType(String referenceDocType) {
		this.referenceDocType = referenceDocType;
	}

	@Column(name = "REFERENCE_DOC_NO", length = 20)
	public String getReferenceDocNo() {
		return this.referenceDocNo;
	}

	public void setReferenceDocNo(String referenceDocNo) {
		this.referenceDocNo = referenceDocNo;
	}

	@Column(name = "PERIOD_NO_START", precision = 2, scale = 0)
	public Integer getPeriodNoStart() {
		return this.periodNoStart;
	}

	public void setPeriodNoStart(Integer periodNoStart) {
		this.periodNoStart = periodNoStart;
	}

	@Column(name = "PERIOD_NO_END", precision = 2, scale = 0)
	public Integer getPeriodNoEnd() {
		return this.periodNoEnd;
	}

	public void setPeriodNoEnd(Integer periodNoEnd) {
		this.periodNoEnd = periodNoEnd;
	}

	@Column(name = "PERIOD_TYPE", length = 5)
	public String getPeriodType() {
		return this.periodType;
	}

	public void setPeriodType(String periodType) {
		this.periodType = periodType;
	}

	@Column(name = "PERIOD_INTERVAL", precision = 2, scale = 0)
	public Integer getPeriodInterval() {
		return this.periodInterval;
	}

	public void setPeriodInterval(Integer periodInterval) {
		this.periodInterval = periodInterval;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PERIOD_START_DT", length = 7)
	public Date getPeriodStartDt() {
		return this.periodStartDt;
	}

	public void setPeriodStartDt(Date periodStartDt) {
		this.periodStartDt = periodStartDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PERIOD_END_DT", length = 7)
	public Date getPeriodEndDt() {
		return this.periodEndDt;
	}

	public void setPeriodEndDt(Date periodEndDt) {
		this.periodEndDt = periodEndDt;
	}

	@Column(name = "PERIOD_AMT", precision = 15)
	public Double getPeriodAmt() {
		return this.periodAmt;
	}

	public void setPeriodAmt(Double periodAmt) {
		this.periodAmt = periodAmt;
	}

	@Column(name = "PAY_VAT_TYPE", length = 5)
	public String getPayVatType() {
		return this.payVatType;
	}

	public void setPayVatType(String payVatType) {
		this.payVatType = payVatType;
	}

	@Column(name = "PAY_VAT_RATE", precision = 4)
	public Double getPayVatRate() {
		return this.payVatRate;
	}

	public void setPayVatRate(Double payVatRate) {
		this.payVatRate = payVatRate;
	}

	@Column(name = "PAY_WHT_TYPE", length = 5)
	public String getPayWhtType() {
		return this.payWhtType;
	}

	public void setPayWhtType(String payWhtType) {
		this.payWhtType = payWhtType;
	}

	@Column(name = "PAY_WHT_RATE", precision = 4)
	public Double getPayWhtRate() {
		return this.payWhtRate;
	}

	public void setPayWhtRate(Double payWhtRate) {
		this.payWhtRate = payWhtRate;
	}

	@Column(name = "PAY_EXC_AMT", precision = 15)
	public Double getPayExcAmt() {
		return this.payExcAmt;
	}

	public void setPayExcAmt(Double payExcAmt) {
		this.payExcAmt = payExcAmt;
	}

	@Column(name = "PAY_VAT_AMT", precision = 15)
	public Double getPayVatAmt() {
		return this.payVatAmt;
	}

	public void setPayVatAmt(Double payVatAmt) {
		this.payVatAmt = payVatAmt;
	}

	@Column(name = "PAY_INC_AMT", precision = 15)
	public Double getPayIncAmt() {
		return this.payIncAmt;
	}

	public void setPayIncAmt(Double payIncAmt) {
		this.payIncAmt = payIncAmt;
	}

	@Column(name = "PAY_WHT_AMT", precision = 15)
	public Double getPayWhtAmt() {
		return this.payWhtAmt;
	}

	public void setPayWhtAmt(Double payWhtAmt) {
		this.payWhtAmt = payWhtAmt;
	}

	@Column(name = "PAY_DUTY_AMT", precision = 15)
	public Double getPayDutyAmt() {
		return this.payDutyAmt;
	}

	public void setPayDutyAmt(Double payDutyAmt) {
		this.payDutyAmt = payDutyAmt;
	}

	@Column(name = "PAYMENT_TYPE", length = 5)
	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "PAYMENT_METHOD", length = 5)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "GL_ACCOUNT", length = 20)
	public String getGlAccount() {
		return this.glAccount;
	}

	public void setGlAccount(String glAccount) {
		this.glAccount = glAccount;
	}

	@Column(name = "COST_CENTER", length = 20)
	public String getCostCenter() {
		return this.costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	@Column(name = "WBS_NO", length = 20)
	public String getWbsNo() {
		return this.wbsNo;
	}

	public void setWbsNo(String wbsNo) {
		this.wbsNo = wbsNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHQ_DT", length = 7)
	public Date getChqDt() {
		return this.chqDt;
	}

	public void setChqDt(Date chqDt) {
		this.chqDt = chqDt;
	}

	@Column(name = "CHQ_NO", length = 20)
	public String getChqNo() {
		return this.chqNo;
	}

	public void setChqNo(String chqNo) {
		this.chqNo = chqNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHQ_RECEIVE_DT", length = 7)
	public Date getChqReceiveDt() {
		return this.chqReceiveDt;
	}

	public void setChqReceiveDt(Date chqReceiveDt) {
		this.chqReceiveDt = chqReceiveDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TRANSFER_DT", length = 7)
	public Date getTransferDt() {
		return this.transferDt;
	}

	public void setTransferDt(Date transferDt) {
		this.transferDt = transferDt;
	}

	@Column(name = "CHQ_CLEARING_STATUS", length = 5)
	public String getChqClearingStatus() {
		return this.chqClearingStatus;
	}

	public void setChqClearingStatus(String chqClearingStatus) {
		this.chqClearingStatus = chqClearingStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHQ_CLEARING_DT", length = 7)
	public Date getChqClearingDt() {
		return this.chqClearingDt;
	}

	public void setChqClearingDt(Date chqClearingDt) {
		this.chqClearingDt = chqClearingDt;
	}

	@Column(name = "APPROVE_BY", length = 20)
	public String getApproveBy() {
		return this.approveBy;
	}

	public void setApproveBy(String approveBy) {
		this.approveBy = approveBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPROVE_DT", length = 7)
	public Date getApproveDt() {
		return this.approveDt;
	}

	public void setApproveDt(Date approveDt) {
		this.approveDt = approveDt;
	}

	@Column(name = "PAYMENT_STATUS", length = 5)
	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	/*@Column(name = "REJECT_STATUS", length = 5)
	public String getRejectStatus() {
		return this.rejectStatus;
	}

	public void setRejectStatus(String rejectStatus) {
		this.rejectStatus = rejectStatus;
	}*/
	
	@Column(name = "REASON", length = 50)
	public String getReason() {
		return reason;
	}
	public void setReason(String reason) {
		this.reason = reason;
	}
	
	@Column(name = "REASON_DESC", length = 500)
	public String getReasonDesc() {
		return reasonDesc;
	}
	public void setReasonDesc(String reasonDesc) {
		this.reasonDesc = reasonDesc;
	}

	@Column(name = "REMARK", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DOC_68", length = 20)
	public String getDoc68() {
		return this.doc68;
	}

	public void setDoc68(String doc68) {
		this.doc68 = doc68;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOC_68_DT", length = 7)
	public Date getDoc68Dt() {
		return this.doc68Dt;
	}

	public void setDoc68Dt(Date doc68Dt) {
		this.doc68Dt = doc68Dt;
	}

	@Column(name = "DOC_92", length = 20)
	public String getDoc92() {
		return this.doc92;
	}

	public void setDoc92(String doc92) {
		this.doc92 = doc92;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOC_92_DT", length = 7)
	public Date getDoc92Dt() {
		return this.doc92Dt;
	}

	public void setDoc92Dt(Date doc92Dt) {
		this.doc92Dt = doc92Dt;
	}

	@Column(name = "RECORD_STATUS", length = 5)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "SAP_GROUP_NO", length = 2)
	public String getSapGroupNo() {
		return this.sapGroupNo;
	}

	public void setSapGroupNo(String sapGroupNo) {
		this.sapGroupNo = sapGroupNo;
	}

	@Column(name = "SAP_UPDATE_FILE", length = 100)
	public String getSapUpdateFile() {
		return this.sapUpdateFile;
	}

	public void setSapUpdateFile(String sapUpdateFile) {
		this.sapUpdateFile = sapUpdateFile;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SAP_UPDATE_DT", length = 7)
	public Date getSapUpdateDt() {
		return this.sapUpdateDt;
	}

	public void setSapUpdateDt(Date sapUpdateDt) {
		this.sapUpdateDt = sapUpdateDt;
	}

	@Column(name = "DOC_68_YEAR", length = 4)
	public String getDoc68Year() {
		return this.doc68Year;
	}

	public void setDoc68Year(String doc68Year) {
		this.doc68Year = doc68Year;
	}

	@Column(name = "DOC_92_YEAR", length = 4)
	public String getDoc92Year() {
		return this.doc92Year;
	}

	public void setDoc92Year(String doc92Year) {
		this.doc92Year = doc92Year;
	}

	@Column(name = "DOC_68_LINITM", length = 3)
	public String getDoc68Linitm() {
		return this.doc68Linitm;
	}

	public void setDoc68Linitm(String doc68Linitm) {
		this.doc68Linitm = doc68Linitm;
	}

	
	@Override
	@Column(name="CREATE_BY")
	public String getCreateBy() {
		return this.createBy;
	}
	@Override
	@Column(name="CREATE_DT")
	public Date getCreateDt() {
		return this.createDt;
	}

	@Override
	@Column(name="UPDATE_BY")
	public String getUpdateBy() {
		return this.updateBy;
	}

	@Override
	@Column(name="UPDATE_DT")
	public Date getUpdateDt() {
		return this.updateDt;
	}
	
	@Override
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
		
	}

	@Override
	public void setCreateDt(Date createDt) {
		this.createDt = createDt;		
	}

	@Override
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy; 
		
	}

	@Override
	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
		
	}
	
	
	public TransPaymentHist() {
	}

	public TransPaymentHist(String rowId) {
		this.rowId = rowId;
	}

	public TransPaymentHist(String rowId,
			String transPaymentId, String company, String expenseType,
			Date paymentDt, String paymentBatchNo, String paymentGroupNo,
			String paymentDocNo, String vendorCode, String payeeName,
			String payeeAddress, String payeeBankAccNo, String docType,
			String docNo, Date docDt, String referenceDocType,
			String referenceDocNo, Integer periodNoStart, Integer periodNoEnd,
			String periodType, Integer periodInterval, Date periodStartDt,
			Date periodEndDt, Double periodAmt, String payVatType,
			Double payVatRate, String payWhtType, Double payWhtRate,
			Double payExcAmt, Double payVatAmt, Double payIncAmt,
			Double payWhtAmt, Double payDutyAmt, String paymentType,
			String paymentMethod, String glAccount, String costCenter,
			String wbsNo, Date chqDt, String chqNo, Date chqReceiveDt,
			Date transferDt, String chqClearingStatus, Date chqClearingDt,
			String approveBy, Date approveDt, String paymentStatus,
			/*String rejectStatus, */String reason, String reasonDesc,
			String remark, String doc68, Date doc68Dt,
			String doc92, Date doc92Dt, String recordStatus, Date createDt,
			String createBy, Date updateDt, String updateBy, String sapGroupNo,
			String sapUpdateFile, Date sapUpdateDt, String doc68Year,
			String doc92Year, String doc68Linitm) {
		this.rowId = rowId;
		this.transPaymentId = transPaymentId;
		this.company = company;
		this.expenseType = expenseType;
		this.paymentDt = paymentDt;
		this.paymentBatchNo = paymentBatchNo;
		this.paymentGroupNo = paymentGroupNo;
		this.paymentDocNo = paymentDocNo;
		this.vendorCode = vendorCode;
		this.payeeName = payeeName;
		this.payeeAddress = payeeAddress;
		this.payeeBankAccNo = payeeBankAccNo;
		this.docType = docType;
		this.docNo = docNo;
		this.docDt = docDt;
		this.referenceDocType = referenceDocType;
		this.referenceDocNo = referenceDocNo;
		this.periodNoStart = periodNoStart;
		this.periodNoEnd = periodNoEnd;
		this.periodType = periodType;
		this.periodInterval = periodInterval;
		this.periodStartDt = periodStartDt;
		this.periodEndDt = periodEndDt;
		this.periodAmt = periodAmt;
		this.payVatType = payVatType;
		this.payVatRate = payVatRate;
		this.payWhtType = payWhtType;
		this.payWhtRate = payWhtRate;
		this.payExcAmt = payExcAmt;
		this.payVatAmt = payVatAmt;
		this.payIncAmt = payIncAmt;
		this.payWhtAmt = payWhtAmt;
		this.payDutyAmt = payDutyAmt;
		this.paymentType = paymentType;
		this.paymentMethod = paymentMethod;
		this.glAccount = glAccount;
		this.costCenter = costCenter;
		this.wbsNo = wbsNo;
		this.chqDt = chqDt;
		this.chqNo = chqNo;
		this.chqReceiveDt = chqReceiveDt;
		this.transferDt = transferDt;
		this.chqClearingStatus = chqClearingStatus;
		this.chqClearingDt = chqClearingDt;
		this.approveBy = approveBy;
		this.approveDt = approveDt;
		this.paymentStatus = paymentStatus;
		//this.rejectStatus = rejectStatus;
		this.reason = reason;
		this.reasonDesc = reasonDesc;
		this.remark = remark;
		this.doc68 = doc68;
		this.doc68Dt = doc68Dt;
		this.doc92 = doc92;
		this.doc92Dt = doc92Dt;
		this.recordStatus = recordStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
		this.sapGroupNo = sapGroupNo;
		this.sapUpdateFile = sapUpdateFile;
		this.sapUpdateDt = sapUpdateDt;
		this.doc68Year = doc68Year;
		this.doc92Year = doc92Year;
		this.doc68Linitm = doc68Linitm;
	}
	
	public TransPaymentHist(String rowId, TransPayment transPayment) {
		this.rowId = rowId;
		this.transPaymentId = transPayment.getTransPaymentId();
		this.company = transPayment.getCompany();
		this.expenseType = transPayment.getExpenseType();
		this.paymentDt = transPayment.getPaymentDt();
		this.paymentBatchNo = transPayment.getPaymentBatchNo();
		this.paymentGroupNo = transPayment.getPaymentGroupNo();
		this.paymentDocNo = transPayment.getPaymentDocNo();
		this.vendorCode = transPayment.getVendorCode();
		this.payeeName = transPayment.getPayeeName();
		this.payeeAddress = transPayment.getPayeeAddress();
		this.payeeBankAccNo = transPayment.getPayeeBankAccNo();
		this.docType = transPayment.getDocType();
		this.docNo = transPayment.getDocNo();
		this.docDt = transPayment.getDocDt();
		this.referenceDocType = transPayment.getReferenceDocType();
		this.referenceDocNo = transPayment.getReferenceDocNo();
		this.periodNoStart = transPayment.getPeriodNoStart();
		this.periodNoEnd = transPayment.getPeriodNoEnd();
		this.periodType = transPayment.getPeriodType();
		this.periodInterval = transPayment.getPeriodInterval();
		this.periodStartDt = transPayment.getPeriodStartDt();
		this.periodEndDt = transPayment.getPeriodEndDt();
		this.periodAmt = transPayment.getPeriodAmt();
		this.payVatType = transPayment.getPayVatType();
		this.payVatRate = transPayment.getPayVatRate();
		this.payWhtType = transPayment.getPayWhtType();
		this.payWhtRate = transPayment.getPayWhtRate();
		this.payExcAmt = transPayment.getPayExcAmt();
		this.payVatAmt = transPayment.getPayVatAmt();
		this.payIncAmt = transPayment.getPayIncAmt();
		this.payWhtAmt = transPayment.getPayWhtAmt();
		this.payDutyAmt = transPayment.getPayDutyAmt();
		this.paymentType = transPayment.getPaymentType();
		this.paymentMethod = transPayment.getPaymentMethod();
		this.glAccount = transPayment.getGlAccount();
		this.costCenter = transPayment.getCostCenter();
		this.wbsNo = transPayment.getWbsNo();
		this.chqDt = transPayment.getChqDt();
		this.chqNo = transPayment.getChqNo();
		this.chqReceiveDt = transPayment.getChqReceiveDt();
		this.transferDt = transPayment.getTransferDt();
		this.chqClearingStatus = transPayment.getChqClearingStatus();
		this.chqClearingDt = transPayment.getChqClearingDt();
		this.approveBy = transPayment.getApproveBy();
		this.approveDt = transPayment.getApproveDt();
		this.paymentStatus = transPayment.getPaymentStatus();
		//this.rejectStatus = transPayment.getRejectStatus();
		this.reason = transPayment.getReason();
		this.reasonDesc = transPayment.getReasonDesc();
		this.remark = transPayment.getRemark();
		this.doc68 = transPayment.getDoc68();
		this.doc68Dt = transPayment.getDoc68Dt();
		this.doc92 = transPayment.getDoc92();
		this.doc92Dt = transPayment.getDoc92Dt();
		this.recordStatus = transPayment.getRecordStatus();
		this.createDt = transPayment.getCreateDt();
		this.createBy = transPayment.getCreateBy();
		this.updateDt = transPayment.getUpdateDt();
		this.updateBy = transPayment.getUpdateBy();
		this.sapGroupNo = transPayment.getSapGroupNo();
		this.sapUpdateFile = transPayment.getSapUpdateFile();
		this.sapUpdateDt = transPayment.getSapUpdateDt();
		this.doc68Year = transPayment.getDoc68Year();
		this.doc92Year = transPayment.getDoc92Year();
		this.doc68Linitm = transPayment.getDoc68Linitm();
	}

}
