package th.co.ais.domain.ir;

// Generated Aug 15, 2011 5:52:24 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.domain.AbstractDomain;
import th.co.ais.rpt.util.DataUtil;

/**
 * SemIrClaimDetail generated by hbm2java
 */
@Entity
@Table(name = "SEM_IR_CLAIM_DETAIL", schema = "SEM")
public class IrClaimDetail extends AbstractDomain {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2830097024485062350L;
	private String rowId;
	private IrClaim irClaim;
	private String claimAsset;
	private BigDecimal claimAmt;
	private String claimAmtStr;
	private String serialNo;
	private String articleNo;
	private String recordStatus;
	private Long version;
	private String remark;

	public IrClaimDetail() {
	}

	public IrClaimDetail(String rowId) {
		this.rowId = rowId;
	}

	public IrClaimDetail(IrClaimDetail irClaimDetail) {
		super();
		this.rowId = irClaimDetail.getRowId();
		this.irClaim = irClaimDetail.getIrClaim();
		this.claimAsset = irClaimDetail.getClaimAsset();
		this.claimAmt = irClaimDetail.getClaimAmt();
		this.serialNo = irClaimDetail.getSerialNo();
		this.articleNo = irClaimDetail.getArticleNo();
		this.recordStatus = irClaimDetail.getRecordStatus();
		this.version = irClaimDetail.getVersion();
		this.remark = irClaimDetail.getRemark();
		this.createBy = irClaimDetail.getCreateBy();
		this.createDt = irClaimDetail.getCreateDt();
		this.updateBy = irClaimDetail.getUpdateBy();
		this.updateDt = irClaimDetail.getUpdateDt();
		this.currentUser = irClaimDetail.getCurrentUser();
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "CLAIM_DETAIL_ID", unique = true, nullable = false, length = 50)
	public String getRowId() {
		return rowId;
	}

	public void setRowId(String rowId) {
		this.rowId = rowId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLAIM_ID", nullable = false)
	public IrClaim getIrClaim() {
		return irClaim;
	}

	public void setIrClaim(IrClaim irClaim) {
		this.irClaim = irClaim;
	}

	@Column(name = "CLAIM_ASSET")
	public String getClaimAsset() {
		return this.claimAsset;
	}

	public void setClaimAsset(String claimAsset) {
		this.claimAsset = claimAsset;
	}

	@Column(name = "CLAIM_AMT", precision = 15)
	public BigDecimal getClaimAmt() {
		return this.claimAmt;
	}

	public void setClaimAmt(BigDecimal claimAmt) {
		this.claimAmt = claimAmt;
	}
	@Transient
	public String getClaimAmtStr() {
		return DataUtil.setFormatDecmal(getClaimAmt());
	}

	public void setClaimAmtStr(String claimAmtStr) {
		this.claimAmtStr = claimAmtStr;
	}

	@Column(name = "SERIAL_NO")
	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "ARTICLE_NO")
	public String getArticleNo() {
		return this.articleNo;
	}

	public void setArticleNo(String articleNo) {
		this.articleNo = articleNo;
	}

	@Column(name = "RECORD_STATUS", length = 5)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Version
	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "REMARK", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
