package th.co.ais.domain.ir;

// Generated Aug 15, 2011 5:52:24 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.domain.AbstractDomain;
import th.co.ais.rpt.util.DataUtil;

/**
 * SemIrClaim generated by hbm2java
 */
@Entity
@Table(name = "SEM_IR_CLAIM", schema = "SEM")
public class IrClaim extends AbstractDomain {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6808033669966219378L;
	private String rowId;
	private String claimNo;
	private Date claimDt;
	private String reqBy;
	private String reqDepBy;
	private String reqTel;
	private String reqEmail;
	private String locationId;
	private String locationName;
	private String lossPlaceName;
	private String sameLocationFlg;
	private String lossProvinceId;
	private String lossRegion;
	private String transferType;
	private String lossAddress;
	private Date lossDt;
	private String lossTime;
	private String lossType;
	private String lossSubType;
	private String lossDesc;
	private BigDecimal estimateAmt;
	private String estimateAmtStr;
	private String preAct;
	private String litigantFlg;
	private String litigantName;
	private String litigantAddress;
	private String litigantTel;
	private String doc01;
	private String doc02;
	private String doc03;
	private String doc04;
	private String doc05;
	private String doc05Desc;
	private String claimStatus;
	private String remark;
	private Long version;
	private String recordStatus;
	private List<IrClaimDetail> irClaimDetails;
	private String locationCode;
	private String contractNo;
	
	// Transient
	private boolean locationFlg;
	private String estimateAmtDesc;
	private boolean doc01Flg;
	private boolean doc02Flg;
	private boolean doc03Flg;
	private boolean doc04Flg;
	private boolean doc05Flg;
	private String provinceName;
	private String TransferTypeDesc;
	private String lossTypeDesc;
	private String lossSubTypeDesc;
	private String lossDetailDesc;
	private String claimStatusDescl;
	
	
	
	public IrClaim() {
	}

	public IrClaim(String rowId) {
		this.rowId = rowId;
	}

	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "CLAIM_ID", unique = true, nullable = false, length = 50)
	public String getRowId() {
		return rowId;
	}

	public void setRowId(String rowId) {
		this.rowId = rowId;
	}

	@Column(name = "CLAIM_NO", length = 50)
	public String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(String claimNo) {
		this.claimNo = claimNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CLAIM_DT", length = 7)
	public Date getClaimDt() {
		return this.claimDt;
	}

	public void setClaimDt(Date claimDt) {
		this.claimDt = claimDt;
	}

	@Column(name = "REQ_BY", length = 50)
	public String getReqBy() {
		return this.reqBy;
	}

	public void setReqBy(String reqBy) {
		this.reqBy = reqBy;
	}

	@Column(name = "REQ_DEP_BY")
	public String getReqDepBy() {
		return this.reqDepBy;
	}

	public void setReqDepBy(String reqDepBy) {
		this.reqDepBy = reqDepBy;
	}

	@Column(name = "REQ_TEL", length = 50)
	public String getReqTel() {
		return this.reqTel;
	}

	public void setReqTel(String reqTel) {
		this.reqTel = reqTel;
	}

	@Column(name = "REQ_EMAIL", length = 50)
	public String getReqEmail() {
		return this.reqEmail;
	}

	public void setReqEmail(String reqEmail) {
		this.reqEmail = reqEmail;
	}

	@Column(name = "LOCATION_ID", length = 50)
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "LOCATION_NAME")
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "LOSS_PLACE_NAME")
	public String getLossPlaceName() {
		return this.lossPlaceName;
	}

	public void setLossPlaceName(String lossPlaceName) {
		this.lossPlaceName = lossPlaceName;
	}

	@Column(name = "SAME_LOCATION_FLG", length = 5)
	public String getSameLocationFlg() {
		return this.sameLocationFlg;
	}

	public void setSameLocationFlg(String sameLocationFlg) {
		this.sameLocationFlg = sameLocationFlg;
	}

	@Column(name = "LOSS_PROVINCE_ID", length = 10)
	public String getLossProvinceId() {
		return this.lossProvinceId;
	}

	public void setLossProvinceId(String lossProvinceId) {
		this.lossProvinceId = lossProvinceId;
	}

	@Column(name = "LOSS_REGION", length = 10)
	public String getLossRegion() {
		return this.lossRegion;
	}

	public void setLossRegion(String lossRegion) {
		this.lossRegion = lossRegion;
	}

	@Column(name = "TRANSFER_TYPE", length = 5)
	public String getTransferType() {
		return this.transferType;
	}

	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

	@Column(name = "LOSS_ADDRESS")
	public String getLossAddress() {
		return this.lossAddress;
	}

	public void setLossAddress(String lossAddress) {
		this.lossAddress = lossAddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOSS_DT", length = 7)
	public Date getLossDt() {
		return this.lossDt;
	}

	public void setLossDt(Date lossDt) {
		this.lossDt = lossDt;
	}

	@Column(name = "LOSS_TIME", length = 10)
	public String getLossTime() {
		return this.lossTime;
	}

	public void setLossTime(String lossTime) {
		this.lossTime = lossTime;
	}

	@Column(name = "LOSS_TYPE", length = 5)
	public String getLossType() {
		return this.lossType;
	}

	public void setLossType(String lossType) {
		this.lossType = lossType;
	}

	@Column(name = "LOSS_SUB_TYPE", length = 5)
	public String getLossSubType() {
		return this.lossSubType;
	}

	public void setLossSubType(String lossSubType) {
		this.lossSubType = lossSubType;
	}

	@Column(name = "LOSS_DESC")
	public String getLossDesc() {
		return this.lossDesc;
	}

	public void setLossDesc(String lossDesc) {
		this.lossDesc = lossDesc;
	}

	@Column(name = "ESTIMATE_AMT", precision = 15)
	public BigDecimal getEstimateAmt() {
		return this.estimateAmt;
	}

	public void setEstimateAmt(BigDecimal estimateAmt) {
		this.estimateAmt = estimateAmt;
	}
	@Transient
	public String getEstimateAmtStr() {
		return DataUtil.setFormatDecmal(getEstimateAmt());
	}

	public void setEstimateAmtStr(String estimateAmtStr) {
		this.estimateAmtStr = estimateAmtStr;
	}

	@Column(name = "PRE_ACT")
	public String getPreAct() {
		return this.preAct;
	}

	public void setPreAct(String preAct) {
		this.preAct = preAct;
	}

	@Column(name = "LITIGANT_FLG", length = 5)
	public String getLitigantFlg() {
		return this.litigantFlg;
	}

	public void setLitigantFlg(String litigantFlg) {
		this.litigantFlg = litigantFlg;
	}

	@Column(name = "LITIGANT_NAME")
	public String getLitigantName() {
		return this.litigantName;
	}

	public void setLitigantName(String litigantName) {
		this.litigantName = litigantName;
	}

	@Column(name = "LITIGANT_ADDRESS")
	public String getLitigantAddress() {
		return this.litigantAddress;
	}

	public void setLitigantAddress(String litigantAddress) {
		this.litigantAddress = litigantAddress;
	}

	@Column(name = "LITIGANT_TEL", length = 50)
	public String getLitigantTel() {
		return this.litigantTel;
	}

	public void setLitigantTel(String litigantTel) {
		this.litigantTel = litigantTel;
	}

	@Column(name = "DOC_01", length = 5)
	public String getDoc01() {
		return this.doc01;
	}

	public void setDoc01(String doc01) {
		this.doc01 = doc01;
	}

	@Column(name = "DOC_02", length = 5)
	public String getDoc02() {
		return this.doc02;
	}

	public void setDoc02(String doc02) {
		this.doc02 = doc02;
	}

	@Column(name = "DOC_03", length = 5)
	public String getDoc03() {
		return this.doc03;
	}

	public void setDoc03(String doc03) {
		this.doc03 = doc03;
	}

	@Column(name = "DOC_04", length = 5)
	public String getDoc04() {
		return this.doc04;
	}

	public void setDoc04(String doc04) {
		this.doc04 = doc04;
	}

	@Column(name = "DOC_05", length = 5)
	public String getDoc05() {
		return this.doc05;
	}

	public void setDoc05(String doc05) {
		this.doc05 = doc05;
	}

	@Column(name = "DOC_05_DESC")
	public String getDoc05Desc() {
		return this.doc05Desc;
	}

	public void setDoc05Desc(String doc05Desc) {
		this.doc05Desc = doc05Desc;
	}

	@Column(name = "CLAIM_STATUS", length = 5)
	public String getClaimStatus() {
		return this.claimStatus;
	}

	public void setClaimStatus(String claimStatus) {
		this.claimStatus = claimStatus;
	}

	@Column(name = "REMARK", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "RECORD_STATUS", length = 5)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Version
	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "irClaim")
	public List<IrClaimDetail> getIrClaimDetails() {
		return irClaimDetails;
	}

	public void setIrClaimDetails(List<IrClaimDetail> irClaimDetails) {
		this.irClaimDetails = irClaimDetails;
	}

	@Column(name = "LOCATION_CODE", length = 20)
	public String getLocationCode() {
		return locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}
	
	@Transient
	public boolean isLocationFlg() {
		return locationFlg;
	}

	public void setLocationFlg(boolean locationFlg) {
		this.locationFlg = locationFlg;
	}

	@Transient
	public String getEstimateAmtDesc() {
		return estimateAmtDesc;
	}

	public void setEstimateAmtDesc(String estimateAmtDesc) {
		this.estimateAmtDesc = estimateAmtDesc;
	}

	@Transient
	public boolean isDoc01Flg() {
		return doc01Flg;
	}

	public void setDoc01Flg(boolean doc01Flg) {
		this.doc01Flg = doc01Flg;
	}

	@Transient
	public boolean isDoc02Flg() {
		return doc02Flg;
	}

	public void setDoc02Flg(boolean doc02Flg) {
		this.doc02Flg = doc02Flg;
	}

	@Transient
	public boolean isDoc03Flg() {
		return doc03Flg;
	}

	public void setDoc03Flg(boolean doc03Flg) {
		this.doc03Flg = doc03Flg;
	}

	@Transient
	public boolean isDoc04Flg() {
		return doc04Flg;
	}

	public void setDoc04Flg(boolean doc04Flg) {
		this.doc04Flg = doc04Flg;
	}

	@Transient
	public boolean isDoc05Flg() {
		return doc05Flg;
	}

	public void setDoc05Flg(boolean doc05Flg) {
		this.doc05Flg = doc05Flg;
	}

	@Transient
	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Transient
	public String getTransferTypeDesc() {
		return TransferTypeDesc;
	}

	public void setTransferTypeDesc(String transferTypeDesc) {
		TransferTypeDesc = transferTypeDesc;
	}

	@Transient
	public String getLossTypeDesc() {
		return lossTypeDesc;
	}

	public void setLossTypeDesc(String lossTypeDesc) {
		this.lossTypeDesc = lossTypeDesc;
	}

	@Transient
	public String getLossSubTypeDesc() {
		return lossSubTypeDesc;
	}

	public void setLossSubTypeDesc(String lossSubTypeDesc) {
		this.lossSubTypeDesc = lossSubTypeDesc;
	}

	@Transient
	public String getLossDetailDesc() {
		return lossDetailDesc;
	}

	public void setLossDetailDesc(String lossDetailDesc) {
		this.lossDetailDesc = lossDetailDesc;
	}

	@Transient
	public String getClaimStatusDescl() {
		return claimStatusDescl;
	}

	public void setClaimStatusDescl(String claimStatusDescl) {
		this.claimStatusDescl = claimStatusDescl;
	}
	
	@Column(name = "CONTRACT_NO", length = 50)
	public String getContractNo() {
		return contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

}
