package com.ais.migrate.sem.hibernate.annotion;

// Generated Dec 13, 2010 4:40:15 PM by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MigrateSapmo generated by hbm2java
 */
@Entity
@Table(name = "MIGRATE_SAPMO", schema="SEM")
public class MigrateSapmo implements Serializable {

	private static final long serialVersionUID = 8914559562910065937L;
	
	private Integer no;
	private String flghea;
	private String comcod;
	private String conno;
	private Integer subcon;
	private String contyp;
	private String locid;
	private String doctyp;
	private String refdoc;
	private String dochea;
	private String docdat;
	private String posdat;
	private String bracod;
	private String curcod;
	private Double excrat;
	private String vencod;
	private Double venamt;
	private String invdoc;
	private String invyea;
	private String paydoc;
	private String payyea;
	private String paydat;
	private String chqno;

	private String filename;
	private String createdate;
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "MIGRATE_SAPMO_SEQ")
	@SequenceGenerator(name="MIGRATE_SAPMO_SEQ", sequenceName = "MIGRATE_SAPMO_SEQ")
	@Column(name = "NO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@Column(name = "FLGHEA", length = 1)
	public String getFlghea() {
		return this.flghea;
	}

	public void setFlghea(String flghea) {
		this.flghea = flghea;
	}

	@Column(name = "COMCOD", length = 4)
	public String getComcod() {
		return this.comcod;
	}

	public void setComcod(String comcod) {
		this.comcod = comcod;
	}

	@Column(name = "CONNO", length = 10)
	public String getConno() {
		return this.conno;
	}

	public void setConno(String conno) {
		this.conno = conno;
	}

	@Column(name = "SUBCON", precision = 22, scale = 0)
	public Integer getSubcon() {
		return this.subcon;
	}

	public void setSubcon(Integer subcon) {
		this.subcon = subcon;
	}

	@Column(name = "CONTYP", length = 2)
	public String getContyp() {
		return this.contyp;
	}

	public void setContyp(String contyp) {
		this.contyp = contyp;
	}

	@Column(name = "LOCID", length = 10)
	public String getLocid() {
		return this.locid;
	}

	public void setLocid(String locid) {
		this.locid = locid;
	}

	@Column(name = "DOCTYP", length = 2)
	public String getDoctyp() {
		return this.doctyp;
	}

	public void setDoctyp(String doctyp) {
		this.doctyp = doctyp;
	}

	@Column(name = "REFDOC", length = 16)
	public String getRefdoc() {
		return this.refdoc;
	}

	public void setRefdoc(String refdoc) {
		this.refdoc = refdoc;
	}

	@Column(name = "DOCHEA", length = 25)
	public String getDochea() {
		return this.dochea;
	}

	public void setDochea(String dochea) {
		this.dochea = dochea;
	}

	@Column(name = "DOCDAT", length = 8)
	public String getDocdat() {
		return this.docdat;
	}

	public void setDocdat(String docdat) {
		this.docdat = docdat;
	}

	@Column(name = "POSDAT", length = 8)
	public String getPosdat() {
		return this.posdat;
	}

	public void setPosdat(String posdat) {
		this.posdat = posdat;
	}

	@Column(name = "BRACOD", length = 4)
	public String getBracod() {
		return this.bracod;
	}

	public void setBracod(String bracod) {
		this.bracod = bracod;
	}

	@Column(name = "CURCOD", length = 5)
	public String getCurcod() {
		return this.curcod;
	}

	public void setCurcod(String curcod) {
		this.curcod = curcod;
	}

	@Column(name = "EXCRAT", precision = 9, scale = 5)
	public Double getExcrat() {
		return this.excrat;
	}

	public void setExcrat(Double excrat) {
		this.excrat = excrat;
	}

	@Column(name = "VENCOD", length = 10)
	public String getVencod() {
		return this.vencod;
	}

	public void setVencod(String vencod) {
		this.vencod = vencod;
	}

	@Column(name = "VENAMT", precision = 13)
	public Double getVenamt() {
		return this.venamt;
	}

	public void setVenamt(Double venamt) {
		this.venamt = venamt;
	}

	@Column(name = "INVDOC", length = 10)
	public String getInvdoc() {
		return this.invdoc;
	}

	public void setInvdoc(String invdoc) {
		this.invdoc = invdoc;
	}

	@Column(name = "INVYEA", length = 4)
	public String getInvyea() {
		return this.invyea;
	}

	public void setInvyea(String invyea) {
		this.invyea = invyea;
	}

	@Column(name = "PAYDOC", length = 10)
	public String getPaydoc() {
		return this.paydoc;
	}

	public void setPaydoc(String paydoc) {
		this.paydoc = paydoc;
	}

	@Column(name = "PAYYEA", length = 4)
	public String getPayyea() {
		return this.payyea;
	}

	public void setPayyea(String payyea) {
		this.payyea = payyea;
	}

	@Column(name = "PAYDAT", length = 8)
	public String getPaydat() {
		return this.paydat;
	}

	public void setPaydat(String paydat) {
		this.paydat = paydat;
	}

	@Column(name = "CHQNO", length = 8)
	public String getChqno() {
		return this.chqno;
	}

	public void setChqno(String chqno) {
		this.chqno = chqno;
	}

	@Column(name = "FILENAME", length = 100)
	 public String getFilename() {
	  return this.filename;
	 }

	 public void setFilename(String filename) {
	  this.filename = filename;
	 }

	 @Column(name = "CREATEDATE", length = 8)
	 public String getCreatedate() {
	  return this.createdate;
	 }

	 public void setCreatedate(String createdate) {
	  this.createdate = createdate;
	 }
}
