package com.ais.migrate.sem.hibernate.annotion;

// Generated Dec 15, 2010 12:20:41 PM by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MigrateSapv1 generated by hbm2java
 */
@Entity
@Table(name = "MIGRATE_SAPV1", schema="SEM")
public class MigrateSapv1 implements Serializable {

	private static final long serialVersionUID = 117196177110446381L;
	
	private Integer no;
	private String status;
	private String vencod;
	private String datsta;
	private String usrsta;
	private String comcod;
	private String oneflg;
	private String accgro;
	private String vennam1;
	private String vennam2;
	private String vennam3;
	private String vennam4;
	private String seater;
	private String street;
	private String distri;
	private String city01;
	private String poscod;
	private String countr;
	private String region;
	private String telpho1;
	private String telpho2;
	private String mobileno;
	private String faxno;
	private String email;
	private String datcom;
	private String telbox;
	private String commen;
	private String cuscod;
	private String trapar;
	private String perid;
	private String taxid;
	private String indkey;
	private String bnkkey1;
	private String bnknam1;
	private String bnkacc1;
	private String acchod1;
	private String parbnk1;
	private String bnkkey2;
	private String bnknam2;
	private String bnkacc2;
	private String acchod2;
	private String parbnk2;
	private String recacc;
	private String heaacc;
	private String preacc;
	private String payter;
	private String paymet;
	private String payblk;
	private String accclk;
	private String wittype1;
	private String witcode1;
	private String rectype1;
	private String wittype2;
	private String witcode2;
	private String rectype2;
	private String wittype3;
	private String witcode3;
	private String rectype3;

	private String filename;
	private String createdate;
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator = "MIGRATE_SAPV1_SEQ")
	@SequenceGenerator(name="MIGRATE_SAPV1_SEQ", sequenceName = "MIGRATE_SAPV1_SEQ")
	@Column(name = "NO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@Column(name = "STATUS", length = 3)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "VENCOD", length = 10)
	public String getVencod() {
		return this.vencod;
	}

	public void setVencod(String vencod) {
		this.vencod = vencod;
	}

	@Column(name = "DATSTA", length = 8)
	public String getDatsta() {
		return this.datsta;
	}

	public void setDatsta(String datsta) {
		this.datsta = datsta;
	}

	@Column(name = "USRSTA", length = 12)
	public String getUsrsta() {
		return this.usrsta;
	}

	public void setUsrsta(String usrsta) {
		this.usrsta = usrsta;
	}

	@Column(name = "COMCOD", length = 4)
	public String getComcod() {
		return this.comcod;
	}

	public void setComcod(String comcod) {
		this.comcod = comcod;
	}

	@Column(name = "ONEFLG", length = 1)
	public String getOneflg() {
		return this.oneflg;
	}

	public void setOneflg(String oneflg) {
		this.oneflg = oneflg;
	}

	@Column(name = "ACCGRO", length = 4)
	public String getAccgro() {
		return this.accgro;
	}

	public void setAccgro(String accgro) {
		this.accgro = accgro;
	}

	@Column(name = "VENNAM1", length = 35)
	public String getVennam1() {
		return this.vennam1;
	}

	public void setVennam1(String vennam1) {
		this.vennam1 = vennam1;
	}

	@Column(name = "VENNAM2", length = 35)
	public String getVennam2() {
		return this.vennam2;
	}

	public void setVennam2(String vennam2) {
		this.vennam2 = vennam2;
	}

	@Column(name = "VENNAM3", length = 35)
	public String getVennam3() {
		return this.vennam3;
	}

	public void setVennam3(String vennam3) {
		this.vennam3 = vennam3;
	}

	@Column(name = "VENNAM4", length = 35)
	public String getVennam4() {
		return this.vennam4;
	}

	public void setVennam4(String vennam4) {
		this.vennam4 = vennam4;
	}

	@Column(name = "SEATER", length = 10)
	public String getSeater() {
		return this.seater;
	}

	public void setSeater(String seater) {
		this.seater = seater;
	}

	@Column(name = "STREET", length = 35)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "DISTRI", length = 35)
	public String getDistri() {
		return this.distri;
	}

	public void setDistri(String distri) {
		this.distri = distri;
	}

	@Column(name = "CITY01", length = 35)
	public String getCity01() {
		return this.city01;
	}

	public void setCity01(String city01) {
		this.city01 = city01;
	}

	@Column(name = "POSCOD", length = 10)
	public String getPoscod() {
		return this.poscod;
	}

	public void setPoscod(String poscod) {
		this.poscod = poscod;
	}

	@Column(name = "COUNTR", length = 3)
	public String getCountr() {
		return this.countr;
	}

	public void setCountr(String countr) {
		this.countr = countr;
	}

	@Column(name = "REGION", length = 3)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "TELPHO1", length = 16)
	public String getTelpho1() {
		return this.telpho1;
	}

	public void setTelpho1(String telpho1) {
		this.telpho1 = telpho1;
	}

	@Column(name = "TELPHO2", length = 16)
	public String getTelpho2() {
		return this.telpho2;
	}

	public void setTelpho2(String telpho2) {
		this.telpho2 = telpho2;
	}

	@Column(name = "MOBILENO", length = 16)
	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	@Column(name = "FAXNO", length = 30)
	public String getFaxno() {
		return this.faxno;
	}

	public void setFaxno(String faxno) {
		this.faxno = faxno;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DATCOM", length = 40)
	public String getDatcom() {
		return this.datcom;
	}

	public void setDatcom(String datcom) {
		this.datcom = datcom;
	}

	@Column(name = "TELBOX", length = 40)
	public String getTelbox() {
		return this.telbox;
	}

	public void setTelbox(String telbox) {
		this.telbox = telbox;
	}

	@Column(name = "COMMEN", length = 50)
	public String getCommen() {
		return this.commen;
	}

	public void setCommen(String commen) {
		this.commen = commen;
	}

	@Column(name = "CUSCOD", length = 10)
	public String getCuscod() {
		return this.cuscod;
	}

	public void setCuscod(String cuscod) {
		this.cuscod = cuscod;
	}

	@Column(name = "TRAPAR", length = 6)
	public String getTrapar() {
		return this.trapar;
	}

	public void setTrapar(String trapar) {
		this.trapar = trapar;
	}

	@Column(name = "PERID", length = 13)
	public String getPerid() {
		return this.perid;
	}

	public void setPerid(String perid) {
		this.perid = perid;
	}

	@Column(name = "TAXID", length = 10)
	public String getTaxid() {
		return this.taxid;
	}

	public void setTaxid(String taxid) {
		this.taxid = taxid;
	}

	@Column(name = "INDKEY", length = 4)
	public String getIndkey() {
		return this.indkey;
	}

	public void setIndkey(String indkey) {
		this.indkey = indkey;
	}

	@Column(name = "BNKKEY1", length = 7)
	public String getBnkkey1() {
		return this.bnkkey1;
	}

	public void setBnkkey1(String bnkkey1) {
		this.bnkkey1 = bnkkey1;
	}

	@Column(name = "BNKNAM1", length = 60)
	public String getBnknam1() {
		return this.bnknam1;
	}

	public void setBnknam1(String bnknam1) {
		this.bnknam1 = bnknam1;
	}

	@Column(name = "BNKACC1", length = 18)
	public String getBnkacc1() {
		return this.bnkacc1;
	}

	public void setBnkacc1(String bnkacc1) {
		this.bnkacc1 = bnkacc1;
	}

	@Column(name = "ACCHOD1", length = 60)
	public String getAcchod1() {
		return this.acchod1;
	}

	public void setAcchod1(String acchod1) {
		this.acchod1 = acchod1;
	}

	@Column(name = "PARBNK1", length = 4)
	public String getParbnk1() {
		return this.parbnk1;
	}

	public void setParbnk1(String parbnk1) {
		this.parbnk1 = parbnk1;
	}

	@Column(name = "BNKKEY2", length = 7)
	public String getBnkkey2() {
		return this.bnkkey2;
	}

	public void setBnkkey2(String bnkkey2) {
		this.bnkkey2 = bnkkey2;
	}

	@Column(name = "BNKNAM2", length = 60)
	public String getBnknam2() {
		return this.bnknam2;
	}

	public void setBnknam2(String bnknam2) {
		this.bnknam2 = bnknam2;
	}

	@Column(name = "BNKACC2", length = 18)
	public String getBnkacc2() {
		return this.bnkacc2;
	}

	public void setBnkacc2(String bnkacc2) {
		this.bnkacc2 = bnkacc2;
	}

	@Column(name = "ACCHOD2", length = 60)
	public String getAcchod2() {
		return this.acchod2;
	}

	public void setAcchod2(String acchod2) {
		this.acchod2 = acchod2;
	}

	@Column(name = "PARBNK2", length = 4)
	public String getParbnk2() {
		return this.parbnk2;
	}

	public void setParbnk2(String parbnk2) {
		this.parbnk2 = parbnk2;
	}

	@Column(name = "RECACC", length = 10)
	public String getRecacc() {
		return this.recacc;
	}

	public void setRecacc(String recacc) {
		this.recacc = recacc;
	}

	@Column(name = "HEAACC", length = 10)
	public String getHeaacc() {
		return this.heaacc;
	}

	public void setHeaacc(String heaacc) {
		this.heaacc = heaacc;
	}

	@Column(name = "PREACC", length = 10)
	public String getPreacc() {
		return this.preacc;
	}

	public void setPreacc(String preacc) {
		this.preacc = preacc;
	}

	@Column(name = "PAYTER", length = 4)
	public String getPayter() {
		return this.payter;
	}

	public void setPayter(String payter) {
		this.payter = payter;
	}

	@Column(name = "PAYMET", length = 10)
	public String getPaymet() {
		return this.paymet;
	}

	public void setPaymet(String paymet) {
		this.paymet = paymet;
	}

	@Column(name = "PAYBLK", length = 1)
	public String getPayblk() {
		return this.payblk;
	}

	public void setPayblk(String payblk) {
		this.payblk = payblk;
	}

	@Column(name = "ACCCLK", length = 2)
	public String getAccclk() {
		return this.accclk;
	}

	public void setAccclk(String accclk) {
		this.accclk = accclk;
	}

	@Column(name = "WITTYPE1", length = 2)
	public String getWittype1() {
		return this.wittype1;
	}

	public void setWittype1(String wittype1) {
		this.wittype1 = wittype1;
	}

	@Column(name = "WITCODE1", length = 2)
	public String getWitcode1() {
		return this.witcode1;
	}

	public void setWitcode1(String witcode1) {
		this.witcode1 = witcode1;
	}

	@Column(name = "RECTYPE1", length = 2)
	public String getRectype1() {
		return this.rectype1;
	}

	public void setRectype1(String rectype1) {
		this.rectype1 = rectype1;
	}

	@Column(name = "WITTYPE2", length = 2)
	public String getWittype2() {
		return this.wittype2;
	}

	public void setWittype2(String wittype2) {
		this.wittype2 = wittype2;
	}

	@Column(name = "WITCODE2", length = 2)
	public String getWitcode2() {
		return this.witcode2;
	}

	public void setWitcode2(String witcode2) {
		this.witcode2 = witcode2;
	}

	@Column(name = "RECTYPE2", length = 2)
	public String getRectype2() {
		return this.rectype2;
	}

	public void setRectype2(String rectype2) {
		this.rectype2 = rectype2;
	}

	@Column(name = "WITTYPE3", length = 2)
	public String getWittype3() {
		return this.wittype3;
	}

	public void setWittype3(String wittype3) {
		this.wittype3 = wittype3;
	}

	@Column(name = "WITCODE3", length = 2)
	public String getWitcode3() {
		return this.witcode3;
	}

	public void setWitcode3(String witcode3) {
		this.witcode3 = witcode3;
	}

	@Column(name = "RECTYPE3", length = 2)
	public String getRectype3() {
		return this.rectype3;
	}

	public void setRectype3(String rectype3) {
		this.rectype3 = rectype3;
	}
	
	@Column(name = "FILENAME", length = 100)
	 public String getFilename() {
	  return this.filename;
	 }

	 public void setFilename(String filename) {
	  this.filename = filename;
	 }

	 @Column(name = "CREATEDATE", length = 8)
	 public String getCreatedate() {
	  return this.createdate;
	 }

	 public void setCreatedate(String createdate) {
	  this.createdate = createdate;
	 }
}
