package com.ais.migrate.sem.hibernate.annotion;
// default package
// Generated 9 มี.ค. 2554, 10:00:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MpContractClean generated by hbm2java
 */
@Entity
@Table(name = "MP_CONTRACT_CLEAN")
public class MpContractClean implements java.io.Serializable {

	private static final long serialVersionUID = -8643902475221560140L;
	
	private Double uniqueId;
	private String migrateStatus;
	private String errorMsg;
	private String recordTypeS;
	private String recordTypeM;
	private String cpRecordType;
	private String beginDateS;
	private String beginDateM;
	private String cpContBeginDate;
	private String endDateS;
	private String endDateM;
	private String cpContEndDate;
	private String companyS;
	private String companyM;
	private String cpCompany;
	private String locationNameS;
	private String locationNameM;
	private String cpLocationName;
	private String contractIdS;
	private String contractIdM;
	private String cpContractId;
	private String locationIdS;
	private String locationIdM;
	private String cpLocationId;
	private String regionS;
	private String regionM;
	private String cpRegion;
	private String vencodS;
	private String vencodM;
	private String cpPayeeVendorId;
	private String provinceId;
	private String provinceIdM;
	private String cpProvince;
	private String payeeNameS;
	private String payeeNameM;
	private String cpPayee;
	private Integer subconS;
	private Integer subconM;
	private Double depamtS;
	private Double depamtM;
	private String cpDepositAmt;
	private Double mnimsDepositamt;
	private Double vat;
	private String vatCondition;
	private Double sapDepositamt;
	private String reconcileDepositamt;
	private Double contractAmountS;
	private Double contractAmountM;
	private String cpContractAmount;
	private Double monthlyAmountS;
	private Double monthlyAmountM;
	private String cpMonthlyAmount;
	private Double whtCompanyAbsorbS;
	private Double whtCompanyAbsorbM;
	private String cpWhtCompanyAbsorb;
	private Double baseAmountVatS;
	private Double baseAmountVatM;
	private String cpBaseAmountVat;
	private Double whtCode1S;
	private String whtCode1M;
	private String cpWhtCode1;
	private Double whtBaseCode1S;
	private Double whtBaseCode1M;
	private String cpWhtBaseCode1;
	private Double whtCode2S;
	private String whtCode2M;
	private String cpWhtCode2;
	private Double whtBaseCode2S;
	private Double whtBaseCode2M;
	private String cpWhtBaseCode2;
	private Double rentalAmountS;
	private Double rentalAmountM;
	private String cpRentalAmount;
	private Double serviceAmountS;
	private Double serviceAmountM;
	private String cpServiceAmount;
	private Double whtRentalAmountS;
	private Double whtRentalAmountM;
	private String cpWhtRentalAmount;
	private Double whtServiceAmountS;
	private Double whtServiceAmountM;
	private String cpWhtServiceAmount;
	private String fromSapTable;
	private Double no;
	private String rectyp;
	private String comcod;
	private String basnam;
	private String conno;
	private Integer subcon;
	private String contyp;
	private String locid;
	private String phaseSap;
	private String system;
	private String regionSap;
	private String jobtyp;
	private String stadat;
	private String enddat;
	private String vencod;
	private Double coscen;
	private String provin;
	private String altnam;
	private String premon;
	private String terint;
	private Double depamt;
	private Double vatdep;
	private Double conamt;
	private Double monamt;
	private Double abswit;
	private Double basamt;
	private Double adjamt;
	private String adjrea;
	private String adjdat;
	private Double witcod1;
	private Double witbas1;
	private Double witcod2;
	private Double witbas2;
	private String fstdue;
	private Double rntamt;
	private Double svcamt;
	private Double wthrnt;
	private Double wthsvc;
	private Double amtbill;
	private Double amtpai;
	private Double amtout;
	private Double prpamt;
	private Double prpout;
	private Double tembill;
	private Double tempai;
	private Double temout;
	private String filename;
	private String createdate;
	private String fromMnimsTable;
	private String contractId;
	private String locationId;
	private String locationCode;
	private String locationName;
	private String phase;
	private Double priority;
	private String systemType;
	private String region;
	private String stationType;
	private String contractType;
	private String siteplanId;
	private String sitecode;
	private String company;
	private String status;
	private String samTeam;
	private String officerName;
	private Date contBeginDate;
	private Date contEndDate;
	private String contNoOfYears;
	private Date contValidConEnd;
	private Date contExtensionDate;
	private String placeType;
	private String placeM2Roof;
	private String placeM2Building;
	private String placeM2Room;
	private String placeM2Land;
	private String placeW2Land;
	private String siteaddRegionConfirm;
	private String siteaddAddress1;
	private String siteaddAddress2;
	private String siteaddDistrict;
	private String siteaddSubDivision;
	private String siteaddProvince;
	private String siteaddZipcode;
	private String siteaddTelephone;
	private String siteaddFax;
	private String siteaddRemark;
	private String ownerName;
	private String ownerNameInContract;
	private String ownerAddress1;
	private String ownerAddress2;
	private String ownerStreet;
	private String ownerDistrict;
	private String ownerSubdivision;
	private String ownerProvince;
	private String ownerZipcode;
	private String ownerTelephone;
	private String ownerFax;
	private String ownerContactPerson;
	private String ownerContactTelephone;
	private String payeeVendorId;
	private String payeeName;
	private String payeeAddress1;
	private String payeeAddress2;
	private String payeeDistrict;
	private String payeeSubDivision;
	private String payeeProvince;
	private String payeeZipcode;
	private String payeeTelephone;
	private String payeeFax;
	private String payee2Name;
	private String payee2Address1;
	private String payee2Address2;
	private String payee2District;
	private String payee2SubDivision;
	private String payee2Province;
	private String payee2Zipcode;
	private String payee2Telephone;
	private String payee2Fax;
	private String elecMeaType;
	private Double elecCostPerUnit;
	private Double elecTotalCostMonth;
	private Double elecTotalCostYear;
	private String elecTotalCostCondition;
	private String elecRemark;
	private Double RNextIncreasePercent;
	private Double RRentalFeeY1;
	private String RRentalTypeY1;
	private Double RRentalFeeY2;
	private String RRentalTypeY2;
	private Double RRentalFeeY3;
	private String RRentalTypeY3;
	private Double RAdvanceNoMonths;
	private String RWhtType;
	private String RHouseTaxType;
	private Double RHouseTaxFigure;
	private String RHouseTaxRemark;
	private Double RTotalRentPlusService;
	private Double RRentalIncrease;
	private Double SNextIncreasePercent;
	private Double SServiceFeeY1;
	private String SServiceTypeY1;
	private Double SServiceFeeY2;
	private String SServiceTypeY2;
	private Double SServiceFeeY3;
	private String SServiceTypeY3;
	private String SVatType;
	private String SWhtType;
	private Double SServiceIncrease;
	private String depositPaymentType;
	private Double depositFigure;
	private Double depositIncrease;
	private Date contMakingDate;
	private Date contSamAcceptDate;
	private Date contSamToAspmDate;
	private Date contSignatureDate;
	private Date contTotSignatureDate;
	private Date contAspmAcceptDate;
	private Date contSendToOwnerDate;
	private Date contAspmFilingDate;
	private String contStoredType;
	private Double sapVendorAmtRentalY1;
	private Double sapVendorAmtRentalY2;
	private Double sapVendorAmtRentalY3;
	private Double sapWhtAmtRentalY1;
	private Double sapWhtAmtRentalY2;
	private Double sapWhtAmtRentalY3;
	private Double sapVendorAmtServiceY1;
	private Double sapVendorAmtServiceY2;
	private Double sapVendorAmtServiceY3;
	private Double sapWhtAmtServiceY1;
	private Double sapWhtAmtServiceY2;
	private Double sapWhtAmtServiceY3;
	private String contractFileName;
	private String exportInsurStatus;
	private String elMetinfElectZone;
	private String elMetinfElectZoneCode;
	private String elMetinfElectZoneBelong;
	private Date elMetinfElectPaidDate;
	private String elMetinfMeterId;
	private String elMetinfElectricUsername;
	private String elMetinfAdapterBrand;
	private String elMetinfAdapterSize;
	private String elMetinfMeterSize;
	private String elMetinfAdapterSerialNo;
	private Date elMetinfAdapterInstalldate;
	private Date elMetinfSaqmModelDate;
	private Date elMetinfSaqmContractDate;
	private Date elMetinfSendMeterDate;
	private Date elMetinfSendElectricDate;
	private Date elMetinfAdddataDate;
	private String elMetinfRemark;
	private String elMetbgNoDepositBg1;
	private String elMetbgBankBg1;
	private String elMetbgMeaDepositBg1;
	private Date elMetbgInsuranceStart1;
	private Date elMetbgInsuranceEnd1;
	private Date elMetbgReceivedBgDate1;
	private Date elMetbgReturnToFndDate1;
	private String elMetbgRemark1;
	private String elMetbgNoDepositBg2;
	private String elMetbgBankBg2;
	private String elMetbgMeaDepositBg2;
	private Date elMetbgInsuranceStart2;
	private Date elMetbgInsuranceEnd2;
	private Date elMetbgReceivedBgDate2;
	private Date elMetbgReturnToFndDate2;
	private String elMetbgRemark2;
	private Date elMetbgAdddataDate;
	private Double elMetbgCashFee1;
	private Date elMetbgCashMeaPay1;
	private Date elMetbgCashAspdPay1;
	private String elMetbgCashRemark1;
	private Double elMetbgCashFee2;
	private Date elMetbgCashMeaPay2;
	private Date elMetbgCashAspdPay2;
	private String elMetbgCashRemark2;
	private Date lastUpdateDate;
	private String lastUpdateUser;
	private String rentalWhtCode;
	private String serviceWhtCode;
	private String depositRemark;
	private String renewStatus;
	private String oldLocationName;
	private String contractProvince;
	private String parentContract;
	private String depositeVatType;
	private Date createDate;
	private String meterInfoStatus;
	private String insuranceStatus;
	private String timeEntry;
	private String elecPermission;
	private String otherCondition;
	private String cmMeterType;
	private String cmSaveEnergy;
	private Double depositSFigure;
	private String depositSType;
	private String depositSVattype;
	private String elMetinfMeterPhase;
	private String lastUpdateMeterUser;
	private Date lastUpdateMeterDate;
	private String elMetinfMeterId2;
	private String elMetbgReceipt;
	private Date elMetbgReceiptDate;
	private String prevContractId;
	private String nextContractId;
	private String contractOrder;
	private Character flagTrfMeter;
	private Date ognTrfMeterDate;
	private Date dstTrfMeterDate;
	private String rentalGl;
	private String trfMeterId;
	private String semRemark;
	private String semUpdateRemark;
	private String elMetinfMeterId3;
	private String semOwnerNameInContract1;
	private String semOwnerNameInContract2;
	private String semOwnerNameInContractR;

	public MpContractClean() {
	}
	
	@Id
	@Column(name = "UNIQUE_ID", precision = 22, scale = 0)
	public Double getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(Double uniqueId) {
		this.uniqueId = uniqueId;
	}

	@Column(name = "MIGRATE_STATUS", length = 10)
	public String getMigrateStatus() {
		return this.migrateStatus;
	}

	public void setMigrateStatus(String migrateStatus) {
		this.migrateStatus = migrateStatus;
	}

	@Column(name = "ERROR_MSG", length = 50)
	public String getErrorMsg() {
		return this.errorMsg;
	}

	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}

	@Column(name = "RECORD_TYPE_S", length = 3)
	public String getRecordTypeS() {
		return this.recordTypeS;
	}

	public void setRecordTypeS(String recordTypeS) {
		this.recordTypeS = recordTypeS;
	}

	@Column(name = "RECORD_TYPE_M", length = 10)
	public String getRecordTypeM() {
		return this.recordTypeM;
	}

	public void setRecordTypeM(String recordTypeM) {
		this.recordTypeM = recordTypeM;
	}

	@Column(name = "CP_RECORD_TYPE", length = 10)
	public String getCpRecordType() {
		return this.cpRecordType;
	}

	public void setCpRecordType(String cpRecordType) {
		this.cpRecordType = cpRecordType;
	}

	@Column(name = "BEGIN_DATE_S", length = 8)
	public String getBeginDateS() {
		return this.beginDateS;
	}

	public void setBeginDateS(String beginDateS) {
		this.beginDateS = beginDateS;
	}

	@Column(name = "BEGIN_DATE_M", length = 8)
	public String getBeginDateM() {
		return this.beginDateM;
	}

	public void setBeginDateM(String beginDateM) {
		this.beginDateM = beginDateM;
	}

	@Column(name = "CP_CONT_BEGIN_DATE", length = 10)
	public String getCpContBeginDate() {
		return this.cpContBeginDate;
	}

	public void setCpContBeginDate(String cpContBeginDate) {
		this.cpContBeginDate = cpContBeginDate;
	}

	@Column(name = "END_DATE_S", length = 8)
	public String getEndDateS() {
		return this.endDateS;
	}

	public void setEndDateS(String endDateS) {
		this.endDateS = endDateS;
	}

	@Column(name = "END_DATE_M", length = 8)
	public String getEndDateM() {
		return this.endDateM;
	}

	public void setEndDateM(String endDateM) {
		this.endDateM = endDateM;
	}

	@Column(name = "CP_CONT_END_DATE", length = 10)
	public String getCpContEndDate() {
		return this.cpContEndDate;
	}

	public void setCpContEndDate(String cpContEndDate) {
		this.cpContEndDate = cpContEndDate;
	}

	@Column(name = "COMPANY_S", length = 10)
	public String getCompanyS() {
		return this.companyS;
	}

	public void setCompanyS(String companyS) {
		this.companyS = companyS;
	}

	@Column(name = "COMPANY_M", length = 10)
	public String getCompanyM() {
		return this.companyM;
	}

	public void setCompanyM(String companyM) {
		this.companyM = companyM;
	}

	@Column(name = "CP_COMPANY", length = 10)
	public String getCpCompany() {
		return this.cpCompany;
	}

	public void setCpCompany(String cpCompany) {
		this.cpCompany = cpCompany;
	}

	@Column(name = "LOCATION_NAME_S", length = 50)
	public String getLocationNameS() {
		return this.locationNameS;
	}

	public void setLocationNameS(String locationNameS) {
		this.locationNameS = locationNameS;
	}

	@Column(name = "LOCATION_NAME_M", length = 300)
	public String getLocationNameM() {
		return this.locationNameM;
	}

	public void setLocationNameM(String locationNameM) {
		this.locationNameM = locationNameM;
	}

	@Column(name = "CP_LOCATION_NAME", length = 10)
	public String getCpLocationName() {
		return this.cpLocationName;
	}

	public void setCpLocationName(String cpLocationName) {
		this.cpLocationName = cpLocationName;
	}

	@Column(name = "CONTRACT_ID_S", length = 15)
	public String getContractIdS() {
		return this.contractIdS;
	}

	public void setContractIdS(String contractIdS) {
		this.contractIdS = contractIdS;
	}

	@Column(name = "CONTRACT_ID_M", length = 25)
	public String getContractIdM() {
		return this.contractIdM;
	}

	public void setContractIdM(String contractIdM) {
		this.contractIdM = contractIdM;
	}

	@Column(name = "CP_CONTRACT_ID", length = 10)
	public String getCpContractId() {
		return this.cpContractId;
	}

	public void setCpContractId(String cpContractId) {
		this.cpContractId = cpContractId;
	}

	@Column(name = "LOCATION_ID_S", length = 10)
	public String getLocationIdS() {
		return this.locationIdS;
	}

	public void setLocationIdS(String locationIdS) {
		this.locationIdS = locationIdS;
	}

	@Column(name = "LOCATION_ID_M", length = 25)
	public String getLocationIdM() {
		return this.locationIdM;
	}

	public void setLocationIdM(String locationIdM) {
		this.locationIdM = locationIdM;
	}

	@Column(name = "CP_LOCATION_ID", length = 10)
	public String getCpLocationId() {
		return this.cpLocationId;
	}

	public void setCpLocationId(String cpLocationId) {
		this.cpLocationId = cpLocationId;
	}

	@Column(name = "REGION_S", length = 3)
	public String getRegionS() {
		return this.regionS;
	}

	public void setRegionS(String regionS) {
		this.regionS = regionS;
	}

	@Column(name = "REGION_M", length = 10)
	public String getRegionM() {
		return this.regionM;
	}

	public void setRegionM(String regionM) {
		this.regionM = regionM;
	}

	@Column(name = "CP_REGION", length = 10)
	public String getCpRegion() {
		return this.cpRegion;
	}

	public void setCpRegion(String cpRegion) {
		this.cpRegion = cpRegion;
	}

	@Column(name = "VENCOD_S", length = 10)
	public String getVencodS() {
		return this.vencodS;
	}

	public void setVencodS(String vencodS) {
		this.vencodS = vencodS;
	}

	@Column(name = "VENCOD_M", length = 25)
	public String getVencodM() {
		return this.vencodM;
	}

	public void setVencodM(String vencodM) {
		this.vencodM = vencodM;
	}

	@Column(name = "CP_PAYEE_VENDOR_ID", length = 10)
	public String getCpPayeeVendorId() {
		return this.cpPayeeVendorId;
	}

	public void setCpPayeeVendorId(String cpPayeeVendorId) {
		this.cpPayeeVendorId = cpPayeeVendorId;
	}

	@Column(name = "PROVINCE_ID", length = 10)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "PROVINCE_ID_M", length = 50)
	public String getProvinceIdM() {
		return this.provinceIdM;
	}

	public void setProvinceIdM(String provinceIdM) {
		this.provinceIdM = provinceIdM;
	}

	@Column(name = "CP_PROVINCE", length = 10)
	public String getCpProvince() {
		return this.cpProvince;
	}

	public void setCpProvince(String cpProvince) {
		this.cpProvince = cpProvince;
	}

	@Column(name = "PAYEE_NAME_S", length = 80)
	public String getPayeeNameS() {
		return this.payeeNameS;
	}

	public void setPayeeNameS(String payeeNameS) {
		this.payeeNameS = payeeNameS;
	}

	@Column(name = "PAYEE_NAME_M", length = 300)
	public String getPayeeNameM() {
		return this.payeeNameM;
	}

	public void setPayeeNameM(String payeeNameM) {
		this.payeeNameM = payeeNameM;
	}

	@Column(name = "CP_PAYEE", length = 10)
	public String getCpPayee() {
		return this.cpPayee;
	}

	public void setCpPayee(String cpPayee) {
		this.cpPayee = cpPayee;
	}

	@Column(name = "SUBCON_S", precision = 22, scale = 0)
	public Integer getSubconS() {
		return this.subconS;
	}

	public void setSubconS(Integer subconS) {
		this.subconS = subconS;
	}

	@Column(name = "SUBCON_M", precision = 22, scale = 0)
	public Integer getSubconM() {
		return this.subconM;
	}

	public void setSubconM(Integer subconM) {
		this.subconM = subconM;
	}

	@Column(name = "DEPAMT_S", precision = 15)
	public Double getDepamtS() {
		return this.depamtS;
	}

	public void setDepamtS(Double depamtS) {
		this.depamtS = depamtS;
	}

	@Column(name = "DEPAMT_M", precision = 20)
	public Double getDepamtM() {
		return this.depamtM;
	}

	public void setDepamtM(Double depamtM) {
		this.depamtM = depamtM;
	}

	@Column(name = "CP_DEPOSIT_AMT", length = 10)
	public String getCpDepositAmt() {
		return this.cpDepositAmt;
	}

	public void setCpDepositAmt(String cpDepositAmt) {
		this.cpDepositAmt = cpDepositAmt;
	}

	@Column(name = "MNIMS_DEPOSITAMT", precision = 20)
	public Double getMnimsDepositamt() {
		return this.mnimsDepositamt;
	}

	public void setMnimsDepositamt(Double mnimsDepositamt) {
		this.mnimsDepositamt = mnimsDepositamt;
	}

	@Column(name = "VAT", precision = 22, scale = 0)
	public Double getVat() {
		return this.vat;
	}

	public void setVat(Double vat) {
		this.vat = vat;
	}

	@Column(name = "VAT_CONDITION", length = 11)
	public String getVatCondition() {
		return this.vatCondition;
	}

	public void setVatCondition(String vatCondition) {
		this.vatCondition = vatCondition;
	}

	@Column(name = "SAP_DEPOSITAMT", precision = 15)
	public Double getSapDepositamt() {
		return this.sapDepositamt;
	}

	public void setSapDepositamt(Double sapDepositamt) {
		this.sapDepositamt = sapDepositamt;
	}

	@Column(name = "RECONCILE_DEPOSITAMT", length = 10)
	public String getReconcileDepositamt() {
		return this.reconcileDepositamt;
	}

	public void setReconcileDepositamt(String reconcileDepositamt) {
		this.reconcileDepositamt = reconcileDepositamt;
	}

	@Column(name = "CONTRACT_AMOUNT_S", precision = 15)
	public Double getContractAmountS() {
		return this.contractAmountS;
	}

	public void setContractAmountS(Double contractAmountS) {
		this.contractAmountS = contractAmountS;
	}

	@Column(name = "CONTRACT_AMOUNT_M", precision = 22, scale = 0)
	public Double getContractAmountM() {
		return this.contractAmountM;
	}

	public void setContractAmountM(Double contractAmountM) {
		this.contractAmountM = contractAmountM;
	}

	@Column(name = "CP_CONTRACT_AMOUNT", length = 10)
	public String getCpContractAmount() {
		return this.cpContractAmount;
	}

	public void setCpContractAmount(String cpContractAmount) {
		this.cpContractAmount = cpContractAmount;
	}

	@Column(name = "MONTHLY_AMOUNT_S", precision = 15)
	public Double getMonthlyAmountS() {
		return this.monthlyAmountS;
	}

	public void setMonthlyAmountS(Double monthlyAmountS) {
		this.monthlyAmountS = monthlyAmountS;
	}

	@Column(name = "MONTHLY_AMOUNT_M", precision = 22, scale = 0)
	public Double getMonthlyAmountM() {
		return this.monthlyAmountM;
	}

	public void setMonthlyAmountM(Double monthlyAmountM) {
		this.monthlyAmountM = monthlyAmountM;
	}

	@Column(name = "CP_MONTHLY_AMOUNT", length = 10)
	public String getCpMonthlyAmount() {
		return this.cpMonthlyAmount;
	}

	public void setCpMonthlyAmount(String cpMonthlyAmount) {
		this.cpMonthlyAmount = cpMonthlyAmount;
	}

	@Column(name = "WHT_COMPANY_ABSORB_S", precision = 15)
	public Double getWhtCompanyAbsorbS() {
		return this.whtCompanyAbsorbS;
	}

	public void setWhtCompanyAbsorbS(Double whtCompanyAbsorbS) {
		this.whtCompanyAbsorbS = whtCompanyAbsorbS;
	}

	@Column(name = "WHT_COMPANY_ABSORB_M", precision = 22, scale = 0)
	public Double getWhtCompanyAbsorbM() {
		return this.whtCompanyAbsorbM;
	}

	public void setWhtCompanyAbsorbM(Double whtCompanyAbsorbM) {
		this.whtCompanyAbsorbM = whtCompanyAbsorbM;
	}

	@Column(name = "CP_WHT_COMPANY_ABSORB", length = 10)
	public String getCpWhtCompanyAbsorb() {
		return this.cpWhtCompanyAbsorb;
	}

	public void setCpWhtCompanyAbsorb(String cpWhtCompanyAbsorb) {
		this.cpWhtCompanyAbsorb = cpWhtCompanyAbsorb;
	}

	@Column(name = "BASE_AMOUNT_VAT_S", precision = 15)
	public Double getBaseAmountVatS() {
		return this.baseAmountVatS;
	}

	public void setBaseAmountVatS(Double baseAmountVatS) {
		this.baseAmountVatS = baseAmountVatS;
	}

	@Column(name = "BASE_AMOUNT_VAT_M", precision = 22, scale = 0)
	public Double getBaseAmountVatM() {
		return this.baseAmountVatM;
	}

	public void setBaseAmountVatM(Double baseAmountVatM) {
		this.baseAmountVatM = baseAmountVatM;
	}

	@Column(name = "CP_BASE_AMOUNT_VAT", length = 10)
	public String getCpBaseAmountVat() {
		return this.cpBaseAmountVat;
	}

	public void setCpBaseAmountVat(String cpBaseAmountVat) {
		this.cpBaseAmountVat = cpBaseAmountVat;
	}

	@Column(name = "WHT_CODE1_S", precision = 22, scale = 0)
	public Double getWhtCode1S() {
		return this.whtCode1S;
	}

	public void setWhtCode1S(Double whtCode1S) {
		this.whtCode1S = whtCode1S;
	}

	@Column(name = "WHT_CODE1_M", length = 10)
	public String getWhtCode1M() {
		return this.whtCode1M;
	}

	public void setWhtCode1M(String whtCode1M) {
		this.whtCode1M = whtCode1M;
	}

	@Column(name = "CP_WHT_CODE1", length = 10)
	public String getCpWhtCode1() {
		return this.cpWhtCode1;
	}

	public void setCpWhtCode1(String cpWhtCode1) {
		this.cpWhtCode1 = cpWhtCode1;
	}

	@Column(name = "WHT_BASE_CODE1_S", precision = 22, scale = 0)
	public Double getWhtBaseCode1S() {
		return this.whtBaseCode1S;
	}

	public void setWhtBaseCode1S(Double whtBaseCode1S) {
		this.whtBaseCode1S = whtBaseCode1S;
	}

	@Column(name = "WHT_BASE_CODE1_M", precision = 22, scale = 0)
	public Double getWhtBaseCode1M() {
		return this.whtBaseCode1M;
	}

	public void setWhtBaseCode1M(Double whtBaseCode1M) {
		this.whtBaseCode1M = whtBaseCode1M;
	}

	@Column(name = "CP_WHT_BASE_CODE1", length = 10)
	public String getCpWhtBaseCode1() {
		return this.cpWhtBaseCode1;
	}

	public void setCpWhtBaseCode1(String cpWhtBaseCode1) {
		this.cpWhtBaseCode1 = cpWhtBaseCode1;
	}

	@Column(name = "WHT_CODE2_S", precision = 22, scale = 0)
	public Double getWhtCode2S() {
		return this.whtCode2S;
	}

	public void setWhtCode2S(Double whtCode2S) {
		this.whtCode2S = whtCode2S;
	}

	@Column(name = "WHT_CODE2_M", length = 10)
	public String getWhtCode2M() {
		return this.whtCode2M;
	}

	public void setWhtCode2M(String whtCode2M) {
		this.whtCode2M = whtCode2M;
	}

	@Column(name = "CP_WHT_CODE2", length = 10)
	public String getCpWhtCode2() {
		return this.cpWhtCode2;
	}

	public void setCpWhtCode2(String cpWhtCode2) {
		this.cpWhtCode2 = cpWhtCode2;
	}

	@Column(name = "WHT_BASE_CODE2_S", precision = 22, scale = 0)
	public Double getWhtBaseCode2S() {
		return this.whtBaseCode2S;
	}

	public void setWhtBaseCode2S(Double whtBaseCode2S) {
		this.whtBaseCode2S = whtBaseCode2S;
	}

	@Column(name = "WHT_BASE_CODE2_M", precision = 22, scale = 0)
	public Double getWhtBaseCode2M() {
		return this.whtBaseCode2M;
	}

	public void setWhtBaseCode2M(Double whtBaseCode2M) {
		this.whtBaseCode2M = whtBaseCode2M;
	}

	@Column(name = "CP_WHT_BASE_CODE2", length = 10)
	public String getCpWhtBaseCode2() {
		return this.cpWhtBaseCode2;
	}

	public void setCpWhtBaseCode2(String cpWhtBaseCode2) {
		this.cpWhtBaseCode2 = cpWhtBaseCode2;
	}

	@Column(name = "RENTAL_AMOUNT_S", precision = 15)
	public Double getRentalAmountS() {
		return this.rentalAmountS;
	}

	public void setRentalAmountS(Double rentalAmountS) {
		this.rentalAmountS = rentalAmountS;
	}

	@Column(name = "RENTAL_AMOUNT_M", precision = 22, scale = 0)
	public Double getRentalAmountM() {
		return this.rentalAmountM;
	}

	public void setRentalAmountM(Double rentalAmountM) {
		this.rentalAmountM = rentalAmountM;
	}

	@Column(name = "CP_RENTAL_AMOUNT", length = 10)
	public String getCpRentalAmount() {
		return this.cpRentalAmount;
	}

	public void setCpRentalAmount(String cpRentalAmount) {
		this.cpRentalAmount = cpRentalAmount;
	}

	@Column(name = "SERVICE_AMOUNT_S", precision = 15)
	public Double getServiceAmountS() {
		return this.serviceAmountS;
	}

	public void setServiceAmountS(Double serviceAmountS) {
		this.serviceAmountS = serviceAmountS;
	}

	@Column(name = "SERVICE_AMOUNT_M", precision = 22, scale = 0)
	public Double getServiceAmountM() {
		return this.serviceAmountM;
	}

	public void setServiceAmountM(Double serviceAmountM) {
		this.serviceAmountM = serviceAmountM;
	}

	@Column(name = "CP_SERVICE_AMOUNT", length = 10)
	public String getCpServiceAmount() {
		return this.cpServiceAmount;
	}

	public void setCpServiceAmount(String cpServiceAmount) {
		this.cpServiceAmount = cpServiceAmount;
	}

	@Column(name = "WHT_RENTAL_AMOUNT_S", precision = 15)
	public Double getWhtRentalAmountS() {
		return this.whtRentalAmountS;
	}

	public void setWhtRentalAmountS(Double whtRentalAmountS) {
		this.whtRentalAmountS = whtRentalAmountS;
	}

	@Column(name = "WHT_RENTAL_AMOUNT_M", precision = 22, scale = 0)
	public Double getWhtRentalAmountM() {
		return this.whtRentalAmountM;
	}

	public void setWhtRentalAmountM(Double whtRentalAmountM) {
		this.whtRentalAmountM = whtRentalAmountM;
	}

	@Column(name = "CP_WHT_RENTAL_AMOUNT", length = 10)
	public String getCpWhtRentalAmount() {
		return this.cpWhtRentalAmount;
	}

	public void setCpWhtRentalAmount(String cpWhtRentalAmount) {
		this.cpWhtRentalAmount = cpWhtRentalAmount;
	}

	@Column(name = "WHT_SERVICE_AMOUNT_S", precision = 15)
	public Double getWhtServiceAmountS() {
		return this.whtServiceAmountS;
	}

	public void setWhtServiceAmountS(Double whtServiceAmountS) {
		this.whtServiceAmountS = whtServiceAmountS;
	}

	@Column(name = "WHT_SERVICE_AMOUNT_M", precision = 22, scale = 0)
	public Double getWhtServiceAmountM() {
		return this.whtServiceAmountM;
	}

	public void setWhtServiceAmountM(Double whtServiceAmountM) {
		this.whtServiceAmountM = whtServiceAmountM;
	}

	@Column(name = "CP_WHT_SERVICE_AMOUNT", length = 10)
	public String getCpWhtServiceAmount() {
		return this.cpWhtServiceAmount;
	}

	public void setCpWhtServiceAmount(String cpWhtServiceAmount) {
		this.cpWhtServiceAmount = cpWhtServiceAmount;
	}

	@Column(name = "FROM_SAP_TABLE", length = 4)
	public String getFromSapTable() {
		return this.fromSapTable;
	}

	public void setFromSapTable(String fromSapTable) {
		this.fromSapTable = fromSapTable;
	}

	@Column(name = "NO", precision = 22, scale = 0)
	public Double getNo() {
		return this.no;
	}

	public void setNo(Double no) {
		this.no = no;
	}

	@Column(name = "RECTYP", length = 3)
	public String getRectyp() {
		return this.rectyp;
	}

	public void setRectyp(String rectyp) {
		this.rectyp = rectyp;
	}

	@Column(name = "COMCOD", length = 10)
	public String getComcod() {
		return this.comcod;
	}

	public void setComcod(String comcod) {
		this.comcod = comcod;
	}

	@Column(name = "BASNAM", length = 50)
	public String getBasnam() {
		return this.basnam;
	}

	public void setBasnam(String basnam) {
		this.basnam = basnam;
	}

	@Column(name = "CONNO", length = 15)
	public String getConno() {
		return this.conno;
	}

	public void setConno(String conno) {
		this.conno = conno;
	}

	@Column(name = "SUBCON", precision = 22, scale = 0)
	public Integer getSubcon() {
		return this.subcon;
	}

	public void setSubcon(Integer subcon) {
		this.subcon = subcon;
	}

	@Column(name = "CONTYP", length = 2)
	public String getContyp() {
		return this.contyp;
	}

	public void setContyp(String contyp) {
		this.contyp = contyp;
	}

	@Column(name = "LOCID", length = 10)
	public String getLocid() {
		return this.locid;
	}

	public void setLocid(String locid) {
		this.locid = locid;
	}

	@Column(name = "PHASE_SAP", length = 10)
	public String getPhaseSap() {
		return this.phaseSap;
	}

	public void setPhaseSap(String phaseSap) {
		this.phaseSap = phaseSap;
	}

	@Column(name = "SYSTEM", length = 10)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "REGION_SAP", length = 3)
	public String getRegionSap() {
		return this.regionSap;
	}

	public void setRegionSap(String regionSap) {
		this.regionSap = regionSap;
	}

	@Column(name = "JOBTYP", length = 10)
	public String getJobtyp() {
		return this.jobtyp;
	}

	public void setJobtyp(String jobtyp) {
		this.jobtyp = jobtyp;
	}

	@Column(name = "STADAT", length = 8)
	public String getStadat() {
		return this.stadat;
	}

	public void setStadat(String stadat) {
		this.stadat = stadat;
	}

	@Column(name = "ENDDAT", length = 8)
	public String getEnddat() {
		return this.enddat;
	}

	public void setEnddat(String enddat) {
		this.enddat = enddat;
	}

	@Column(name = "VENCOD", length = 10)
	public String getVencod() {
		return this.vencod;
	}

	public void setVencod(String vencod) {
		this.vencod = vencod;
	}

	@Column(name = "COSCEN", precision = 22, scale = 0)
	public Double getCoscen() {
		return this.coscen;
	}

	public void setCoscen(Double coscen) {
		this.coscen = coscen;
	}

	@Column(name = "PROVIN", length = 20)
	public String getProvin() {
		return this.provin;
	}

	public void setProvin(String provin) {
		this.provin = provin;
	}

	@Column(name = "ALTNAM", length = 80)
	public String getAltnam() {
		return this.altnam;
	}

	public void setAltnam(String altnam) {
		this.altnam = altnam;
	}

	@Column(name = "PREMON", length = 2)
	public String getPremon() {
		return this.premon;
	}

	public void setPremon(String premon) {
		this.premon = premon;
	}

	@Column(name = "TERINT", length = 2)
	public String getTerint() {
		return this.terint;
	}

	public void setTerint(String terint) {
		this.terint = terint;
	}

	@Column(name = "DEPAMT", precision = 15)
	public Double getDepamt() {
		return this.depamt;
	}

	public void setDepamt(Double depamt) {
		this.depamt = depamt;
	}

	@Column(name = "VATDEP", precision = 15)
	public Double getVatdep() {
		return this.vatdep;
	}

	public void setVatdep(Double vatdep) {
		this.vatdep = vatdep;
	}

	@Column(name = "CONAMT", precision = 15)
	public Double getConamt() {
		return this.conamt;
	}

	public void setConamt(Double conamt) {
		this.conamt = conamt;
	}

	@Column(name = "MONAMT", precision = 15)
	public Double getMonamt() {
		return this.monamt;
	}

	public void setMonamt(Double monamt) {
		this.monamt = monamt;
	}

	@Column(name = "ABSWIT", precision = 15)
	public Double getAbswit() {
		return this.abswit;
	}

	public void setAbswit(Double abswit) {
		this.abswit = abswit;
	}

	@Column(name = "BASAMT", precision = 15)
	public Double getBasamt() {
		return this.basamt;
	}

	public void setBasamt(Double basamt) {
		this.basamt = basamt;
	}

	@Column(name = "ADJAMT", precision = 15)
	public Double getAdjamt() {
		return this.adjamt;
	}

	public void setAdjamt(Double adjamt) {
		this.adjamt = adjamt;
	}

	@Column(name = "ADJREA", length = 30)
	public String getAdjrea() {
		return this.adjrea;
	}

	public void setAdjrea(String adjrea) {
		this.adjrea = adjrea;
	}

	@Column(name = "ADJDAT", length = 8)
	public String getAdjdat() {
		return this.adjdat;
	}

	public void setAdjdat(String adjdat) {
		this.adjdat = adjdat;
	}

	@Column(name = "WITCOD1", precision = 22, scale = 0)
	public Double getWitcod1() {
		return this.witcod1;
	}

	public void setWitcod1(Double witcod1) {
		this.witcod1 = witcod1;
	}

	@Column(name = "WITBAS1", precision = 22, scale = 0)
	public Double getWitbas1() {
		return this.witbas1;
	}

	public void setWitbas1(Double witbas1) {
		this.witbas1 = witbas1;
	}

	@Column(name = "WITCOD2", precision = 22, scale = 0)
	public Double getWitcod2() {
		return this.witcod2;
	}

	public void setWitcod2(Double witcod2) {
		this.witcod2 = witcod2;
	}

	@Column(name = "WITBAS2", precision = 22, scale = 0)
	public Double getWitbas2() {
		return this.witbas2;
	}

	public void setWitbas2(Double witbas2) {
		this.witbas2 = witbas2;
	}

	@Column(name = "FSTDUE", length = 8)
	public String getFstdue() {
		return this.fstdue;
	}

	public void setFstdue(String fstdue) {
		this.fstdue = fstdue;
	}

	@Column(name = "RNTAMT", precision = 15)
	public Double getRntamt() {
		return this.rntamt;
	}

	public void setRntamt(Double rntamt) {
		this.rntamt = rntamt;
	}

	@Column(name = "SVCAMT", precision = 15)
	public Double getSvcamt() {
		return this.svcamt;
	}

	public void setSvcamt(Double svcamt) {
		this.svcamt = svcamt;
	}

	@Column(name = "WTHRNT", precision = 15)
	public Double getWthrnt() {
		return this.wthrnt;
	}

	public void setWthrnt(Double wthrnt) {
		this.wthrnt = wthrnt;
	}

	@Column(name = "WTHSVC", precision = 15)
	public Double getWthsvc() {
		return this.wthsvc;
	}

	public void setWthsvc(Double wthsvc) {
		this.wthsvc = wthsvc;
	}

	@Column(name = "AMTBILL", precision = 15)
	public Double getAmtbill() {
		return this.amtbill;
	}

	public void setAmtbill(Double amtbill) {
		this.amtbill = amtbill;
	}

	@Column(name = "AMTPAI", precision = 15)
	public Double getAmtpai() {
		return this.amtpai;
	}

	public void setAmtpai(Double amtpai) {
		this.amtpai = amtpai;
	}

	@Column(name = "AMTOUT", precision = 15)
	public Double getAmtout() {
		return this.amtout;
	}

	public void setAmtout(Double amtout) {
		this.amtout = amtout;
	}

	@Column(name = "PRPAMT", precision = 15)
	public Double getPrpamt() {
		return this.prpamt;
	}

	public void setPrpamt(Double prpamt) {
		this.prpamt = prpamt;
	}

	@Column(name = "PRPOUT", precision = 15)
	public Double getPrpout() {
		return this.prpout;
	}

	public void setPrpout(Double prpout) {
		this.prpout = prpout;
	}

	@Column(name = "TEMBILL", precision = 22, scale = 0)
	public Double getTembill() {
		return this.tembill;
	}

	public void setTembill(Double tembill) {
		this.tembill = tembill;
	}

	@Column(name = "TEMPAI", precision = 22, scale = 0)
	public Double getTempai() {
		return this.tempai;
	}

	public void setTempai(Double tempai) {
		this.tempai = tempai;
	}

	@Column(name = "TEMOUT", precision = 22, scale = 0)
	public Double getTemout() {
		return this.temout;
	}

	public void setTemout(Double temout) {
		this.temout = temout;
	}

	@Column(name = "FILENAME", length = 100)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "CREATEDATE", length = 8)
	public String getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	@Column(name = "FROM_MNIMS_TABLE", length = 4)
	public String getFromMnimsTable() {
		return this.fromMnimsTable;
	}

	public void setFromMnimsTable(String fromMnimsTable) {
		this.fromMnimsTable = fromMnimsTable;
	}

	@Column(name = "CONTRACT_ID", length = 25)
	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	@Column(name = "LOCATION_ID", length = 25)
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	@Column(name = "LOCATION_CODE", length = 25)
	public String getLocationCode() {
		return this.locationCode;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	@Column(name = "LOCATION_NAME", length = 300)
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "PHASE", length = 50)
	public String getPhase() {
		return this.phase;
	}

	public void setPhase(String phase) {
		this.phase = phase;
	}

	@Column(name = "PRIORITY", precision = 20, scale = 0)
	public Double getPriority() {
		return this.priority;
	}

	public void setPriority(Double priority) {
		this.priority = priority;
	}

	@Column(name = "SYSTEM_TYPE", length = 20)
	public String getSystemType() {
		return this.systemType;
	}

	public void setSystemType(String systemType) {
		this.systemType = systemType;
	}

	@Column(name = "REGION", length = 10)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "STATION_TYPE", length = 100)
	public String getStationType() {
		return this.stationType;
	}

	public void setStationType(String stationType) {
		this.stationType = stationType;
	}

	@Column(name = "CONTRACT_TYPE", length = 100)
	public String getContractType() {
		return this.contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	@Column(name = "SITEPLAN_ID", length = 25)
	public String getSiteplanId() {
		return this.siteplanId;
	}

	public void setSiteplanId(String siteplanId) {
		this.siteplanId = siteplanId;
	}

	@Column(name = "SITECODE", length = 50)
	public String getSitecode() {
		return this.sitecode;
	}

	public void setSitecode(String sitecode) {
		this.sitecode = sitecode;
	}

	@Column(name = "COMPANY", length = 10)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "SAM_TEAM", length = 10)
	public String getSamTeam() {
		return this.samTeam;
	}

	public void setSamTeam(String samTeam) {
		this.samTeam = samTeam;
	}

	@Column(name = "OFFICER_NAME", length = 100)
	public String getOfficerName() {
		return this.officerName;
	}

	public void setOfficerName(String officerName) {
		this.officerName = officerName;
	}

	@Column(name = "CONT_BEGIN_DATE", length = 7)
	public Date getContBeginDate() {
		return this.contBeginDate;
	}

	public void setContBeginDate(Date contBeginDate) {
		this.contBeginDate = contBeginDate;
	}

	@Column(name = "CONT_END_DATE", length = 7)
	public Date getContEndDate() {
		return this.contEndDate;
	}

	public void setContEndDate(Date contEndDate) {
		this.contEndDate = contEndDate;
	}

	@Column(name = "CONT_NO_OF_YEARS", length = 30)
	public String getContNoOfYears() {
		return this.contNoOfYears;
	}

	public void setContNoOfYears(String contNoOfYears) {
		this.contNoOfYears = contNoOfYears;
	}

	@Column(name = "CONT_VALID_CON_END", length = 7)
	public Date getContValidConEnd() {
		return this.contValidConEnd;
	}

	public void setContValidConEnd(Date contValidConEnd) {
		this.contValidConEnd = contValidConEnd;
	}

	@Column(name = "CONT_EXTENSION_DATE", length = 7)
	public Date getContExtensionDate() {
		return this.contExtensionDate;
	}

	public void setContExtensionDate(Date contExtensionDate) {
		this.contExtensionDate = contExtensionDate;
	}

	@Column(name = "PLACE_TYPE", length = 12)
	public String getPlaceType() {
		return this.placeType;
	}

	public void setPlaceType(String placeType) {
		this.placeType = placeType;
	}

	@Column(name = "PLACE_M2_ROOF", length = 100)
	public String getPlaceM2Roof() {
		return this.placeM2Roof;
	}

	public void setPlaceM2Roof(String placeM2Roof) {
		this.placeM2Roof = placeM2Roof;
	}

	@Column(name = "PLACE_M2_BUILDING", length = 100)
	public String getPlaceM2Building() {
		return this.placeM2Building;
	}

	public void setPlaceM2Building(String placeM2Building) {
		this.placeM2Building = placeM2Building;
	}

	@Column(name = "PLACE_M2_ROOM", length = 30)
	public String getPlaceM2Room() {
		return this.placeM2Room;
	}

	public void setPlaceM2Room(String placeM2Room) {
		this.placeM2Room = placeM2Room;
	}

	@Column(name = "PLACE_M2_LAND", length = 30)
	public String getPlaceM2Land() {
		return this.placeM2Land;
	}

	public void setPlaceM2Land(String placeM2Land) {
		this.placeM2Land = placeM2Land;
	}

	@Column(name = "PLACE_W2_LAND", length = 30)
	public String getPlaceW2Land() {
		return this.placeW2Land;
	}

	public void setPlaceW2Land(String placeW2Land) {
		this.placeW2Land = placeW2Land;
	}

	@Column(name = "SITEADD_REGION_CONFIRM", length = 50)
	public String getSiteaddRegionConfirm() {
		return this.siteaddRegionConfirm;
	}

	public void setSiteaddRegionConfirm(String siteaddRegionConfirm) {
		this.siteaddRegionConfirm = siteaddRegionConfirm;
	}

	@Column(name = "SITEADD_ADDRESS1", length = 200)
	public String getSiteaddAddress1() {
		return this.siteaddAddress1;
	}

	public void setSiteaddAddress1(String siteaddAddress1) {
		this.siteaddAddress1 = siteaddAddress1;
	}

	@Column(name = "SITEADD_ADDRESS2", length = 200)
	public String getSiteaddAddress2() {
		return this.siteaddAddress2;
	}

	public void setSiteaddAddress2(String siteaddAddress2) {
		this.siteaddAddress2 = siteaddAddress2;
	}

	@Column(name = "SITEADD_DISTRICT", length = 150)
	public String getSiteaddDistrict() {
		return this.siteaddDistrict;
	}

	public void setSiteaddDistrict(String siteaddDistrict) {
		this.siteaddDistrict = siteaddDistrict;
	}

	@Column(name = "SITEADD_SUB_DIVISION", length = 50)
	public String getSiteaddSubDivision() {
		return this.siteaddSubDivision;
	}

	public void setSiteaddSubDivision(String siteaddSubDivision) {
		this.siteaddSubDivision = siteaddSubDivision;
	}

	@Column(name = "SITEADD_PROVINCE", length = 50)
	public String getSiteaddProvince() {
		return this.siteaddProvince;
	}

	public void setSiteaddProvince(String siteaddProvince) {
		this.siteaddProvince = siteaddProvince;
	}

	@Column(name = "SITEADD_ZIPCODE", length = 10)
	public String getSiteaddZipcode() {
		return this.siteaddZipcode;
	}

	public void setSiteaddZipcode(String siteaddZipcode) {
		this.siteaddZipcode = siteaddZipcode;
	}

	@Column(name = "SITEADD_TELEPHONE", length = 100)
	public String getSiteaddTelephone() {
		return this.siteaddTelephone;
	}

	public void setSiteaddTelephone(String siteaddTelephone) {
		this.siteaddTelephone = siteaddTelephone;
	}

	@Column(name = "SITEADD_FAX", length = 100)
	public String getSiteaddFax() {
		return this.siteaddFax;
	}

	public void setSiteaddFax(String siteaddFax) {
		this.siteaddFax = siteaddFax;
	}

	@Column(name = "SITEADD_REMARK", length = 300)
	public String getSiteaddRemark() {
		return this.siteaddRemark;
	}

	public void setSiteaddRemark(String siteaddRemark) {
		this.siteaddRemark = siteaddRemark;
	}

	@Column(name = "OWNER_NAME", length = 300)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "OWNER_NAME_IN_CONTRACT", length = 300)
	public String getOwnerNameInContract() {
		return this.ownerNameInContract;
	}

	public void setOwnerNameInContract(String ownerNameInContract) {
		this.ownerNameInContract = ownerNameInContract;
	}

	@Column(name = "OWNER_ADDRESS1", length = 300)
	public String getOwnerAddress1() {
		return this.ownerAddress1;
	}

	public void setOwnerAddress1(String ownerAddress1) {
		this.ownerAddress1 = ownerAddress1;
	}

	@Column(name = "OWNER_ADDRESS2", length = 300)
	public String getOwnerAddress2() {
		return this.ownerAddress2;
	}

	public void setOwnerAddress2(String ownerAddress2) {
		this.ownerAddress2 = ownerAddress2;
	}

	@Column(name = "OWNER_STREET", length = 100)
	public String getOwnerStreet() {
		return this.ownerStreet;
	}

	public void setOwnerStreet(String ownerStreet) {
		this.ownerStreet = ownerStreet;
	}

	@Column(name = "OWNER_DISTRICT", length = 50)
	public String getOwnerDistrict() {
		return this.ownerDistrict;
	}

	public void setOwnerDistrict(String ownerDistrict) {
		this.ownerDistrict = ownerDistrict;
	}

	@Column(name = "OWNER_SUBDIVISION", length = 50)
	public String getOwnerSubdivision() {
		return this.ownerSubdivision;
	}

	public void setOwnerSubdivision(String ownerSubdivision) {
		this.ownerSubdivision = ownerSubdivision;
	}

	@Column(name = "OWNER_PROVINCE", length = 50)
	public String getOwnerProvince() {
		return this.ownerProvince;
	}

	public void setOwnerProvince(String ownerProvince) {
		this.ownerProvince = ownerProvince;
	}

	@Column(name = "OWNER_ZIPCODE", length = 10)
	public String getOwnerZipcode() {
		return this.ownerZipcode;
	}

	public void setOwnerZipcode(String ownerZipcode) {
		this.ownerZipcode = ownerZipcode;
	}

	@Column(name = "OWNER_TELEPHONE", length = 50)
	public String getOwnerTelephone() {
		return this.ownerTelephone;
	}

	public void setOwnerTelephone(String ownerTelephone) {
		this.ownerTelephone = ownerTelephone;
	}

	@Column(name = "OWNER_FAX", length = 50)
	public String getOwnerFax() {
		return this.ownerFax;
	}

	public void setOwnerFax(String ownerFax) {
		this.ownerFax = ownerFax;
	}

	@Column(name = "OWNER_CONTACT_PERSON", length = 150)
	public String getOwnerContactPerson() {
		return this.ownerContactPerson;
	}

	public void setOwnerContactPerson(String ownerContactPerson) {
		this.ownerContactPerson = ownerContactPerson;
	}

	@Column(name = "OWNER_CONTACT_TELEPHONE", length = 50)
	public String getOwnerContactTelephone() {
		return this.ownerContactTelephone;
	}

	public void setOwnerContactTelephone(String ownerContactTelephone) {
		this.ownerContactTelephone = ownerContactTelephone;
	}

	@Column(name = "PAYEE_VENDOR_ID", length = 25)
	public String getPayeeVendorId() {
		return this.payeeVendorId;
	}

	public void setPayeeVendorId(String payeeVendorId) {
		this.payeeVendorId = payeeVendorId;
	}

	@Column(name = "PAYEE_NAME", length = 300)
	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	@Column(name = "PAYEE_ADDRESS1", length = 300)
	public String getPayeeAddress1() {
		return this.payeeAddress1;
	}

	public void setPayeeAddress1(String payeeAddress1) {
		this.payeeAddress1 = payeeAddress1;
	}

	@Column(name = "PAYEE_ADDRESS2", length = 300)
	public String getPayeeAddress2() {
		return this.payeeAddress2;
	}

	public void setPayeeAddress2(String payeeAddress2) {
		this.payeeAddress2 = payeeAddress2;
	}

	@Column(name = "PAYEE_DISTRICT", length = 100)
	public String getPayeeDistrict() {
		return this.payeeDistrict;
	}

	public void setPayeeDistrict(String payeeDistrict) {
		this.payeeDistrict = payeeDistrict;
	}

	@Column(name = "PAYEE_SUB_DIVISION", length = 50)
	public String getPayeeSubDivision() {
		return this.payeeSubDivision;
	}

	public void setPayeeSubDivision(String payeeSubDivision) {
		this.payeeSubDivision = payeeSubDivision;
	}

	@Column(name = "PAYEE_PROVINCE", length = 50)
	public String getPayeeProvince() {
		return this.payeeProvince;
	}

	public void setPayeeProvince(String payeeProvince) {
		this.payeeProvince = payeeProvince;
	}

	@Column(name = "PAYEE_ZIPCODE", length = 10)
	public String getPayeeZipcode() {
		return this.payeeZipcode;
	}

	public void setPayeeZipcode(String payeeZipcode) {
		this.payeeZipcode = payeeZipcode;
	}

	@Column(name = "PAYEE_TELEPHONE", length = 50)
	public String getPayeeTelephone() {
		return this.payeeTelephone;
	}

	public void setPayeeTelephone(String payeeTelephone) {
		this.payeeTelephone = payeeTelephone;
	}

	@Column(name = "PAYEE_FAX", length = 50)
	public String getPayeeFax() {
		return this.payeeFax;
	}

	public void setPayeeFax(String payeeFax) {
		this.payeeFax = payeeFax;
	}

	@Column(name = "PAYEE2_NAME", length = 300)
	public String getPayee2Name() {
		return this.payee2Name;
	}

	public void setPayee2Name(String payee2Name) {
		this.payee2Name = payee2Name;
	}

	@Column(name = "PAYEE2_ADDRESS1", length = 300)
	public String getPayee2Address1() {
		return this.payee2Address1;
	}

	public void setPayee2Address1(String payee2Address1) {
		this.payee2Address1 = payee2Address1;
	}

	@Column(name = "PAYEE2_ADDRESS2", length = 300)
	public String getPayee2Address2() {
		return this.payee2Address2;
	}

	public void setPayee2Address2(String payee2Address2) {
		this.payee2Address2 = payee2Address2;
	}

	@Column(name = "PAYEE2_DISTRICT", length = 100)
	public String getPayee2District() {
		return this.payee2District;
	}

	public void setPayee2District(String payee2District) {
		this.payee2District = payee2District;
	}

	@Column(name = "PAYEE2_SUB_DIVISION", length = 50)
	public String getPayee2SubDivision() {
		return this.payee2SubDivision;
	}

	public void setPayee2SubDivision(String payee2SubDivision) {
		this.payee2SubDivision = payee2SubDivision;
	}

	@Column(name = "PAYEE2_PROVINCE", length = 50)
	public String getPayee2Province() {
		return this.payee2Province;
	}

	public void setPayee2Province(String payee2Province) {
		this.payee2Province = payee2Province;
	}

	@Column(name = "PAYEE2_ZIPCODE", length = 10)
	public String getPayee2Zipcode() {
		return this.payee2Zipcode;
	}

	public void setPayee2Zipcode(String payee2Zipcode) {
		this.payee2Zipcode = payee2Zipcode;
	}

	@Column(name = "PAYEE2_TELEPHONE", length = 50)
	public String getPayee2Telephone() {
		return this.payee2Telephone;
	}

	public void setPayee2Telephone(String payee2Telephone) {
		this.payee2Telephone = payee2Telephone;
	}

	@Column(name = "PAYEE2_FAX", length = 50)
	public String getPayee2Fax() {
		return this.payee2Fax;
	}

	public void setPayee2Fax(String payee2Fax) {
		this.payee2Fax = payee2Fax;
	}

	@Column(name = "ELEC_MEA_TYPE", length = 20)
	public String getElecMeaType() {
		return this.elecMeaType;
	}

	public void setElecMeaType(String elecMeaType) {
		this.elecMeaType = elecMeaType;
	}

	@Column(name = "ELEC_COST_PER_UNIT", precision = 20)
	public Double getElecCostPerUnit() {
		return this.elecCostPerUnit;
	}

	public void setElecCostPerUnit(Double elecCostPerUnit) {
		this.elecCostPerUnit = elecCostPerUnit;
	}

	@Column(name = "ELEC_TOTAL_COST_MONTH", precision = 20)
	public Double getElecTotalCostMonth() {
		return this.elecTotalCostMonth;
	}

	public void setElecTotalCostMonth(Double elecTotalCostMonth) {
		this.elecTotalCostMonth = elecTotalCostMonth;
	}

	@Column(name = "ELEC_TOTAL_COST_YEAR", precision = 20)
	public Double getElecTotalCostYear() {
		return this.elecTotalCostYear;
	}

	public void setElecTotalCostYear(Double elecTotalCostYear) {
		this.elecTotalCostYear = elecTotalCostYear;
	}

	@Column(name = "ELEC_TOTAL_COST_CONDITION", length = 50)
	public String getElecTotalCostCondition() {
		return this.elecTotalCostCondition;
	}

	public void setElecTotalCostCondition(String elecTotalCostCondition) {
		this.elecTotalCostCondition = elecTotalCostCondition;
	}

	@Column(name = "ELEC_REMARK", length = 200)
	public String getElecRemark() {
		return this.elecRemark;
	}

	public void setElecRemark(String elecRemark) {
		this.elecRemark = elecRemark;
	}

	@Column(name = "R_NEXT_INCREASE_PERCENT", precision = 20)
	public Double getRNextIncreasePercent() {
		return this.RNextIncreasePercent;
	}

	public void setRNextIncreasePercent(Double RNextIncreasePercent) {
		this.RNextIncreasePercent = RNextIncreasePercent;
	}

	@Column(name = "R_RENTAL_FEE_Y1", precision = 20)
	public Double getRRentalFeeY1() {
		return this.RRentalFeeY1;
	}

	public void setRRentalFeeY1(Double RRentalFeeY1) {
		this.RRentalFeeY1 = RRentalFeeY1;
	}

	@Column(name = "R_RENTAL_TYPE_Y1", length = 5)
	public String getRRentalTypeY1() {
		return this.RRentalTypeY1;
	}

	public void setRRentalTypeY1(String RRentalTypeY1) {
		this.RRentalTypeY1 = RRentalTypeY1;
	}

	@Column(name = "R_RENTAL_FEE_Y2", precision = 20)
	public Double getRRentalFeeY2() {
		return this.RRentalFeeY2;
	}

	public void setRRentalFeeY2(Double RRentalFeeY2) {
		this.RRentalFeeY2 = RRentalFeeY2;
	}

	@Column(name = "R_RENTAL_TYPE_Y2", length = 5)
	public String getRRentalTypeY2() {
		return this.RRentalTypeY2;
	}

	public void setRRentalTypeY2(String RRentalTypeY2) {
		this.RRentalTypeY2 = RRentalTypeY2;
	}

	@Column(name = "R_RENTAL_FEE_Y3", precision = 20)
	public Double getRRentalFeeY3() {
		return this.RRentalFeeY3;
	}

	public void setRRentalFeeY3(Double RRentalFeeY3) {
		this.RRentalFeeY3 = RRentalFeeY3;
	}

	@Column(name = "R_RENTAL_TYPE_Y3", length = 5)
	public String getRRentalTypeY3() {
		return this.RRentalTypeY3;
	}

	public void setRRentalTypeY3(String RRentalTypeY3) {
		this.RRentalTypeY3 = RRentalTypeY3;
	}

	@Column(name = "R_ADVANCE_NO_MONTHS", precision = 20, scale = 0)
	public Double getRAdvanceNoMonths() {
		return this.RAdvanceNoMonths;
	}

	public void setRAdvanceNoMonths(Double RAdvanceNoMonths) {
		this.RAdvanceNoMonths = RAdvanceNoMonths;
	}

	@Column(name = "R_WHT_TYPE", length = 5)
	public String getRWhtType() {
		return this.RWhtType;
	}

	public void setRWhtType(String RWhtType) {
		this.RWhtType = RWhtType;
	}

	@Column(name = "R_HOUSE_TAX_TYPE", length = 20)
	public String getRHouseTaxType() {
		return this.RHouseTaxType;
	}

	public void setRHouseTaxType(String RHouseTaxType) {
		this.RHouseTaxType = RHouseTaxType;
	}

	@Column(name = "R_HOUSE_TAX_FIGURE", precision = 20)
	public Double getRHouseTaxFigure() {
		return this.RHouseTaxFigure;
	}

	public void setRHouseTaxFigure(Double RHouseTaxFigure) {
		this.RHouseTaxFigure = RHouseTaxFigure;
	}

	@Column(name = "R_HOUSE_TAX_REMARK", length = 200)
	public String getRHouseTaxRemark() {
		return this.RHouseTaxRemark;
	}

	public void setRHouseTaxRemark(String RHouseTaxRemark) {
		this.RHouseTaxRemark = RHouseTaxRemark;
	}

	@Column(name = "R_TOTAL_RENT_PLUS_SERVICE", precision = 20)
	public Double getRTotalRentPlusService() {
		return this.RTotalRentPlusService;
	}

	public void setRTotalRentPlusService(Double RTotalRentPlusService) {
		this.RTotalRentPlusService = RTotalRentPlusService;
	}

	@Column(name = "R_RENTAL_INCREASE", precision = 20)
	public Double getRRentalIncrease() {
		return this.RRentalIncrease;
	}

	public void setRRentalIncrease(Double RRentalIncrease) {
		this.RRentalIncrease = RRentalIncrease;
	}

	@Column(name = "S_NEXT_INCREASE_PERCENT", precision = 20)
	public Double getSNextIncreasePercent() {
		return this.SNextIncreasePercent;
	}

	public void setSNextIncreasePercent(Double SNextIncreasePercent) {
		this.SNextIncreasePercent = SNextIncreasePercent;
	}

	@Column(name = "S_SERVICE_FEE_Y1", precision = 20)
	public Double getSServiceFeeY1() {
		return this.SServiceFeeY1;
	}

	public void setSServiceFeeY1(Double SServiceFeeY1) {
		this.SServiceFeeY1 = SServiceFeeY1;
	}

	@Column(name = "S_SERVICE_TYPE_Y1", length = 5)
	public String getSServiceTypeY1() {
		return this.SServiceTypeY1;
	}

	public void setSServiceTypeY1(String SServiceTypeY1) {
		this.SServiceTypeY1 = SServiceTypeY1;
	}

	@Column(name = "S_SERVICE_FEE_Y2", precision = 20)
	public Double getSServiceFeeY2() {
		return this.SServiceFeeY2;
	}

	public void setSServiceFeeY2(Double SServiceFeeY2) {
		this.SServiceFeeY2 = SServiceFeeY2;
	}

	@Column(name = "S_SERVICE_TYPE_Y2", length = 5)
	public String getSServiceTypeY2() {
		return this.SServiceTypeY2;
	}

	public void setSServiceTypeY2(String SServiceTypeY2) {
		this.SServiceTypeY2 = SServiceTypeY2;
	}

	@Column(name = "S_SERVICE_FEE_Y3", precision = 20)
	public Double getSServiceFeeY3() {
		return this.SServiceFeeY3;
	}

	public void setSServiceFeeY3(Double SServiceFeeY3) {
		this.SServiceFeeY3 = SServiceFeeY3;
	}

	@Column(name = "S_SERVICE_TYPE_Y3", length = 5)
	public String getSServiceTypeY3() {
		return this.SServiceTypeY3;
	}

	public void setSServiceTypeY3(String SServiceTypeY3) {
		this.SServiceTypeY3 = SServiceTypeY3;
	}

	@Column(name = "S_VAT_TYPE", length = 20)
	public String getSVatType() {
		return this.SVatType;
	}

	public void setSVatType(String SVatType) {
		this.SVatType = SVatType;
	}

	@Column(name = "S_WHT_TYPE", length = 20)
	public String getSWhtType() {
		return this.SWhtType;
	}

	public void setSWhtType(String SWhtType) {
		this.SWhtType = SWhtType;
	}

	@Column(name = "S_SERVICE_INCREASE", precision = 20)
	public Double getSServiceIncrease() {
		return this.SServiceIncrease;
	}

	public void setSServiceIncrease(Double SServiceIncrease) {
		this.SServiceIncrease = SServiceIncrease;
	}

	@Column(name = "DEPOSIT_PAYMENT_TYPE", length = 25)
	public String getDepositPaymentType() {
		return this.depositPaymentType;
	}

	public void setDepositPaymentType(String depositPaymentType) {
		this.depositPaymentType = depositPaymentType;
	}

	@Column(name = "DEPOSIT_FIGURE", precision = 20)
	public Double getDepositFigure() {
		return this.depositFigure;
	}

	public void setDepositFigure(Double depositFigure) {
		this.depositFigure = depositFigure;
	}

	@Column(name = "DEPOSIT_INCREASE", precision = 20)
	public Double getDepositIncrease() {
		return this.depositIncrease;
	}

	public void setDepositIncrease(Double depositIncrease) {
		this.depositIncrease = depositIncrease;
	}

	@Column(name = "CONT_MAKING_DATE", length = 7)
	public Date getContMakingDate() {
		return this.contMakingDate;
	}

	public void setContMakingDate(Date contMakingDate) {
		this.contMakingDate = contMakingDate;
	}

	@Column(name = "CONT_SAM_ACCEPT_DATE", length = 7)
	public Date getContSamAcceptDate() {
		return this.contSamAcceptDate;
	}

	public void setContSamAcceptDate(Date contSamAcceptDate) {
		this.contSamAcceptDate = contSamAcceptDate;
	}

	@Column(name = "CONT_SAM_TO_ASPM_DATE", length = 7)
	public Date getContSamToAspmDate() {
		return this.contSamToAspmDate;
	}

	public void setContSamToAspmDate(Date contSamToAspmDate) {
		this.contSamToAspmDate = contSamToAspmDate;
	}

	@Column(name = "CONT_SIGNATURE_DATE", length = 7)
	public Date getContSignatureDate() {
		return this.contSignatureDate;
	}

	public void setContSignatureDate(Date contSignatureDate) {
		this.contSignatureDate = contSignatureDate;
	}

	@Column(name = "CONT_TOT_SIGNATURE_DATE", length = 7)
	public Date getContTotSignatureDate() {
		return this.contTotSignatureDate;
	}

	public void setContTotSignatureDate(Date contTotSignatureDate) {
		this.contTotSignatureDate = contTotSignatureDate;
	}

	@Column(name = "CONT_ASPM_ACCEPT_DATE", length = 7)
	public Date getContAspmAcceptDate() {
		return this.contAspmAcceptDate;
	}

	public void setContAspmAcceptDate(Date contAspmAcceptDate) {
		this.contAspmAcceptDate = contAspmAcceptDate;
	}

	@Column(name = "CONT_SEND_TO_OWNER_DATE", length = 7)
	public Date getContSendToOwnerDate() {
		return this.contSendToOwnerDate;
	}

	public void setContSendToOwnerDate(Date contSendToOwnerDate) {
		this.contSendToOwnerDate = contSendToOwnerDate;
	}

	@Column(name = "CONT_ASPM_FILING_DATE", length = 7)
	public Date getContAspmFilingDate() {
		return this.contAspmFilingDate;
	}

	public void setContAspmFilingDate(Date contAspmFilingDate) {
		this.contAspmFilingDate = contAspmFilingDate;
	}

	@Column(name = "CONT_STORED_TYPE", length = 25)
	public String getContStoredType() {
		return this.contStoredType;
	}

	public void setContStoredType(String contStoredType) {
		this.contStoredType = contStoredType;
	}

	@Column(name = "SAP_VENDOR_AMT_RENTAL_Y1", precision = 20)
	public Double getSapVendorAmtRentalY1() {
		return this.sapVendorAmtRentalY1;
	}

	public void setSapVendorAmtRentalY1(Double sapVendorAmtRentalY1) {
		this.sapVendorAmtRentalY1 = sapVendorAmtRentalY1;
	}

	@Column(name = "SAP_VENDOR_AMT_RENTAL_Y2", precision = 20)
	public Double getSapVendorAmtRentalY2() {
		return this.sapVendorAmtRentalY2;
	}

	public void setSapVendorAmtRentalY2(Double sapVendorAmtRentalY2) {
		this.sapVendorAmtRentalY2 = sapVendorAmtRentalY2;
	}

	@Column(name = "SAP_VENDOR_AMT_RENTAL_Y3", precision = 20)
	public Double getSapVendorAmtRentalY3() {
		return this.sapVendorAmtRentalY3;
	}

	public void setSapVendorAmtRentalY3(Double sapVendorAmtRentalY3) {
		this.sapVendorAmtRentalY3 = sapVendorAmtRentalY3;
	}

	@Column(name = "SAP_WHT_AMT_RENTAL_Y1", precision = 20)
	public Double getSapWhtAmtRentalY1() {
		return this.sapWhtAmtRentalY1;
	}

	public void setSapWhtAmtRentalY1(Double sapWhtAmtRentalY1) {
		this.sapWhtAmtRentalY1 = sapWhtAmtRentalY1;
	}

	@Column(name = "SAP_WHT_AMT_RENTAL_Y2", precision = 20)
	public Double getSapWhtAmtRentalY2() {
		return this.sapWhtAmtRentalY2;
	}

	public void setSapWhtAmtRentalY2(Double sapWhtAmtRentalY2) {
		this.sapWhtAmtRentalY2 = sapWhtAmtRentalY2;
	}

	@Column(name = "SAP_WHT_AMT_RENTAL_Y3", precision = 20)
	public Double getSapWhtAmtRentalY3() {
		return this.sapWhtAmtRentalY3;
	}

	public void setSapWhtAmtRentalY3(Double sapWhtAmtRentalY3) {
		this.sapWhtAmtRentalY3 = sapWhtAmtRentalY3;
	}

	@Column(name = "SAP_VENDOR_AMT_SERVICE_Y1", precision = 20)
	public Double getSapVendorAmtServiceY1() {
		return this.sapVendorAmtServiceY1;
	}

	public void setSapVendorAmtServiceY1(Double sapVendorAmtServiceY1) {
		this.sapVendorAmtServiceY1 = sapVendorAmtServiceY1;
	}

	@Column(name = "SAP_VENDOR_AMT_SERVICE_Y2", precision = 20)
	public Double getSapVendorAmtServiceY2() {
		return this.sapVendorAmtServiceY2;
	}

	public void setSapVendorAmtServiceY2(Double sapVendorAmtServiceY2) {
		this.sapVendorAmtServiceY2 = sapVendorAmtServiceY2;
	}

	@Column(name = "SAP_VENDOR_AMT_SERVICE_Y3", precision = 20)
	public Double getSapVendorAmtServiceY3() {
		return this.sapVendorAmtServiceY3;
	}

	public void setSapVendorAmtServiceY3(Double sapVendorAmtServiceY3) {
		this.sapVendorAmtServiceY3 = sapVendorAmtServiceY3;
	}

	@Column(name = "SAP_WHT_AMT_SERVICE_Y1", precision = 20)
	public Double getSapWhtAmtServiceY1() {
		return this.sapWhtAmtServiceY1;
	}

	public void setSapWhtAmtServiceY1(Double sapWhtAmtServiceY1) {
		this.sapWhtAmtServiceY1 = sapWhtAmtServiceY1;
	}

	@Column(name = "SAP_WHT_AMT_SERVICE_Y2", precision = 20)
	public Double getSapWhtAmtServiceY2() {
		return this.sapWhtAmtServiceY2;
	}

	public void setSapWhtAmtServiceY2(Double sapWhtAmtServiceY2) {
		this.sapWhtAmtServiceY2 = sapWhtAmtServiceY2;
	}

	@Column(name = "SAP_WHT_AMT_SERVICE_Y3", precision = 20)
	public Double getSapWhtAmtServiceY3() {
		return this.sapWhtAmtServiceY3;
	}

	public void setSapWhtAmtServiceY3(Double sapWhtAmtServiceY3) {
		this.sapWhtAmtServiceY3 = sapWhtAmtServiceY3;
	}

	@Column(name = "CONTRACT_FILE_NAME", length = 100)
	public String getContractFileName() {
		return this.contractFileName;
	}

	public void setContractFileName(String contractFileName) {
		this.contractFileName = contractFileName;
	}

	@Column(name = "EXPORT_INSUR_STATUS", length = 30)
	public String getExportInsurStatus() {
		return this.exportInsurStatus;
	}

	public void setExportInsurStatus(String exportInsurStatus) {
		this.exportInsurStatus = exportInsurStatus;
	}

	@Column(name = "EL_METINF_ELECT_ZONE", length = 30)
	public String getElMetinfElectZone() {
		return this.elMetinfElectZone;
	}

	public void setElMetinfElectZone(String elMetinfElectZone) {
		this.elMetinfElectZone = elMetinfElectZone;
	}

	@Column(name = "EL_METINF_ELECT_ZONE_CODE", length = 30)
	public String getElMetinfElectZoneCode() {
		return this.elMetinfElectZoneCode;
	}

	public void setElMetinfElectZoneCode(String elMetinfElectZoneCode) {
		this.elMetinfElectZoneCode = elMetinfElectZoneCode;
	}

	@Column(name = "EL_METINF_ELECT_ZONE_BELONG", length = 30)
	public String getElMetinfElectZoneBelong() {
		return this.elMetinfElectZoneBelong;
	}

	public void setElMetinfElectZoneBelong(String elMetinfElectZoneBelong) {
		this.elMetinfElectZoneBelong = elMetinfElectZoneBelong;
	}

	@Column(name = "EL_METINF_ELECT_PAID_DATE", length = 7)
	public Date getElMetinfElectPaidDate() {
		return this.elMetinfElectPaidDate;
	}

	public void setElMetinfElectPaidDate(Date elMetinfElectPaidDate) {
		this.elMetinfElectPaidDate = elMetinfElectPaidDate;
	}

	@Column(name = "EL_METINF_METER_ID", length = 50)
	public String getElMetinfMeterId() {
		return this.elMetinfMeterId;
	}

	public void setElMetinfMeterId(String elMetinfMeterId) {
		this.elMetinfMeterId = elMetinfMeterId;
	}

	@Column(name = "EL_METINF_ELECTRIC_USERNAME", length = 50)
	public String getElMetinfElectricUsername() {
		return this.elMetinfElectricUsername;
	}

	public void setElMetinfElectricUsername(String elMetinfElectricUsername) {
		this.elMetinfElectricUsername = elMetinfElectricUsername;
	}

	@Column(name = "EL_METINF_ADAPTER_BRAND", length = 200)
	public String getElMetinfAdapterBrand() {
		return this.elMetinfAdapterBrand;
	}

	public void setElMetinfAdapterBrand(String elMetinfAdapterBrand) {
		this.elMetinfAdapterBrand = elMetinfAdapterBrand;
	}

	@Column(name = "EL_METINF_ADAPTER_SIZE", length = 50)
	public String getElMetinfAdapterSize() {
		return this.elMetinfAdapterSize;
	}

	public void setElMetinfAdapterSize(String elMetinfAdapterSize) {
		this.elMetinfAdapterSize = elMetinfAdapterSize;
	}

	@Column(name = "EL_METINF_METER_SIZE", length = 50)
	public String getElMetinfMeterSize() {
		return this.elMetinfMeterSize;
	}

	public void setElMetinfMeterSize(String elMetinfMeterSize) {
		this.elMetinfMeterSize = elMetinfMeterSize;
	}

	@Column(name = "EL_METINF_ADAPTER_SERIAL_NO", length = 50)
	public String getElMetinfAdapterSerialNo() {
		return this.elMetinfAdapterSerialNo;
	}

	public void setElMetinfAdapterSerialNo(String elMetinfAdapterSerialNo) {
		this.elMetinfAdapterSerialNo = elMetinfAdapterSerialNo;
	}

	@Column(name = "EL_METINF_ADAPTER_INSTALLDATE", length = 7)
	public Date getElMetinfAdapterInstalldate() {
		return this.elMetinfAdapterInstalldate;
	}

	public void setElMetinfAdapterInstalldate(Date elMetinfAdapterInstalldate) {
		this.elMetinfAdapterInstalldate = elMetinfAdapterInstalldate;
	}

	@Column(name = "EL_METINF_SAQM_MODEL_DATE", length = 7)
	public Date getElMetinfSaqmModelDate() {
		return this.elMetinfSaqmModelDate;
	}

	public void setElMetinfSaqmModelDate(Date elMetinfSaqmModelDate) {
		this.elMetinfSaqmModelDate = elMetinfSaqmModelDate;
	}

	@Column(name = "EL_METINF_SAQM_CONTRACT_DATE", length = 7)
	public Date getElMetinfSaqmContractDate() {
		return this.elMetinfSaqmContractDate;
	}

	public void setElMetinfSaqmContractDate(Date elMetinfSaqmContractDate) {
		this.elMetinfSaqmContractDate = elMetinfSaqmContractDate;
	}

	@Column(name = "EL_METINF_SEND_METER_DATE", length = 7)
	public Date getElMetinfSendMeterDate() {
		return this.elMetinfSendMeterDate;
	}

	public void setElMetinfSendMeterDate(Date elMetinfSendMeterDate) {
		this.elMetinfSendMeterDate = elMetinfSendMeterDate;
	}

	@Column(name = "EL_METINF_SEND_ELECTRIC_DATE", length = 7)
	public Date getElMetinfSendElectricDate() {
		return this.elMetinfSendElectricDate;
	}

	public void setElMetinfSendElectricDate(Date elMetinfSendElectricDate) {
		this.elMetinfSendElectricDate = elMetinfSendElectricDate;
	}

	@Column(name = "EL_METINF_ADDDATA_DATE", length = 7)
	public Date getElMetinfAdddataDate() {
		return this.elMetinfAdddataDate;
	}

	public void setElMetinfAdddataDate(Date elMetinfAdddataDate) {
		this.elMetinfAdddataDate = elMetinfAdddataDate;
	}

	@Column(name = "EL_METINF_REMARK", length = 500)
	public String getElMetinfRemark() {
		return this.elMetinfRemark;
	}

	public void setElMetinfRemark(String elMetinfRemark) {
		this.elMetinfRemark = elMetinfRemark;
	}

	@Column(name = "EL_METBG_NO_DEPOSIT_BG_1", length = 300)
	public String getElMetbgNoDepositBg1() {
		return this.elMetbgNoDepositBg1;
	}

	public void setElMetbgNoDepositBg1(String elMetbgNoDepositBg1) {
		this.elMetbgNoDepositBg1 = elMetbgNoDepositBg1;
	}

	@Column(name = "EL_METBG_BANK_BG_1", length = 300)
	public String getElMetbgBankBg1() {
		return this.elMetbgBankBg1;
	}

	public void setElMetbgBankBg1(String elMetbgBankBg1) {
		this.elMetbgBankBg1 = elMetbgBankBg1;
	}

	@Column(name = "EL_METBG_MEA_DEPOSIT_BG_1", length = 300)
	public String getElMetbgMeaDepositBg1() {
		return this.elMetbgMeaDepositBg1;
	}

	public void setElMetbgMeaDepositBg1(String elMetbgMeaDepositBg1) {
		this.elMetbgMeaDepositBg1 = elMetbgMeaDepositBg1;
	}

	@Column(name = "EL_METBG_INSURANCE_START_1", length = 7)
	public Date getElMetbgInsuranceStart1() {
		return this.elMetbgInsuranceStart1;
	}

	public void setElMetbgInsuranceStart1(Date elMetbgInsuranceStart1) {
		this.elMetbgInsuranceStart1 = elMetbgInsuranceStart1;
	}

	@Column(name = "EL_METBG_INSURANCE_END_1", length = 7)
	public Date getElMetbgInsuranceEnd1() {
		return this.elMetbgInsuranceEnd1;
	}

	public void setElMetbgInsuranceEnd1(Date elMetbgInsuranceEnd1) {
		this.elMetbgInsuranceEnd1 = elMetbgInsuranceEnd1;
	}

	@Column(name = "EL_METBG_RECEIVED_BG_DATE1", length = 7)
	public Date getElMetbgReceivedBgDate1() {
		return this.elMetbgReceivedBgDate1;
	}

	public void setElMetbgReceivedBgDate1(Date elMetbgReceivedBgDate1) {
		this.elMetbgReceivedBgDate1 = elMetbgReceivedBgDate1;
	}

	@Column(name = "EL_METBG_RETURN_TO_FND_DATE1", length = 7)
	public Date getElMetbgReturnToFndDate1() {
		return this.elMetbgReturnToFndDate1;
	}

	public void setElMetbgReturnToFndDate1(Date elMetbgReturnToFndDate1) {
		this.elMetbgReturnToFndDate1 = elMetbgReturnToFndDate1;
	}

	@Column(name = "EL_METBG_REMARK1", length = 500)
	public String getElMetbgRemark1() {
		return this.elMetbgRemark1;
	}

	public void setElMetbgRemark1(String elMetbgRemark1) {
		this.elMetbgRemark1 = elMetbgRemark1;
	}

	@Column(name = "EL_METBG_NO_DEPOSIT_BG_2", length = 300)
	public String getElMetbgNoDepositBg2() {
		return this.elMetbgNoDepositBg2;
	}

	public void setElMetbgNoDepositBg2(String elMetbgNoDepositBg2) {
		this.elMetbgNoDepositBg2 = elMetbgNoDepositBg2;
	}

	@Column(name = "EL_METBG_BANK_BG_2", length = 300)
	public String getElMetbgBankBg2() {
		return this.elMetbgBankBg2;
	}

	public void setElMetbgBankBg2(String elMetbgBankBg2) {
		this.elMetbgBankBg2 = elMetbgBankBg2;
	}

	@Column(name = "EL_METBG_MEA_DEPOSIT_BG_2", length = 300)
	public String getElMetbgMeaDepositBg2() {
		return this.elMetbgMeaDepositBg2;
	}

	public void setElMetbgMeaDepositBg2(String elMetbgMeaDepositBg2) {
		this.elMetbgMeaDepositBg2 = elMetbgMeaDepositBg2;
	}

	@Column(name = "EL_METBG_INSURANCE_START_2", length = 7)
	public Date getElMetbgInsuranceStart2() {
		return this.elMetbgInsuranceStart2;
	}

	public void setElMetbgInsuranceStart2(Date elMetbgInsuranceStart2) {
		this.elMetbgInsuranceStart2 = elMetbgInsuranceStart2;
	}

	@Column(name = "EL_METBG_INSURANCE_END_2", length = 7)
	public Date getElMetbgInsuranceEnd2() {
		return this.elMetbgInsuranceEnd2;
	}

	public void setElMetbgInsuranceEnd2(Date elMetbgInsuranceEnd2) {
		this.elMetbgInsuranceEnd2 = elMetbgInsuranceEnd2;
	}

	@Column(name = "EL_METBG_RECEIVED_BG_DATE2", length = 7)
	public Date getElMetbgReceivedBgDate2() {
		return this.elMetbgReceivedBgDate2;
	}

	public void setElMetbgReceivedBgDate2(Date elMetbgReceivedBgDate2) {
		this.elMetbgReceivedBgDate2 = elMetbgReceivedBgDate2;
	}

	@Column(name = "EL_METBG_RETURN_TO_FND_DATE2", length = 7)
	public Date getElMetbgReturnToFndDate2() {
		return this.elMetbgReturnToFndDate2;
	}

	public void setElMetbgReturnToFndDate2(Date elMetbgReturnToFndDate2) {
		this.elMetbgReturnToFndDate2 = elMetbgReturnToFndDate2;
	}

	@Column(name = "EL_METBG_REMARK2", length = 500)
	public String getElMetbgRemark2() {
		return this.elMetbgRemark2;
	}

	public void setElMetbgRemark2(String elMetbgRemark2) {
		this.elMetbgRemark2 = elMetbgRemark2;
	}

	@Column(name = "EL_METBG_ADDDATA_DATE", length = 7)
	public Date getElMetbgAdddataDate() {
		return this.elMetbgAdddataDate;
	}

	public void setElMetbgAdddataDate(Date elMetbgAdddataDate) {
		this.elMetbgAdddataDate = elMetbgAdddataDate;
	}

	@Column(name = "EL_METBG_CASH_FEE_1", precision = 20)
	public Double getElMetbgCashFee1() {
		return this.elMetbgCashFee1;
	}

	public void setElMetbgCashFee1(Double elMetbgCashFee1) {
		this.elMetbgCashFee1 = elMetbgCashFee1;
	}

	@Column(name = "EL_METBG_CASH_MEA_PAY_1", length = 7)
	public Date getElMetbgCashMeaPay1() {
		return this.elMetbgCashMeaPay1;
	}

	public void setElMetbgCashMeaPay1(Date elMetbgCashMeaPay1) {
		this.elMetbgCashMeaPay1 = elMetbgCashMeaPay1;
	}

	@Column(name = "EL_METBG_CASH_ASPD_PAY_1", length = 7)
	public Date getElMetbgCashAspdPay1() {
		return this.elMetbgCashAspdPay1;
	}

	public void setElMetbgCashAspdPay1(Date elMetbgCashAspdPay1) {
		this.elMetbgCashAspdPay1 = elMetbgCashAspdPay1;
	}

	@Column(name = "EL_METBG_CASH_REMARK_1", length = 200)
	public String getElMetbgCashRemark1() {
		return this.elMetbgCashRemark1;
	}

	public void setElMetbgCashRemark1(String elMetbgCashRemark1) {
		this.elMetbgCashRemark1 = elMetbgCashRemark1;
	}

	@Column(name = "EL_METBG_CASH_FEE_2", precision = 20)
	public Double getElMetbgCashFee2() {
		return this.elMetbgCashFee2;
	}

	public void setElMetbgCashFee2(Double elMetbgCashFee2) {
		this.elMetbgCashFee2 = elMetbgCashFee2;
	}

	@Column(name = "EL_METBG_CASH_MEA_PAY_2", length = 7)
	public Date getElMetbgCashMeaPay2() {
		return this.elMetbgCashMeaPay2;
	}

	public void setElMetbgCashMeaPay2(Date elMetbgCashMeaPay2) {
		this.elMetbgCashMeaPay2 = elMetbgCashMeaPay2;
	}

	@Column(name = "EL_METBG_CASH_ASPD_PAY_2", length = 7)
	public Date getElMetbgCashAspdPay2() {
		return this.elMetbgCashAspdPay2;
	}

	public void setElMetbgCashAspdPay2(Date elMetbgCashAspdPay2) {
		this.elMetbgCashAspdPay2 = elMetbgCashAspdPay2;
	}

	@Column(name = "EL_METBG_CASH_REMARK_2", length = 200)
	public String getElMetbgCashRemark2() {
		return this.elMetbgCashRemark2;
	}

	public void setElMetbgCashRemark2(String elMetbgCashRemark2) {
		this.elMetbgCashRemark2 = elMetbgCashRemark2;
	}

	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "LAST_UPDATE_USER", length = 150)
	public String getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	@Column(name = "RENTAL_WHT_CODE", length = 10)
	public String getRentalWhtCode() {
		return this.rentalWhtCode;
	}

	public void setRentalWhtCode(String rentalWhtCode) {
		this.rentalWhtCode = rentalWhtCode;
	}

	@Column(name = "SERVICE_WHT_CODE", length = 10)
	public String getServiceWhtCode() {
		return this.serviceWhtCode;
	}

	public void setServiceWhtCode(String serviceWhtCode) {
		this.serviceWhtCode = serviceWhtCode;
	}

	@Column(name = "DEPOSIT_REMARK", length = 300)
	public String getDepositRemark() {
		return this.depositRemark;
	}

	public void setDepositRemark(String depositRemark) {
		this.depositRemark = depositRemark;
	}

	@Column(name = "RENEW_STATUS", length = 50)
	public String getRenewStatus() {
		return this.renewStatus;
	}

	public void setRenewStatus(String renewStatus) {
		this.renewStatus = renewStatus;
	}

	@Column(name = "OLD_LOCATION_NAME", length = 300)
	public String getOldLocationName() {
		return this.oldLocationName;
	}

	public void setOldLocationName(String oldLocationName) {
		this.oldLocationName = oldLocationName;
	}

	@Column(name = "CONTRACT_PROVINCE", length = 50)
	public String getContractProvince() {
		return this.contractProvince;
	}

	public void setContractProvince(String contractProvince) {
		this.contractProvince = contractProvince;
	}

	@Column(name = "PARENT_CONTRACT", length = 25)
	public String getParentContract() {
		return this.parentContract;
	}

	public void setParentContract(String parentContract) {
		this.parentContract = parentContract;
	}

	@Column(name = "DEPOSITE_VAT_TYPE", length = 25)
	public String getDepositeVatType() {
		return this.depositeVatType;
	}

	public void setDepositeVatType(String depositeVatType) {
		this.depositeVatType = depositeVatType;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "METER_INFO_STATUS", length = 25)
	public String getMeterInfoStatus() {
		return this.meterInfoStatus;
	}

	public void setMeterInfoStatus(String meterInfoStatus) {
		this.meterInfoStatus = meterInfoStatus;
	}

	@Column(name = "INSURANCE_STATUS", length = 25)
	public String getInsuranceStatus() {
		return this.insuranceStatus;
	}

	public void setInsuranceStatus(String insuranceStatus) {
		this.insuranceStatus = insuranceStatus;
	}

	@Column(name = "TIME_ENTRY")
	public String getTimeEntry() {
		return this.timeEntry;
	}

	public void setTimeEntry(String timeEntry) {
		this.timeEntry = timeEntry;
	}

	@Column(name = "ELEC_PERMISSION", length = 50)
	public String getElecPermission() {
		return this.elecPermission;
	}

	public void setElecPermission(String elecPermission) {
		this.elecPermission = elecPermission;
	}

	@Column(name = "OTHER_CONDITION")
	public String getOtherCondition() {
		return this.otherCondition;
	}

	public void setOtherCondition(String otherCondition) {
		this.otherCondition = otherCondition;
	}

	@Column(name = "CM_METER_TYPE", length = 200)
	public String getCmMeterType() {
		return this.cmMeterType;
	}

	public void setCmMeterType(String cmMeterType) {
		this.cmMeterType = cmMeterType;
	}

	@Column(name = "CM_SAVE_ENERGY", length = 200)
	public String getCmSaveEnergy() {
		return this.cmSaveEnergy;
	}

	public void setCmSaveEnergy(String cmSaveEnergy) {
		this.cmSaveEnergy = cmSaveEnergy;
	}

	@Column(name = "DEPOSIT_S_FIGURE", precision = 20, scale = 0)
	public Double getDepositSFigure() {
		return this.depositSFigure;
	}

	public void setDepositSFigure(Double depositSFigure) {
		this.depositSFigure = depositSFigure;
	}

	@Column(name = "DEPOSIT_S_TYPE", length = 25)
	public String getDepositSType() {
		return this.depositSType;
	}

	public void setDepositSType(String depositSType) {
		this.depositSType = depositSType;
	}

	@Column(name = "DEPOSIT_S_VATTYPE", length = 20)
	public String getDepositSVattype() {
		return this.depositSVattype;
	}

	public void setDepositSVattype(String depositSVattype) {
		this.depositSVattype = depositSVattype;
	}

	@Column(name = "EL_METINF_METER_PHASE", length = 50)
	public String getElMetinfMeterPhase() {
		return this.elMetinfMeterPhase;
	}

	public void setElMetinfMeterPhase(String elMetinfMeterPhase) {
		this.elMetinfMeterPhase = elMetinfMeterPhase;
	}

	@Column(name = "LAST_UPDATE_METER_USER", length = 150)
	public String getLastUpdateMeterUser() {
		return this.lastUpdateMeterUser;
	}

	public void setLastUpdateMeterUser(String lastUpdateMeterUser) {
		this.lastUpdateMeterUser = lastUpdateMeterUser;
	}

	@Column(name = "LAST_UPDATE_METER_DATE", length = 7)
	public Date getLastUpdateMeterDate() {
		return this.lastUpdateMeterDate;
	}

	public void setLastUpdateMeterDate(Date lastUpdateMeterDate) {
		this.lastUpdateMeterDate = lastUpdateMeterDate;
	}

	@Column(name = "EL_METINF_METER_ID2", length = 50)
	public String getElMetinfMeterId2() {
		return this.elMetinfMeterId2;
	}

	public void setElMetinfMeterId2(String elMetinfMeterId2) {
		this.elMetinfMeterId2 = elMetinfMeterId2;
	}

	@Column(name = "EL_METBG_RECEIPT", length = 70)
	public String getElMetbgReceipt() {
		return this.elMetbgReceipt;
	}

	public void setElMetbgReceipt(String elMetbgReceipt) {
		this.elMetbgReceipt = elMetbgReceipt;
	}

	@Column(name = "EL_METBG_RECEIPT_DATE", length = 7)
	public Date getElMetbgReceiptDate() {
		return this.elMetbgReceiptDate;
	}

	public void setElMetbgReceiptDate(Date elMetbgReceiptDate) {
		this.elMetbgReceiptDate = elMetbgReceiptDate;
	}

	@Column(name = "PREV_CONTRACT_ID", length = 25)
	public String getPrevContractId() {
		return this.prevContractId;
	}

	public void setPrevContractId(String prevContractId) {
		this.prevContractId = prevContractId;
	}

	@Column(name = "NEXT_CONTRACT_ID", length = 1000)
	public String getNextContractId() {
		return this.nextContractId;
	}

	public void setNextContractId(String nextContractId) {
		this.nextContractId = nextContractId;
	}

	@Column(name = "CONTRACT_ORDER", length = 50)
	public String getContractOrder() {
		return this.contractOrder;
	}

	public void setContractOrder(String contractOrder) {
		this.contractOrder = contractOrder;
	}

	@Column(name = "FLAG_TRF_METER", length = 1)
	public Character getFlagTrfMeter() {
		return this.flagTrfMeter;
	}

	public void setFlagTrfMeter(Character flagTrfMeter) {
		this.flagTrfMeter = flagTrfMeter;
	}

	@Column(name = "OGN_TRF_METER_DATE", length = 7)
	public Date getOgnTrfMeterDate() {
		return this.ognTrfMeterDate;
	}

	public void setOgnTrfMeterDate(Date ognTrfMeterDate) {
		this.ognTrfMeterDate = ognTrfMeterDate;
	}

	@Column(name = "DST_TRF_METER_DATE", length = 7)
	public Date getDstTrfMeterDate() {
		return this.dstTrfMeterDate;
	}

	public void setDstTrfMeterDate(Date dstTrfMeterDate) {
		this.dstTrfMeterDate = dstTrfMeterDate;
	}

	@Column(name = "RENTAL_GL", length = 20)
	public String getRentalGl() {
		return this.rentalGl;
	}

	public void setRentalGl(String rentalGl) {
		this.rentalGl = rentalGl;
	}

	@Column(name = "TRF_METER_ID", length = 50)
	public String getTrfMeterId() {
		return this.trfMeterId;
	}

	public void setTrfMeterId(String trfMeterId) {
		this.trfMeterId = trfMeterId;
	}

	@Column(name = "SEM_REMARK", length = 1000)
	public String getSemRemark() {
		return this.semRemark;
	}

	public void setSemRemark(String semRemark) {
		this.semRemark = semRemark;
	}

	@Column(name = "SEM_UPDATE_REMARK", length = 1000)
	public String getSemUpdateRemark() {
		return this.semUpdateRemark;
	}

	public void setSemUpdateRemark(String semUpdateRemark) {
		this.semUpdateRemark = semUpdateRemark;
	}

	@Column(name = "EL_METINF_METER_ID3", length = 50)
	public String getElMetinfMeterId3() {
		return this.elMetinfMeterId3;
	}

	public void setElMetinfMeterId3(String elMetinfMeterId3) {
		this.elMetinfMeterId3 = elMetinfMeterId3;
	}

	@Column(name = "SEM_OWNER_NAME_IN_CONTRACT_1", length = 300)
	public String getSemOwnerNameInContract1() {
		return this.semOwnerNameInContract1;
	}

	public void setSemOwnerNameInContract1(String semOwnerNameInContract1) {
		this.semOwnerNameInContract1 = semOwnerNameInContract1;
	}

	@Column(name = "SEM_OWNER_NAME_IN_CONTRACT_2", length = 300)
	public String getSemOwnerNameInContract2() {
		return this.semOwnerNameInContract2;
	}

	public void setSemOwnerNameInContract2(String semOwnerNameInContract2) {
		this.semOwnerNameInContract2 = semOwnerNameInContract2;
	}

	@Column(name = "SEM_OWNER_NAME_IN_CONTRACT_R", length = 300)
	public String getSemOwnerNameInContractR() {
		return this.semOwnerNameInContractR;
	}

	public void setSemOwnerNameInContractR(String semOwnerNameInContractR) {
		this.semOwnerNameInContractR = semOwnerNameInContractR;
	}
	
}
