package com.ais.migrate.sem.hibernate.annotion;

// Generated 30 ¾.Â. 2553, 10:08:55 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SemElMeterInfo generated by hbm2java
 */
@Entity
@Table(name = "SEM_EL_METER_INFO")
public class SemElMeterInfo implements java.io.Serializable {

	private String meterInfoId;
	private String electricId;
	private String electricUseType;
	private String referMeterId;
	private String meterId;
	private String EOldMeterId;
	private String EAreaCode;
	private String EAreaName;
	private String EMeterRate;
	private String EMeterSize;
	private String EMeterWire;
	private Date EOnMeterDt;
	private Date EOneBillDt;
	private String ETransformerLabel;
	private String ETransformerType;
	private String ETransformerSize;
	private String ETransformerSerial;
	private Date ETransformerDt;
	private String ECheckArea;
	private String EMeterType;
	private String PMeterOwnerName;
	private String PAreaName;
	private String PMeterAddress;
	private BigDecimal PMeterUnitPrice;
	private String PMeterVatType;
	private BigDecimal PFirstKwh;
	private String PMeterStatus;
	private Date POnMeterDt;
	private Date POffMeterDt;
	private String PMeterRemark;
	private String oneBillFlag;
	private String oneBillAddFlag;
	private String oneBillRemark;
	private Date uploadMeterDt;
	private String firstPaidFlag;
	private String outstandingFlag;
	private Long version;
	private String recordStatus;
	private String createBy;
	private Date createDt;
	private String updateBy;
	private Date updateDt;

	public SemElMeterInfo() {
	}

	public SemElMeterInfo(String meterInfoId, String electricId) {
		this.meterInfoId = meterInfoId;
		this.electricId = electricId;
	}

	public SemElMeterInfo(String meterInfoId, String electricId,
			String electricUseType, String referMeterId, String meterId,
			String EOldMeterId, String EAreaCode, String EAreaName,
			String EMeterRate, String EMeterSize, String EMeterWire,
			Date EOnMeterDt, Date EOneBillDt, String ETransformerLabel,
			String ETransformerType, String ETransformerSize,
			String ETransformerSerial, Date ETransformerDt, String ECheckArea,
			String EMeterType, String PMeterOwnerName, String PAreaName,
			String PMeterAddress, BigDecimal PMeterUnitPrice,
			String PMeterVatType, BigDecimal PFirstKwh, String PMeterStatus,
			Date POnMeterDt, Date POffMeterDt, String PMeterRemark,
			String oneBillFlag, String oneBillAddFlag, String oneBillRemark,
			Date uploadMeterDt, String firstPaidFlag, String outstandingFlag,
			Long version, String recordStatus, String createBy, Date createDt,
			String updateBy, Date updateDt) {
		this.meterInfoId = meterInfoId;
		this.electricId = electricId;
		this.electricUseType = electricUseType;
		this.referMeterId = referMeterId;
		this.meterId = meterId;
		this.EOldMeterId = EOldMeterId;
		this.EAreaCode = EAreaCode;
		this.EAreaName = EAreaName;
		this.EMeterRate = EMeterRate;
		this.EMeterSize = EMeterSize;
		this.EMeterWire = EMeterWire;
		this.EOnMeterDt = EOnMeterDt;
		this.EOneBillDt = EOneBillDt;
		this.ETransformerLabel = ETransformerLabel;
		this.ETransformerType = ETransformerType;
		this.ETransformerSize = ETransformerSize;
		this.ETransformerSerial = ETransformerSerial;
		this.ETransformerDt = ETransformerDt;
		this.ECheckArea = ECheckArea;
		this.EMeterType = EMeterType;
		this.PMeterOwnerName = PMeterOwnerName;
		this.PAreaName = PAreaName;
		this.PMeterAddress = PMeterAddress;
		this.PMeterUnitPrice = PMeterUnitPrice;
		this.PMeterVatType = PMeterVatType;
		this.PFirstKwh = PFirstKwh;
		this.PMeterStatus = PMeterStatus;
		this.POnMeterDt = POnMeterDt;
		this.POffMeterDt = POffMeterDt;
		this.PMeterRemark = PMeterRemark;
		this.oneBillFlag = oneBillFlag;
		this.oneBillAddFlag = oneBillAddFlag;
		this.oneBillRemark = oneBillRemark;
		this.uploadMeterDt = uploadMeterDt;
		this.firstPaidFlag = firstPaidFlag;
		this.outstandingFlag = outstandingFlag;
		this.version = version;
		this.recordStatus = recordStatus;
		this.createBy = createBy;
		this.createDt = createDt;
		this.updateBy = updateBy;
		this.updateDt = updateDt;
	}

	@Id
	@Column(name = "METER_INFO_ID", unique = true, nullable = false, length = 50)
	public String getMeterInfoId() {
		return this.meterInfoId;
	}

	public void setMeterInfoId(String meterInfoId) {
		this.meterInfoId = meterInfoId;
	}

	@Column(name = "ELECTRIC_ID", nullable = false, length = 50)
	public String getElectricId() {
		return this.electricId;
	}

	public void setElectricId(String electricId) {
		this.electricId = electricId;
	}

	@Column(name = "ELECTRIC_USE_TYPE", length = 20)
	public String getElectricUseType() {
		return this.electricUseType;
	}

	public void setElectricUseType(String electricUseType) {
		this.electricUseType = electricUseType;
	}

	@Column(name = "REFER_METER_ID", length = 50)
	public String getReferMeterId() {
		return this.referMeterId;
	}

	public void setReferMeterId(String referMeterId) {
		this.referMeterId = referMeterId;
	}

	@Column(name = "METER_ID", length = 20)
	public String getMeterId() {
		return this.meterId;
	}

	public void setMeterId(String meterId) {
		this.meterId = meterId;
	}

	@Column(name = "E_OLD_METER_ID", length = 20)
	public String getEOldMeterId() {
		return this.EOldMeterId;
	}

	public void setEOldMeterId(String EOldMeterId) {
		this.EOldMeterId = EOldMeterId;
	}

	@Column(name = "E_AREA_CODE", length = 20)
	public String getEAreaCode() {
		return this.EAreaCode;
	}

	public void setEAreaCode(String EAreaCode) {
		this.EAreaCode = EAreaCode;
	}

	@Column(name = "E_AREA_NAME", length = 50)
	public String getEAreaName() {
		return this.EAreaName;
	}

	public void setEAreaName(String EAreaName) {
		this.EAreaName = EAreaName;
	}

	@Column(name = "E_METER_RATE", length = 10)
	public String getEMeterRate() {
		return this.EMeterRate;
	}

	public void setEMeterRate(String EMeterRate) {
		this.EMeterRate = EMeterRate;
	}

	@Column(name = "E_METER_SIZE", length = 50)
	public String getEMeterSize() {
		return this.EMeterSize;
	}

	public void setEMeterSize(String EMeterSize) {
		this.EMeterSize = EMeterSize;
	}

	@Column(name = "E_METER_WIRE", length = 50)
	public String getEMeterWire() {
		return this.EMeterWire;
	}

	public void setEMeterWire(String EMeterWire) {
		this.EMeterWire = EMeterWire;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E_ON_METER_DT", length = 7)
	public Date getEOnMeterDt() {
		return this.EOnMeterDt;
	}

	public void setEOnMeterDt(Date EOnMeterDt) {
		this.EOnMeterDt = EOnMeterDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E_ONE_BILL_DT", length = 7)
	public Date getEOneBillDt() {
		return this.EOneBillDt;
	}

	public void setEOneBillDt(Date EOneBillDt) {
		this.EOneBillDt = EOneBillDt;
	}

	@Column(name = "E_TRANSFORMER_LABEL", length = 50)
	public String getETransformerLabel() {
		return this.ETransformerLabel;
	}

	public void setETransformerLabel(String ETransformerLabel) {
		this.ETransformerLabel = ETransformerLabel;
	}

	@Column(name = "E_TRANSFORMER_TYPE", length = 20)
	public String getETransformerType() {
		return this.ETransformerType;
	}

	public void setETransformerType(String ETransformerType) {
		this.ETransformerType = ETransformerType;
	}

	@Column(name = "E_TRANSFORMER_SIZE", length = 20)
	public String getETransformerSize() {
		return this.ETransformerSize;
	}

	public void setETransformerSize(String ETransformerSize) {
		this.ETransformerSize = ETransformerSize;
	}

	@Column(name = "E_TRANSFORMER_SERIAL", length = 50)
	public String getETransformerSerial() {
		return this.ETransformerSerial;
	}

	public void setETransformerSerial(String ETransformerSerial) {
		this.ETransformerSerial = ETransformerSerial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "E_TRANSFORMER_DT", length = 7)
	public Date getETransformerDt() {
		return this.ETransformerDt;
	}

	public void setETransformerDt(Date ETransformerDt) {
		this.ETransformerDt = ETransformerDt;
	}

	@Column(name = "E_CHECK_AREA", length = 1)
	public String getECheckArea() {
		return this.ECheckArea;
	}

	public void setECheckArea(String ECheckArea) {
		this.ECheckArea = ECheckArea;
	}

	@Column(name = "E_METER_TYPE", length = 20)
	public String getEMeterType() {
		return this.EMeterType;
	}

	public void setEMeterType(String EMeterType) {
		this.EMeterType = EMeterType;
	}

	@Column(name = "P_METER_OWNER_NAME", length = 100)
	public String getPMeterOwnerName() {
		return this.PMeterOwnerName;
	}

	public void setPMeterOwnerName(String PMeterOwnerName) {
		this.PMeterOwnerName = PMeterOwnerName;
	}

	@Column(name = "P_AREA_NAME", length = 50)
	public String getPAreaName() {
		return this.PAreaName;
	}

	public void setPAreaName(String PAreaName) {
		this.PAreaName = PAreaName;
	}

	@Column(name = "P_METER_ADDRESS", length = 200)
	public String getPMeterAddress() {
		return this.PMeterAddress;
	}

	public void setPMeterAddress(String PMeterAddress) {
		this.PMeterAddress = PMeterAddress;
	}

	@Column(name = "P_METER_UNIT_PRICE", precision = 15)
	public BigDecimal getPMeterUnitPrice() {
		return this.PMeterUnitPrice;
	}

	public void setPMeterUnitPrice(BigDecimal PMeterUnitPrice) {
		this.PMeterUnitPrice = PMeterUnitPrice;
	}

	@Column(name = "P_METER_VAT_TYPE", length = 20)
	public String getPMeterVatType() {
		return this.PMeterVatType;
	}

	public void setPMeterVatType(String PMeterVatType) {
		this.PMeterVatType = PMeterVatType;
	}

	@Column(name = "P_FIRST_KWH", precision = 22, scale = 0)
	public BigDecimal getPFirstKwh() {
		return this.PFirstKwh;
	}

	public void setPFirstKwh(BigDecimal PFirstKwh) {
		this.PFirstKwh = PFirstKwh;
	}

	@Column(name = "P_METER_STATUS", length = 20)
	public String getPMeterStatus() {
		return this.PMeterStatus;
	}

	public void setPMeterStatus(String PMeterStatus) {
		this.PMeterStatus = PMeterStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "P_ON_METER_DT", length = 7)
	public Date getPOnMeterDt() {
		return this.POnMeterDt;
	}

	public void setPOnMeterDt(Date POnMeterDt) {
		this.POnMeterDt = POnMeterDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "P_OFF_METER_DT", length = 7)
	public Date getPOffMeterDt() {
		return this.POffMeterDt;
	}

	public void setPOffMeterDt(Date POffMeterDt) {
		this.POffMeterDt = POffMeterDt;
	}

	@Column(name = "P_METER_REMARK", length = 1000)
	public String getPMeterRemark() {
		return this.PMeterRemark;
	}

	public void setPMeterRemark(String PMeterRemark) {
		this.PMeterRemark = PMeterRemark;
	}

	@Column(name = "ONE_BILL_FLAG", length = 1)
	public String getOneBillFlag() {
		return this.oneBillFlag;
	}

	public void setOneBillFlag(String oneBillFlag) {
		this.oneBillFlag = oneBillFlag;
	}

	@Column(name = "ONE_BILL_ADD_FLAG", length = 1)
	public String getOneBillAddFlag() {
		return this.oneBillAddFlag;
	}

	public void setOneBillAddFlag(String oneBillAddFlag) {
		this.oneBillAddFlag = oneBillAddFlag;
	}

	@Column(name = "ONE_BILL_REMARK", length = 500)
	public String getOneBillRemark() {
		return this.oneBillRemark;
	}

	public void setOneBillRemark(String oneBillRemark) {
		this.oneBillRemark = oneBillRemark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOAD_METER_DT", length = 7)
	public Date getUploadMeterDt() {
		return this.uploadMeterDt;
	}

	public void setUploadMeterDt(Date uploadMeterDt) {
		this.uploadMeterDt = uploadMeterDt;
	}

	@Column(name = "FIRST_PAID_FLAG", length = 1)
	public String getFirstPaidFlag() {
		return this.firstPaidFlag;
	}

	public void setFirstPaidFlag(String firstPaidFlag) {
		this.firstPaidFlag = firstPaidFlag;
	}

	@Column(name = "OUTSTANDING_FLAG", length = 1)
	public String getOutstandingFlag() {
		return this.outstandingFlag;
	}

	public void setOutstandingFlag(String outstandingFlag) {
		this.outstandingFlag = outstandingFlag;
	}

	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "RECORD_STATUS", length = 1)
	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "CREATE_BY", length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DT", length = 7)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "UPDATE_BY", length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DT", length = 7)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

}
