package th.co.ais.domain.common;

// Generated Nov 11, 2014 4:08:47 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SemCtForMenuId generated by hbm2java
 */
@Embeddable
public class SemCtForMenuId implements java.io.Serializable {

	private String menuLevel;
	private String menuLabel;
	private String menuUrl;
	private BigDecimal recordCount;

	public SemCtForMenuId() {
	}

	public SemCtForMenuId(String menuLevel, String menuLabel, String menuUrl,
			BigDecimal recordCount) {
		this.menuLevel = menuLevel;
		this.menuLabel = menuLabel;
		this.menuUrl = menuUrl;
		this.recordCount = recordCount;
	}

	@Column(name = "MENU_LEVEL", length = 10)
	public String getMenuLevel() {
		return this.menuLevel;
	}

	public void setMenuLevel(String menuLevel) {
		this.menuLevel = menuLevel;
	}

	@Column(name = "MENU_LABEL", length = 100)
	public String getMenuLabel() {
		return this.menuLabel;
	}

	public void setMenuLabel(String menuLabel) {
		this.menuLabel = menuLabel;
	}

	@Column(name = "MENU_URL", length = 100)
	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	@Column(name = "RECORD_COUNT", precision = 22, scale = 0)
	public BigDecimal getRecordCount() {
		return this.recordCount;
	}

	public void setRecordCount(BigDecimal recordCount) {
		this.recordCount = recordCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SemCtForMenuId))
			return false;
		SemCtForMenuId castOther = (SemCtForMenuId) other;

		return ((this.getMenuLevel() == castOther.getMenuLevel()) || (this
				.getMenuLevel() != null
				&& castOther.getMenuLevel() != null && this.getMenuLevel()
				.equals(castOther.getMenuLevel())))
				&& ((this.getMenuLabel() == castOther.getMenuLabel()) || (this
						.getMenuLabel() != null
						&& castOther.getMenuLabel() != null && this
						.getMenuLabel().equals(castOther.getMenuLabel())))
				&& ((this.getMenuUrl() == castOther.getMenuUrl()) || (this
						.getMenuUrl() != null
						&& castOther.getMenuUrl() != null && this.getMenuUrl()
						.equals(castOther.getMenuUrl())))
				&& ((this.getRecordCount() == castOther.getRecordCount()) || (this
						.getRecordCount() != null
						&& castOther.getRecordCount() != null && this
						.getRecordCount().equals(castOther.getRecordCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMenuLevel() == null ? 0 : this.getMenuLevel().hashCode());
		result = 37 * result
				+ (getMenuLabel() == null ? 0 : this.getMenuLabel().hashCode());
		result = 37 * result
				+ (getMenuUrl() == null ? 0 : this.getMenuUrl().hashCode());
		result = 37
				* result
				+ (getRecordCount() == null ? 0 : this.getRecordCount()
						.hashCode());
		return result;
	}

}
