package th.co.ais.domain.common;
// Generated Nov 11, 2014 4:08:47 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SemCtForMenu generated by hbm2java
 */
@Entity
@Table(name = "SEM_CT_FOR_MENU")
public class SemCtForMenu implements java.io.Serializable {

	private SemCtForMenuId id;

	public SemCtForMenu() {
	}

	public SemCtForMenu(SemCtForMenuId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "menuLevel", column = @Column(name = "MENU_LEVEL", length = 10)),
			@AttributeOverride(name = "menuLabel", column = @Column(name = "MENU_LABEL", length = 100)),
			@AttributeOverride(name = "menuUrl", column = @Column(name = "MENU_URL", length = 100)),
			@AttributeOverride(name = "recordCount", column = @Column(name = "RECORD_COUNT", precision = 22, scale = 0)) })
	public SemCtForMenuId getId() {
		return this.id;
	}

	public void setId(SemCtForMenuId id) {
		this.id = id;
	}

}
