package th.co.ais.domain.sap;

// Generated Nov 10, 2010 6:44:03 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SapTrxDtlId generated by hbm2java
 */
@Embeddable
public class SapTrxDtlId implements java.io.Serializable {

	private static final long serialVersionUID = -8306877900718620280L;
	private Integer logid;
	private String hearun;
	private String linitm;

	public SapTrxDtlId() {
	}

	public SapTrxDtlId(Integer logid, String hearun, String linitm) {
		this.logid = logid;
		this.hearun = hearun;
		this.linitm = linitm;
	}

	@Column(name = "LOGID", nullable = false, precision = 22, scale = 0)
	public Integer getLogid() {
		return this.logid;
	}

	public void setLogid(Integer logid) {
		this.logid = logid;
	}

	@Column(name = "HEARUN", nullable = false, length = 4)
	public String getHearun() {
		return this.hearun;
	}

	public void setHearun(String hearun) {
		this.hearun = hearun;
	}

	@Column(name = "LINITM", nullable = false, length = 3)
	public String getLinitm() {
		return this.linitm;
	}

	public void setLinitm(String linitm) {
		this.linitm = linitm;
	}

}
