package th.co.ais.domain.sap;

// Generated Nov 8, 2010 10:05:43 AM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import th.co.ais.domain.AbstractDomain;

/**
 * SapTrxLogId generated by hbm2java
 */
@Entity
@Table(name="SAP_TRX_LOG", schema="SEM")
public class SapTrxLog extends AbstractDomain {

	private static final long serialVersionUID = -852854320289546752L;
	
	private String rowId;
	private Integer logid;
	private String company;
	private String fileName;
	private String status;
	private String error;
	private Integer dbCount;
	private Double dbAmount;
	private Integer txtCount;
	private Double txtAmount;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private Long version;

	private boolean selected;
	private boolean disableCheckBox;
	private List<SapTrxHdr> sapTrxHdrs;
	
	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "SAP_TRX_LOG_ID", unique=true, nullable=false, insertable=false, updatable=false)
	public String getRowId() {
		return rowId;
	}

	public void setRowId(String rowId) {
		this.rowId = rowId;
	}

	@Column(name = "LOGID", nullable = false)
	public Integer getLogid() {
		return this.logid;
	}

	public void setLogid(Integer logid) {
		this.logid = logid;
	}

	@Column(name = "COMPANY")
	public String getCompany() {
		return company;
	}
	
	public void setCompany(String company) {
		this.company = company;
	}
	
	@Column(name = "FILE_NAME", nullable = false, length=100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "STATUS", length=10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ERROR")
	public String getError() {
		return this.error;
	}

	public void setError(String error) {
		this.error = error;
	}

	@Column(name = "DB_COUNT", precision = 22, scale = 0)
	public Integer getDbCount() {
		return this.dbCount;
	}

	public void setDbCount(Integer dbCount) {
		this.dbCount = dbCount;
	}

	@Column(name = "DB_AMOUNT", precision = 18)
	public Double getDbAmount() {
		return this.dbAmount;
	}

	public void setDbAmount(Double dbAmount) {
		this.dbAmount = dbAmount;
	}

	@Column(name = "TXT_COUNT", precision = 22, scale = 0)
	public Integer getTxtCount() {
		return this.txtCount;
	}

	public void setTxtCount(Integer txtCount) {
		this.txtCount = txtCount;
	}

	@Column(name = "TXT_AMOUNT", precision = 18)
	public Double getTxtAmount() {
		return this.txtAmount;
	}

	public void setTxtAmount(Double txtAmount) {
		this.txtAmount = txtAmount;
	}
	
	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Override
	@Column(name="CREATE_BY")
	public String getCreateBy() {
		return this.createBy;
	}
	@Override
	@Column(name="CREATE_DT")
	public Date getCreateDt() {
		return this.createDt;
	}

	@Override
	@Column(name="UPDATE_BY")
	public String getUpdateBy() {
		return this.updateBy;
	}

	@Override
	@Column(name="UPDATE_DT")
	public Date getUpdateDt() {
		return this.updateDt;
	}
	
	@Override
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
		
	}

	@Override
	public void setCreateDt(Date createDt) {
		this.createDt = createDt;		
	}

	@Override
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy; 
		
	}

	@Override
	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
		
	}

	/**
	 * Constructor
	 */
	public SapTrxLog() {}

	public SapTrxLog(Integer logid, String fileName, Date createDt, String createBy) {
		this.logid = logid;
		this.fileName = fileName;
		this.createDt = createDt;
		this.createBy = createBy;
	}
	public SapTrxLog(Integer logid, String fileName, String status,
			String error, Integer dbCount, Double dbAmount,
			Integer txtCount, Double txtAmount, Date createDt,
			String createBy, Date updateDt, String updateBy, Long version) {
		this.logid = logid;
		this.fileName = fileName;
		this.status = status;
		this.error = error;
		this.dbCount = dbCount;
		this.dbAmount = dbAmount;
		this.txtCount = txtCount;
		this.txtAmount = txtAmount;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
		this.version = version;
	}

	@Transient
	public boolean isSelected() {
		return selected;
	}
	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	@Transient
	public List<SapTrxHdr> getSapTrxHdrs() {
		return sapTrxHdrs;
	}

	public void setSapTrxHdrs(List<SapTrxHdr> sapTrxHdrs) {
		this.sapTrxHdrs = sapTrxHdrs;
	}
	
	@Transient
	public boolean isDisableCheckBox() {
		return disableCheckBox;//!"FAIL".equals(status);
	}
	
	public void setDisableCheckBox(boolean disableCheckBox) {
		this.disableCheckBox = disableCheckBox;
	}

	public enum E_STATUS{
		SUCCESS("SUCCESS"),
		FAIL("FAIL"),
		CANCEL("CANCEL"),
		ERROR("ERROR");
		
		public String name = "";		
		E_STATUS(String name) { this.name = name;}
	}
}
