package th.co.ais.domain.sap;

// Generated Nov 8, 2010 9:37:30 AM by Hibernate Tools 3.3.0.GA

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * SapTrxDtrId generated by hbm2java
 */
@Entity
@Table(name="SAP_TRX_DTL", schema="SEM")
public class SapTrxDtl implements Serializable {

	private static final long serialVersionUID = 3374106084926821096L;
	
	private String flgdet="D";
	/*private Integer logid;
	private String hearun;
	private String linitm;*/
	private SapTrxDtlId id;
	private String refsem;
	private String amttyp;
	private String acctyp;
	private String accnum;
	private String spegli;
	private Double amtloc;
	private Double amtdoc;
	private String coscen;
	private String wbsele;
	private String intord;
	private String purdoc;
	private String purite;
	private String taxcod;
	private Double basloc;
	private Double basdoc;
	private Integer invref;
	private String yerinv;
	private String itminv;
	private String basdat;
	private String payterm;
	private String dscday1;
	private Double dscper1;
	private String dscday2;
	private Double dscper2;
	private String netpay;
	private String payblk;
	private String paymet;
	private String paysup;
	private String assign;
	private String linitmtxt;
	private String lontxt;
	private String wthcod1;
	private Double wthbasl1;
	private Double wthbasd1;
	private Double wthamtl1;
	private Double wthamtd1;
	private String wthcod2;
	private Double wthbasl2;
	private Double wthbasd2;
	private Double wthamtl2;
	private Double wthamtd2;
	private String wthcod3;
	private Double wthbasl3;
	private Double wthbasd3;
	private Double wthamtl3;
	private Double wthamtd3;
	private String refkey1;
	private String refkey2;
	private String refkey3;
	private String parbnk;
	private String traprt;
	private String assspgl;
	private String onenam1;
	private String onenam2;
	private String onenam3;
	private String onenam4;
	private String street;
	private String city01;
	private String poscod;
	private String perid;
	private String taxid;
	private String bnkkey;
	private String bnknam1;
	private String bnkacc;

	@Transient
	public String getFlgdet() {
		return flgdet;
	}

	public void setFlgdet(String flgdet) {
		this.flgdet = flgdet;
	}
	
	@EmbeddedId
	@AttributeOverrides( {
		@AttributeOverride(name = "logid", column = @Column(name = "LOGID", nullable = false, precision = 22, scale = 0)),
		@AttributeOverride(name = "hearun", column = @Column(name = "HEARUN", nullable = false, length = 4)),
		@AttributeOverride(name = "linitm", column = @Column(name = "LINITM", nullable = false, length = 3)) })
	public SapTrxDtlId getId() {
		return this.id;
	}

	public void setId(SapTrxDtlId id) {
		this.id = id;
	}

	@Column(name = "REFSEM", nullable = false)
	public String getRefsem() {
		return this.refsem;
	}

	public void setRefsem(String refsem) {
		this.refsem = refsem;
	}
	
	@Column(name = "AMTTYP", nullable = false)
	public String getAmttyp() {
		return this.amttyp;
	}

	public void setAmttyp(String amttyp) {
		this.amttyp = amttyp;
	}

	@Column(name = "ACCTYP", nullable = false)
	public String getAcctyp() {
		return this.acctyp;
	}

	public void setAcctyp(String acctyp) {
		this.acctyp = acctyp;
	}

	@Column(name = "ACCNUM", nullable = false)
	public String getAccnum() {
		return this.accnum;
	}

	public void setAccnum(String accnum) {
		this.accnum = accnum;
	}

	@Column(name = "SPEGLI")
	public String getSpegli() {
		return this.spegli;
	}

	public void setSpegli(String spegli) {
		this.spegli = spegli;
	}

	@Column(name = "AMTLOC", nullable = false, precision = 13)
	public Double getAmtloc() {
		return this.amtloc;
	}

	public void setAmtloc(Double amtloc) {
		this.amtloc = amtloc;
	}

	@Column(name = "AMTDOC", nullable = false, precision = 13)
	public Double getAmtdoc() {
		return this.amtdoc;
	}

	public void setAmtdoc(Double amtdoc) {
		this.amtdoc = amtdoc;
	}

	@Column(name = "COSCEN", nullable = false)
	public String getCoscen() {
		return this.coscen;
	}

	public void setCoscen(String coscen) {
		this.coscen = coscen;
	}

	@Column(name = "WBSELE")
	public String getWbsele() {
		return this.wbsele;
	}

	public void setWbsele(String wbsele) {
		this.wbsele = wbsele;
	}

	@Column(name = "INTORD")
	public String getIntord() {
		return this.intord;
	}

	public void setIntord(String intord) {
		this.intord = intord;
	}

	@Column(name = "PURDOC")
	public String getPurdoc() {
		return this.purdoc;
	}

	public void setPurdoc(String purdoc) {
		this.purdoc = purdoc;
	}

	@Column(name = "PURITE")
	public String getPurite() {
		return this.purite;
	}

	public void setPurite(String purite) {
		this.purite = purite;
	}

	@Column(name = "TAXCOD")
	public String getTaxcod() {
		return this.taxcod;
	}

	public void setTaxcod(String taxcod) {
		this.taxcod = taxcod;
	}

	@Column(name = "BASLOC", precision = 13)
	public Double getBasloc() {
		return this.basloc;
	}

	public void setBasloc(Double basloc) {
		this.basloc = basloc;
	}

	@Column(name = "BASDOC", precision = 13)
	public Double getBasdoc() {
		return this.basdoc;
	}

	public void setBasdoc(Double basdoc) {
		this.basdoc = basdoc;
	}

	@Column(name = "INVREF", precision = 10, scale = 0)
	public Integer getInvref() {
		return this.invref;
	}

	public void setInvref(Integer invref) {
		this.invref = invref;
	}

	@Column(name = "YERINV")
	public String getYerinv() {
		return this.yerinv;
	}

	public void setYerinv(String yerinv) {
		this.yerinv = yerinv;
	}

	@Column(name = "ITMINV")
	public String getItminv() {
		return this.itminv;
	}

	public void setItminv(String itminv) {
		this.itminv = itminv;
	}

	@Column(name = "BASDAT", nullable = false)
	public String getBasdat() {
		return this.basdat;
	}

	public void setBasdat(String basdat) {
		this.basdat = basdat;
	}

	@Column(name = "PAYTERM")
	public String getPayterm() {
		return this.payterm;
	}

	public void setPayterm(String payterm) {
		this.payterm = payterm;
	}

	@Column(name = "DSCDAY1")
	public String getDscday1() {
		return this.dscday1;
	}

	public void setDscday1(String dscday1) {
		this.dscday1 = dscday1;
	}

	@Column(name = "DSCPER1", precision = 6, scale = 3)
	public Double getDscper1() {
		return this.dscper1;
	}

	public void setDscper1(Double dscper1) {
		this.dscper1 = dscper1;
	}

	@Column(name = "DSCDAY2")
	public String getDscday2() {
		return this.dscday2;
	}

	public void setDscday2(String dscday2) {
		this.dscday2 = dscday2;
	}

	@Column(name = "DSCPER2", precision = 6, scale = 3)
	public Double getDscper2() {
		return this.dscper2;
	}

	public void setDscper2(Double dscper2) {
		this.dscper2 = dscper2;
	}

	@Column(name = "NETPAY")
	public String getNetpay() {
		return this.netpay;
	}

	public void setNetpay(String netpay) {
		this.netpay = netpay;
	}

	@Column(name = "PAYBLK")
	public String getPayblk() {
		return this.payblk;
	}

	public void setPayblk(String payblk) {
		this.payblk = payblk;
	}

	@Column(name = "PAYMET")
	public String getPaymet() {
		return this.paymet;
	}

	public void setPaymet(String paymet) {
		this.paymet = paymet;
	}

	@Column(name = "PAYSUP")
	public String getPaysup() {
		return this.paysup;
	}

	public void setPaysup(String paysup) {
		this.paysup = paysup;
	}

	@Column(name = "ASSIGN")
	public String getAssign() {
		return this.assign;
	}

	public void setAssign(String assign) {
		this.assign = assign;
	}

	@Column(name = "LINITMTXT")
	public String getLinitmtxt() {
		return this.linitmtxt;
	}

	public void setLinitmtxt(String linitmtxt) {
		this.linitmtxt = linitmtxt;
	}

	@Column(name = "LONTXT")
	public String getLontxt() {
		return this.lontxt;
	}

	public void setLontxt(String lontxt) {
		this.lontxt = lontxt;
	}

	@Column(name = "WTHCOD1")
	public String getWthcod1() {
		return this.wthcod1;
	}

	public void setWthcod1(String wthcod1) {
		this.wthcod1 = wthcod1;
	}

	@Column(name = "WTHBASL1", precision = 13)
	public Double getWthbasl1() {
		return this.wthbasl1;
	}

	public void setWthbasl1(Double wthbasl1) {
		this.wthbasl1 = wthbasl1;
	}

	@Column(name = "WTHBASD1", precision = 13)
	public Double getWthbasd1() {
		return this.wthbasd1;
	}

	public void setWthbasd1(Double wthbasd1) {
		this.wthbasd1 = wthbasd1;
	}

	@Column(name = "WTHAMTL1", precision = 13)
	public Double getWthamtl1() {
		return this.wthamtl1;
	}

	public void setWthamtl1(Double wthamtl1) {
		this.wthamtl1 = wthamtl1;
	}

	@Column(name = "WTHAMTD1", precision = 13)
	public Double getWthamtd1() {
		return this.wthamtd1;
	}

	public void setWthamtd1(Double wthamtd1) {
		this.wthamtd1 = wthamtd1;
	}

	@Column(name = "WTHCOD2")
	public String getWthcod2() {
		return this.wthcod2;
	}

	public void setWthcod2(String wthcod2) {
		this.wthcod2 = wthcod2;
	}

	@Column(name = "WTHBASL2", precision = 13)
	public Double getWthbasl2() {
		return this.wthbasl2;
	}

	public void setWthbasl2(Double wthbasl2) {
		this.wthbasl2 = wthbasl2;
	}

	@Column(name = "WTHBASD2", precision = 13)
	public Double getWthbasd2() {
		return this.wthbasd2;
	}

	public void setWthbasd2(Double wthbasd2) {
		this.wthbasd2 = wthbasd2;
	}

	@Column(name = "WTHAMTL2", precision = 13)
	public Double getWthamtl2() {
		return this.wthamtl2;
	}

	public void setWthamtl2(Double wthamtl2) {
		this.wthamtl2 = wthamtl2;
	}

	@Column(name = "WTHAMTD2", precision = 13)
	public Double getWthamtd2() {
		return this.wthamtd2;
	}

	public void setWthamtd2(Double wthamtd2) {
		this.wthamtd2 = wthamtd2;
	}

	@Column(name = "WTHCOD3")
	public String getWthcod3() {
		return this.wthcod3;
	}

	public void setWthcod3(String wthcod3) {
		this.wthcod3 = wthcod3;
	}

	@Column(name = "WTHBASL3", precision = 13)
	public Double getWthbasl3() {
		return this.wthbasl3;
	}

	public void setWthbasl3(Double wthbasl3) {
		this.wthbasl3 = wthbasl3;
	}

	@Column(name = "WTHBASD3", precision = 13)
	public Double getWthbasd3() {
		return this.wthbasd3;
	}

	public void setWthbasd3(Double wthbasd3) {
		this.wthbasd3 = wthbasd3;
	}

	@Column(name = "WTHAMTL3", precision = 13)
	public Double getWthamtl3() {
		return this.wthamtl3;
	}

	public void setWthamtl3(Double wthamtl3) {
		this.wthamtl3 = wthamtl3;
	}

	@Column(name = "WTHAMTD3", precision = 13)
	public Double getWthamtd3() {
		return this.wthamtd3;
	}

	public void setWthamtd3(Double wthamtd3) {
		this.wthamtd3 = wthamtd3;
	}

	@Column(name = "REFKEY1")
	public String getRefkey1() {
		return this.refkey1;
	}

	public void setRefkey1(String refkey1) {
		this.refkey1 = refkey1;
	}

	@Column(name = "REFKEY2")
	public String getRefkey2() {
		return this.refkey2;
	}

	public void setRefkey2(String refkey2) {
		this.refkey2 = refkey2;
	}

	@Column(name = "REFKEY3")
	public String getRefkey3() {
		return this.refkey3;
	}

	public void setRefkey3(String refkey3) {
		this.refkey3 = refkey3;
	}

	@Column(name = "PARBNK")
	public String getParbnk() {
		return this.parbnk;
	}

	public void setParbnk(String parbnk) {
		this.parbnk = parbnk;
	}

	@Column(name = "TRAPRT")
	public String getTraprt() {
		return this.traprt;
	}

	public void setTraprt(String traprt) {
		this.traprt = traprt;
	}

	@Column(name = "ASSSPGL")
	public String getAssspgl() {
		return this.assspgl;
	}

	public void setAssspgl(String assspgl) {
		this.assspgl = assspgl;
	}

	@Column(name = "ONENAM1")
	public String getOnenam1() {
		return this.onenam1;
	}

	public void setOnenam1(String onenam1) {
		this.onenam1 = onenam1;
	}

	@Column(name = "ONENAM2")
	public String getOnenam2() {
		return this.onenam2;
	}

	public void setOnenam2(String onenam2) {
		this.onenam2 = onenam2;
	}

	@Column(name = "ONENAM3")
	public String getOnenam3() {
		return this.onenam3;
	}

	public void setOnenam3(String onenam3) {
		this.onenam3 = onenam3;
	}

	@Column(name = "ONENAM4")
	public String getOnenam4() {
		return this.onenam4;
	}

	public void setOnenam4(String onenam4) {
		this.onenam4 = onenam4;
	}

	@Column(name = "STREET")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CITY01")
	public String getCity01() {
		return this.city01;
	}

	public void setCity01(String city01) {
		this.city01 = city01;
	}

	@Column(name = "POSCOD")
	public String getPoscod() {
		return this.poscod;
	}

	public void setPoscod(String poscod) {
		this.poscod = poscod;
	}

	@Column(name = "PERID")
	public String getPerid() {
		return this.perid;
	}

	public void setPerid(String perid) {
		this.perid = perid;
	}

	@Column(name = "TAXID")
	public String getTaxid() {
		return this.taxid;
	}

	public void setTaxid(String taxid) {
		this.taxid = taxid;
	}

	@Column(name = "BNKKEY")
	public String getBnkkey() {
		return this.bnkkey;
	}

	public void setBnkkey(String bnkkey) {
		this.bnkkey = bnkkey;
	}

	@Column(name = "BNKNAM1")
	public String getBnknam1() {
		return this.bnknam1;
	}

	public void setBnknam1(String bnknam1) {
		this.bnknam1 = bnknam1;
	}

	@Column(name = "BNKACC")
	public String getBnkacc() {
		return this.bnkacc;
	}

	public void setBnkacc(String bnkacc) {
		this.bnkacc = bnkacc;
	}

	/**
	 * Constructor
	 */
	public SapTrxDtl(){}
	public SapTrxDtl(Integer logid, String hearun,String linitm){
		this.id = new SapTrxDtlId(logid, hearun, linitm);
	}
	public SapTrxDtl(Integer logid, String hearun, String refsem,
			String linitm, String amttyp, String acctyp, String accnum,
			Double amtloc, Double amtdoc, String coscen, String basdat) {
		/*this.logid = logid;
		this.hearun = hearun;
		this.linitm = linitm;*/
		this.id = new SapTrxDtlId(logid, hearun, linitm);
		this.refsem = refsem;
		this.amttyp = amttyp;
		this.acctyp = acctyp;
		this.accnum = accnum;
		this.amtloc = amtloc;
		this.amtdoc = amtdoc;
		this.coscen = coscen;
		this.basdat = basdat;
	}	
	public SapTrxDtl(Integer logid, String hearun, String refsem,
			String linitm, String amttyp, String acctyp, String accnum,
			String spegli, Double amtloc, Double amtdoc,
			String coscen, String wbsele, String intord, String purdoc,
			String purite, String taxcod, Double basloc, Double basdoc,
			Integer invref, String yerinv, String itminv, String basdat,
			String payterm, String dscday1, Double dscper1, String dscday2,
			Double dscper2, String netpay, String payblk,
			String paymet, String paysup, String assign, String linitmtxt,
			String lontxt, String wthcod1, Double wthbasl1,
			Double wthbasd1, Double wthamtl1, Double wthamtd1,
			String wthcod2, Double wthbasl2, Double wthbasd2,
			Double wthamtl2, Double wthamtd2, String wthcod3,
			Double wthbasl3, Double wthbasd3, Double wthamtl3,
			Double wthamtd3, String refkey1, String refkey2,
			String refkey3, String parbnk, String traprt, String assspgl,
			String onenam1, String onenam2, String onenam3, String onenam4,
			String street, String city01, String poscod, String perid,
			String taxid, String bnkkey, String bnknam1, String bnkacc) {
		/*this.logid = logid;
		this.hearun = hearun;
		this.linitm = linitm;*/
		this.id = new SapTrxDtlId(logid, hearun, linitm);
		this.refsem = refsem;		
		this.amttyp = amttyp;
		this.acctyp = acctyp;
		this.accnum = accnum;
		this.spegli = spegli;
		this.amtloc = amtloc;
		this.amtdoc = amtdoc;
		this.coscen = coscen;
		this.wbsele = wbsele;
		this.intord = intord;
		this.purdoc = purdoc;
		this.purite = purite;
		this.taxcod = taxcod;
		this.basloc = basloc;
		this.basdoc = basdoc;
		this.invref = invref;
		this.yerinv = yerinv;
		this.itminv = itminv;
		this.basdat = basdat;
		this.payterm = payterm;
		this.dscday1 = dscday1;
		this.dscper1 = dscper1;
		this.dscday2 = dscday2;
		this.dscper2 = dscper2;
		this.netpay = netpay;
		this.payblk = payblk;
		this.paymet = paymet;
		this.paysup = paysup;
		this.assign = assign;
		this.linitmtxt = linitmtxt;
		this.lontxt = lontxt;
		this.wthcod1 = wthcod1;
		this.wthbasl1 = wthbasl1;
		this.wthbasd1 = wthbasd1;
		this.wthamtl1 = wthamtl1;
		this.wthamtd1 = wthamtd1;
		this.wthcod2 = wthcod2;
		this.wthbasl2 = wthbasl2;
		this.wthbasd2 = wthbasd2;
		this.wthamtl2 = wthamtl2;
		this.wthamtd2 = wthamtd2;
		this.wthcod3 = wthcod3;
		this.wthbasl3 = wthbasl3;
		this.wthbasd3 = wthbasd3;
		this.wthamtl3 = wthamtl3;
		this.wthamtd3 = wthamtd3;
		this.refkey1 = refkey1;
		this.refkey2 = refkey2;
		this.refkey3 = refkey3;
		this.parbnk = parbnk;
		this.traprt = traprt;
		this.assspgl = assspgl;
		this.onenam1 = onenam1;
		this.onenam2 = onenam2;
		this.onenam3 = onenam3;
		this.onenam4 = onenam4;
		this.street = street;
		this.city01 = city01;
		this.poscod = poscod;
		this.perid = perid;
		this.taxid = taxid;
		this.bnkkey = bnkkey;
		this.bnknam1 = bnknam1;
		this.bnkacc = bnkacc;
	}
	
}
