package th.co.ais.domain.sap;

// Generated Nov 8, 2010 9:40:39 AM by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * SapTrxHdrId generated by hbm2java
 */
@Entity
@Table(name="SAP_TRX_HDR", schema="SEM")
public class SapTrxHdr implements Serializable {

	private static final long serialVersionUID = -7846503848930839727L;
	
	private String flghea="H";
	private SapTrxHdrId id;
	private String refsem;
	private String comcod;
	private String doctyp;
	private String refdoc;
	private String dochea;
	private String docdat;
	private String posdat;
	private String bracod;
	private String curcod;
	private Double excrat;
	private String tradat;
	private String textid1;
	private String exttxt11;
	private String exttxt12;
	private String exttxt13;
	private String exttxt14;
	private String textid2;
	private String exttxt21;
	private String exttxt22;
	private String exttxt23;
	private String exttxt24;
	private String textid3;
	private String exttxt31;
	private String exttxt32;
	private String exttxt33;
	private String exttxt34;
	private List<SapTrxDtl> sapTrxDtls;
		
	@EmbeddedId
	@AttributeOverrides( {
		@AttributeOverride(name = "logid", column = @Column(name = "LOGID", nullable = false, precision = 22, scale = 0)),
		@AttributeOverride(name = "hearun", column = @Column(name = "HEARUN", nullable = false, length = 4)) })
	public SapTrxHdrId getId() {
		return this.id;
	}
	
	public void setId(SapTrxHdrId id) {
		this.id = id;
	}
	
	@Transient
	public String getFlghea() {
		return flghea;
	}

	public void setFlghea(String flghea) {
		this.flghea = flghea;
	}	
	

	@Column(name = "REFSEM", nullable = false)
	public String getRefsem() {
		return this.refsem;
	}

	public void setRefsem(String refsem) {
		this.refsem = refsem;
	}

	@Column(name = "COMCOD", nullable = false)
	public String getComcod() {
		return this.comcod;
	}

	public void setComcod(String comcod) {
		this.comcod = comcod;
	}

	@Column(name = "DOCTYP", nullable = false)
	public String getDoctyp() {
		return this.doctyp;
	}

	public void setDoctyp(String doctyp) {
		this.doctyp = doctyp;
	}

	@Column(name = "REFDOC", nullable = false)
	public String getRefdoc() {
		return this.refdoc;
	}

	public void setRefdoc(String refdoc) {
		this.refdoc = refdoc;
	}

	@Column(name = "DOCHEA", nullable = false)
	public String getDochea() {
		return this.dochea;
	}

	public void setDochea(String dochea) {
		this.dochea = dochea;
	}

	@Column(name = "DOCDAT", nullable = false)
	public String getDocdat() {
		return this.docdat;
	}

	public void setDocdat(String docdat) {
		this.docdat = docdat;
	}

	@Column(name = "POSDAT", nullable = false)
	public String getPosdat() {
		return this.posdat;
	}

	public void setPosdat(String posdat) {
		this.posdat = posdat;
	}

	@Column(name = "BRACOD", nullable = false)
	public String getBracod() {
		return this.bracod;
	}

	public void setBracod(String bracod) {
		this.bracod = bracod;
	}

	@Column(name = "CURCOD", nullable = false)
	public String getCurcod() {
		return this.curcod;
	}

	public void setCurcod(String curcod) {
		this.curcod = curcod;
	}

	@Column(name = "EXCRAT", precision = 9, scale = 5)
	public Double getExcrat() {
		return this.excrat;
	}

	public void setExcrat(Double excrat) {
		this.excrat = excrat;
	}

	@Column(name = "TRADAT")
	public String getTradat() {
		return this.tradat;
	}

	public void setTradat(String tradat) {
		this.tradat = tradat;
	}

	@Column(name = "TEXTID1")
	public String getTextid1() {
		return this.textid1;
	}

	public void setTextid1(String textid1) {
		this.textid1 = textid1;
	}

	@Column(name = "EXTTXT11")
	public String getExttxt11() {
		return this.exttxt11;
	}

	public void setExttxt11(String exttxt11) {
		this.exttxt11 = exttxt11;
	}

	@Column(name = "EXTTXT12")
	public String getExttxt12() {
		return this.exttxt12;
	}

	public void setExttxt12(String exttxt12) {
		this.exttxt12 = exttxt12;
	}

	@Column(name = "EXTTXT13")
	public String getExttxt13() {
		return this.exttxt13;
	}

	public void setExttxt13(String exttxt13) {
		this.exttxt13 = exttxt13;
	}

	@Column(name = "EXTTXT14")
	public String getExttxt14() {
		return this.exttxt14;
	}

	public void setExttxt14(String exttxt14) {
		this.exttxt14 = exttxt14;
	}

	@Column(name = "TEXTID2")
	public String getTextid2() {
		return this.textid2;
	}

	public void setTextid2(String textid2) {
		this.textid2 = textid2;
	}

	@Column(name = "EXTTXT21")
	public String getExttxt21() {
		return this.exttxt21;
	}

	public void setExttxt21(String exttxt21) {
		this.exttxt21 = exttxt21;
	}

	@Column(name = "EXTTXT22")
	public String getExttxt22() {
		return this.exttxt22;
	}

	public void setExttxt22(String exttxt22) {
		this.exttxt22 = exttxt22;
	}

	@Column(name = "EXTTXT23", nullable = false)
	public String getExttxt23() {
		return this.exttxt23;
	}

	public void setExttxt23(String exttxt23) {
		this.exttxt23 = exttxt23;
	}

	@Column(name = "EXTTXT24")
	public String getExttxt24() {
		return this.exttxt24;
	}

	public void setExttxt24(String exttxt24) {
		this.exttxt24 = exttxt24;
	}

	@Column(name = "TEXTID3")
	public String getTextid3() {
		return this.textid3;
	}

	public void setTextid3(String textid3) {
		this.textid3 = textid3;
	}

	@Column(name = "EXTTXT31")
	public String getExttxt31() {
		return this.exttxt31;
	}

	public void setExttxt31(String exttxt31) {
		this.exttxt31 = exttxt31;
	}

	@Column(name = "EXTTXT32")
	public String getExttxt32() {
		return this.exttxt32;
	}

	public void setExttxt32(String exttxt32) {
		this.exttxt32 = exttxt32;
	}

	@Column(name = "EXTTXT33")
	public String getExttxt33() {
		return this.exttxt33;
	}

	public void setExttxt33(String exttxt33) {
		this.exttxt33 = exttxt33;
	}

	@Column(name = "EXTTXT34")
	public String getExttxt34() {
		return this.exttxt34;
	}

	public void setExttxt34(String exttxt34) {
		this.exttxt34 = exttxt34;
	}

	@Transient
	public List<SapTrxDtl> getSapTrxDtls() {
		return sapTrxDtls;
	}

	public void setSapTrxDtls(List<SapTrxDtl> sapTrxDtls) {
		this.sapTrxDtls = sapTrxDtls;
	}

	/**
	 * Constructor
	 */
	public SapTrxHdr() {}
	public SapTrxHdr(Integer logid, String hearun){
		this.id = new SapTrxHdrId(logid, hearun);
	}
	public SapTrxHdr(Integer logid, String hearun, String refsem,
			String comcod, String doctyp, String refdoc, String dochea,
			String docdat, String posdat, String bracod, String curcod,
			String exttxt23) {
		this.id = new SapTrxHdrId(logid, hearun);
		this.refsem = refsem;
		this.comcod = comcod;
		this.doctyp = doctyp;
		this.refdoc = refdoc;
		this.dochea = dochea;
		this.docdat = docdat;
		this.posdat = posdat;
		this.bracod = bracod;
		this.curcod = curcod;
		this.exttxt23 = exttxt23;
	}
	public SapTrxHdr(Integer logid, String hearun, String refsem,
			String comcod, String doctyp, String refdoc, String dochea,
			String docdat, String posdat, String bracod, String curcod,
			Double excrat, String tradat, String textid1, String exttxt11,
			String exttxt12, String exttxt13, String exttxt14, String textid2,
			String exttxt21, String exttxt22, String exttxt23, String exttxt24,
			String textid3, String exttxt31, String exttxt32, String exttxt33,
			String exttxt34) {
		this.id = new SapTrxHdrId(logid, hearun);
		this.refsem = refsem;
		this.comcod = comcod;
		this.doctyp = doctyp;
		this.refdoc = refdoc;
		this.dochea = dochea;
		this.docdat = docdat;
		this.posdat = posdat;
		this.bracod = bracod;
		this.curcod = curcod;
		this.excrat = excrat;
		this.tradat = tradat;
		this.textid1 = textid1;
		this.exttxt11 = exttxt11;
		this.exttxt12 = exttxt12;
		this.exttxt13 = exttxt13;
		this.exttxt14 = exttxt14;
		this.textid2 = textid2;
		this.exttxt21 = exttxt21;
		this.exttxt22 = exttxt22;
		this.exttxt23 = exttxt23;
		this.exttxt24 = exttxt24;
		this.textid3 = textid3;
		this.exttxt31 = exttxt31;
		this.exttxt32 = exttxt32;
		this.exttxt33 = exttxt33;
		this.exttxt34 = exttxt34;
	}
}
