package th.co.ais.domain.sap;

// Generated Nov 11, 2010 5:53:23 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SapTrxHdrId generated by hbm2java
 */
@Embeddable
public class SapTrxHdrId implements java.io.Serializable {

	private static final long serialVersionUID = -8114637402080744639L;
	private Integer logid;
	private String hearun;

	public SapTrxHdrId() {
	}

	public SapTrxHdrId(Integer logid, String hearun) {
		this.logid = logid;
		this.hearun = hearun;
	}

	@Column(name = "LOGID", nullable = false, precision = 22, scale = 0)
	public Integer getLogid() {
		return this.logid;
	}

	public void setLogid(Integer logid) {
		this.logid = logid;
	}

	@Column(name = "HEARUN", nullable = false, length = 4)
	public String getHearun() {
		return this.hearun;
	}

	public void setHearun(String hearun) {
		this.hearun = hearun;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SapTrxHdrId))
			return false;
		SapTrxHdrId castOther = (SapTrxHdrId) other;

		return ((this.getLogid() == castOther.getLogid()) || (this.getLogid() != null
				&& castOther.getLogid() != null && this.getLogid().equals(
				castOther.getLogid())))
				&& ((this.getHearun() == castOther.getHearun()) || (this
						.getHearun() != null
						&& castOther.getHearun() != null && this.getHearun()
						.equals(castOther.getHearun())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLogid() == null ? 0 : this.getLogid().hashCode());
		result = 37 * result
				+ (getHearun() == null ? 0 : this.getHearun().hashCode());
		return result;
	}

}
